### ISSUE TITLE
Having trouble with ImageMagick filters on production server.

### ISSUE THREAD

**Issue by pixeljitsu** [aelvan/Imager-Craft#1]
First off awesome work!  I hope you can help me resolve this.

Everything works as expected locally on MAMP, but for some reason any ImageMagick filter fails with a 404 on my live server.  ImageMagick is installed: 

imagick:
imagick module version	3.1.2
imagick classes	Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator
ImageMagick version	ImageMagick 6.7.2-7 2015-07-23 Q16 http://www.imagemagick.org
ImageMagick copyright	Copyright (C) 1999-2011 ImageMagick Studio LLC
ImageMagick release date	2015-07-23

and /tmp is writable

{# DETECT DEVICE TYPE #}
{% set deviceType = craft.lj_mobiledetect.type %}
{# IMAGE CROP SETTINGS BASED ON DEVICE TYPE #}
{% if deviceType == 'phone' %}
  {% set imgWidth = 635 %}
  {% set imgHeight = 300 %}
{% else %}
  {% set imgWidth = 1440 %}
  {% set imgHeight = 680 %}
{% endif %}

{% set transformedImage = craft.imager.transformImage(image, { width : imgWidth, height : imgHeight, mode: 'crop' }) %}  

Works just fine, but the second I add a IM filter it throws the 404:

{% set transformedImage = craft.imager.transformImage(image, { width : imgWidth, height: imgHeight, mode : 'crop', effects: { greyscale : true, colorBlend: ['rgb(20, 39, 74)',1] }}) %}

I hope it is just something simple I'm over looking.  :)

**Comment by pixeljitsu** [comment]
Nevermind, I got it sorted: I had `['rgb(20, 39, 74)',1]` and not `['rgb(20, 39, 74),1']` which it needed.  Still it's strange that it worked locally with the bad parameter.  Anyway, nice work on this one :)

**Comment by aelvan** [comment]
Actually, the correct value is ['rgb(20, 39, 74)',1], so there's probably something weird going on in the colorBlend method. Did you check your php error log and the craft.log when this happend? Would be very helpful if you could reproduce the error and send me any errors in those logs!

**Comment by pixeljitsu** [comment]
As it turns out, the policy.xml files were different.  Once I changed the policy.xml on production everything worked as expected.  What confused me was that Craft would throw a 404 URL cannot be found error whenever ImageMagick bailed, so it seemed there was something wrong with the templates at first. Now that production is configured properly, I cannot see any issue with your plugin, everything is pretty fast with no noticeable lags.
