### ISSUE TITLE
Remote Image Output Path

### ISSUE THREAD

**Issue by spAnser** [aelvan/Imager-Craft#100]
When processing a remote image. The output folder being created is `imagerimages_pexels_com/photos/36900/` url output however references `imager/images_pexels_com/photos/36900/`.

I noticed this while attempting to just throw in some placeholder images and seeing how it worked with remote images.

**Comment by spAnser** [comment]
I had my `imagerSystemPath` set without a trailing slash. Adding the trailing slash fixes it. However I think this should probably work with and without the trailing slash.

**Comment by aelvan** [comment]
Yes, I Agree, I'll have a look at it.

**Comment by aelvan** [comment]
This has been fixed in the version 1.5.2.
