### ISSUE TITLE
Assets moved to different folder doesn't trigger cache clearing

### ISSUE THREAD

**Issue by GewoonRoy** [aelvan/Imager-Craft#103]
When an existing asset in a folder is moved to another folder the cache clearing isn't called. This means Imager will search to an old path and can't find the asset which will result in an Exception.

Is there a fix for this?

**Comment by aelvan** [comment]
Which cache are you referring to? The template cache?

**Comment by GewoonRoy** [comment]
@aelvan I'm still debugging this issue a little bit further. I will close this issue and get back to you when i found the issue if there is one for imager.
