### ISSUE TITLE
"allowUpscale" parameter shouldn't appear in Imgix URL

### ISSUE THREAD

**Issue by benface** [aelvan/Imager-Craft#111]
The `allowUpscale: false` parameter seems to work fine with Imgix (in that it limits the `w` parameter that is sent to Imgix to the width of the original image), however it gets added to the list of query string parameters in the Imgix URL, which still works (the image loads fine) but causes a weird issue with Facebook Open Graph. The reason is that weirdly, Facebook changes `?allowUpscale=&` to `?allowUpscale&` and even more weirdly, that makes Imgix return a 404.

**Comment by aelvan** [comment]
This has been fixed in v1.6.2.
