### ISSUE TITLE
Target folder does not exist and could not be created.

### ISSUE THREAD

**Issue by cmalven** [aelvan/Imager-Craft#113]
I have a couple of Craft sites using Imager which have existed for more than 6 months now, both of which are using Amazon S3 as an asset source.

On my previous computer (running Mac OS El Capitan) both of these sites worked locally with no problem. Recently, I purchased a new computer running Mac OS Sierra, and for both of these sites – using the exact same environment and Imager config – I am getting the following error:

`Target folder “/imager/s3_amazonaws_com/my-project/images/” does not exist and could not be created`

in `/imager/services/ImagerService.php(228)`

Given that these sites are set up in the exact same way that they were on my previous machine, and that they're both running without issue in production using the exact same Imager config, I have no idea how to even approach trying to track down the issue.

Have you seen anything like this before? Any suggestions for what to try or where to check for the source of the problem? Thank you!

**Comment by aelvan** [comment]
Sorry for the late reply. You've maybe solved it already, but I'm pretty sure that this has to do with permissions. Maybe the owner/group information got messed up when moving from you old computer. Or maybe the webserver is now running as a different user than before. I'd start by maybe creating a new project, see of that works, and then making sure that the permissions are correct on the old ones?

**Comment by cmalven** [comment]
Thanks for the response @aelvan. To test this:

-  I created a completely new Craft project, reset permissions for all Craft-related folders the way I do for every project
- installed `Imager` plugin
- Copied the imager config from one of the problematic existing projects
- Set up a new asset source in Craft connected to S3 and added some images to it
- Added one of these images to a craft entry and attempted to output it using `{% set transformedImage = craft.imager.transformImage(entry.image[0], { width: 1000 }) %} <img src="{{ transformedImage.url }}">`

Result is the exact same error I reported above.

Is the `Target folder` it is failing to find/create local or on s3? Because I can find a directory both locally at `/craft/storage/runtime/` _and_ on S3 that matches the path in this error.

For reference, this is the full Imager config I'm using:

```php
return array(

  // Progressive Images
  'interlace' => true,
  'allowUpscale' => false,

  // AWS Config
  'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/imager/',
  'imagerUrl' => 'https://s3-us-west-2.amazonaws.com/imager-test/imager/',
  'awsEnabled' => true,
  'awsAccessKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  'awsSecretAccessKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  'awsBucket' => 'imager-test',
  'awsFolder' => 'imager'
);
```

**Comment by aelvan** [comment]
The target folder is locally. 

From the error it seems like `$_SERVER['DOCUMENT_ROOT']`returns an empty string. What webserver are you running?

**Comment by cmalven** [comment]
Webserver is Laravel Valet, which I believe is using some nginx/caddy combination behind the scenes.

**Comment by cmalven** [comment]
This definitely looks like a strong clue https://github.com/laravel/valet/issues/220

I'll do a little bit of investigation there.

**Comment by aelvan** [comment]
Try adding the full path to your imager path instead of using `$_SERVER['DOCUMENT_ROOT']`. Like:

```
'imagerSystemPath' => '/Users/youruser/path/to/project/imager/',
```

Since you have aws enabled, I'm guessing that this has been wrongly configured all along, but you just haven't encountered the problem because the created images are uploaded to aws. The reason why this has become a problem now is probably that newer versions of OSX restricts access to the root, so you can't create a folder on root (which `/imager/s3_amazonaws_com/my-project/images/` is) without elevanted permissions.

**Comment by cmalven** [comment]
Thanks @aelvan I switched to using a hard-coded `imagerSystemPath` and it cleared up the problem. You're likely write about the reason this slipped under the radar for so long. In any case, thanks for helping track down the issue (and for all of the work you do on Imager!)
