### ISSUE TITLE
Feature request: Base64 as image source possible?

### ISSUE THREAD

**Issue by romadev** [aelvan/Imager-Craft#115]
Hi there! Perfect plugin, but: could it be possible to transform base64-source images? This would be the perfect solution for an intense remote database based image website where the images are loaded in base64 format. Or how could this be done?

**Comment by aelvan** [comment]
How do you envision those images being passed to Imager? Would you pass a base64 encoded blob from the template? Or would there be an URL that returned the base64 blob?
