### ISSUE TITLE
Garbled WebP Output

### ISSUE THREAD

**Issue by jeremyfrank** [aelvan/Imager-Craft#116]
I'm seeing some issues with images converted to the WebP format. Depending on the width specified, it will either display completely white, or garbled with diagonal white lines (see below).

![image](https://user-images.githubusercontent.com/283397/29046448-86e52ef2-7b95-11e7-9b67-bf42502e77b1.png)

Conversion settings used were:

```
craft.imager.transformImage(image, { format: 'jpg', width: 400 })
craft.imager.transformImage(image, { format: 'webp', width: 400, webpQuality: 80 })
```

I also tried setting `useCwebp: true` and a few different things in `webpImagickOptions`. The variable `craft.imager.serverSupportsWebp` also returns true.

I originally had installed imagemagick via homebrew with `brew install imagemagick --with-webp` and imagick (so that it could reference the new imagemagick) with `pecl install imagick`. The PHP Info panel in Craft shows the correct versions of imagemagick, and also WEBP as a supported image format.

The strange thing is that converting an image to WebP via the command line or directly in PHP works as expected (see below):

![image](https://user-images.githubusercontent.com/283397/29046697-98fa3afa-7b96-11e7-90d2-e3006435e190.png)

**Comment by aelvan** [comment]
Hmm, I've seen similar results when using the webp support in GD, which is really bad. Are you sure you're using Imagick as the image driver?

When using `useCwebp: true`, did you have cwebp installed?

**Comment by jeremyfrank** [comment]
Yeah. The _Server Info_ tab in Craft shows the ImageMagick extension with a green check mark, and the _PHP Info_ tab shows imagick pointing to the version of ImageMagick that was compiled with WebP support (7.0.6-5 in my case).

I did also try `useCwebp: true`(with cwebp installed) and got the same results.

**Comment by aelvan** [comment]
I've tested in ImageMagick 7, and can confirm the bug. It appears that the new version of Imagick/ImageMagick doesn't like that I was enabling the alpha channel for all images. I've added a check to prevent it from being added for images without one. The fix will be in the next version of Imager which will be pushed shortly.

Not sure why you got the same result with `useCwebp: true` though, that worked fine for me. Are you sure the garbled image wasn't cached?

**Comment by jeremyfrank** [comment]
Thanks for looking into this so quickly! I did end up updating Imager after you implemented the check and that resolved things. Also yes, it's entirely possible that when I switched to cwebp, the transformed image had been previously cached.
