### ISSUE TITLE
mozjpeg handling is incorrect

### ISSUE THREAD

**Issue by khalwat** [aelvan/Imager-Craft#117]
So this one is my fault... the handling of `mozjpeg` is incorrect. Using the setup as it is now, it won't harm anything, but none of the images will be optimized.

Using the command as it is now, what happens is the compressed image data is sent to `stdout` and the file is not modified:

```
/usr/bin/mozjpeg -optimize -copy none '/home/vagrant/sites/craft3/storage/runtime/temp/painted-face5987ee5b801728.25302839.jpg'
```

Unlike the other optimizers, `mozjpeg` can't optimize _in situ_, or if it can, I haven't been able to figure out how. Instead, you need to pass in the `-outfile` flag with a path to the file the output should be written to. This can be the same file path as the input file:

```
/usr/bin/mozjpeg -optimize -copy none  -outfile '/home/vagrant/sites/craft3/storage/runtime/temp/painted-face5987ee5b801728.25302839.jpg' '/home/vagrant/sites/craft3/storage/runtime/temp/painted-face5987ee5b801728.25302839.jpg'
```

Here's how I handled it in the ImageOptimize plugin for Craft 3: https://github.com/nystudio107/craft3-imageoptimize/blob/master/src/services/Optimize.php#L185

**Comment by aelvan** [comment]
Looking at the code, it appears that I'm already doing this in Imager (see https://github.com/aelvan/Imager-Craft/blob/master/imager/services/ImagerService.php#L1656). 

How did you reproduce this error in Imager?

**Comment by khalwat** [comment]
Wow, I gave you the wrong info, did it wrong in my plugin... but you did it right. Closing the ticket, and walking slowly away :)
