### ISSUE TITLE
Opacity and blendMode not working 

### ISSUE THREAD

**Issue by middle8media** [aelvan/Imager-Craft#119]
The logo appears over the image, width/height and positioning all work as expected, but opacity and blendMode are not taking effect.

I have `Version: ImageMagick 7.0.6-5` installed.

```
{% set image = entry.aboutImage.first() %}
{% set logo = craft.assets({ id: 133 }).first() %}
{% set watermarkedImage = craft.imager.transformImage(image, {
    width: 600,
    watermark: { image: logo, width: 428, height: 105, position: { right: 75, top: 175 }, opacity: 0.3, blendMode: 'blend' }
}) %}

<img src="{{ watermarkedImage.url }}">
```

Maybe I missed an ImageMagick option during install?

**Comment by aelvan** [comment]
I've tested this on ImageMagick 6 and 7, and can confirm that it works. 

If you see the watermark image on the original but without the opacity and blend mode, I'm guessing that Craft/Imager isn't using Imagick, but GD, which doesn't support this. Try adding `'imageDriver' => 'imagick',` to your general.php config file.

**Comment by Bcdo** [comment]
I have the same issue, where the effects that does not require the imagick works, but the effects that uses imagick does not work. I have added the 'imageDriver' => 'imagick', to the general.php config file, but it does not do anything different.
