### ISSUE TITLE
How to set a subfolder in S3?

### ISSUE THREAD

**Issue by robzor** [aelvan/Imager-Craft#12]
Hi @aelvan, loving the plug-in, can't believe how much faster it is.

I've got a site with multiple locales so I'm serving images from S3. Everything appears to work ok apart from the fact I can't set a subfolder for the transforms to live on the S3. 

i.e.
`'imagerUrl' => 'http://s3-eu-west-1.amazonaws.com/<bucketname>/_imagertransforms/',`

doesn't work, the only way I can get transforms from the S3 is without a subfolder. Any ideas?

Thanks,

Rob

**Comment by aelvan** [comment]
Right, that's not possible right now. Why do you need it as a subfolder, do you share the bucket between different sites? Or do you use the same bucket as an asset source and for the transformed files?

It's a nice feature request though, shouldn't be that much work to implement.

**Comment by robzor** [comment]
Thanks for getting back to me,

Currently we use the same bucket as an asset source, but I guess we could set up a separate bucket for the transforms.

**Comment by aelvan** [comment]
This has been added as a new config setting in 1.0.2.
