### ISSUE TITLE
Replace local files with dummy files when using s3

### ISSUE THREAD

**Issue by RichardGG** [aelvan/Imager-Craft#121]
Found this idea by @joepagan on another issue https://github.com/aelvan/Imager-Craft/issues/65, thought it deserved its own thread. Replacing the local images with empty files would save a lot of wasted space.

> Hey @aelvan
>
> Wondering if you would ever consider this going forward?
> 
> Larger sites that could have 50,000+ product pages would have multiple versions of the same image is definitely going to be an issue in this case.
> 
> It would certainly be nice to be given the option if one dev wanted speed, or, another dev wanted storage space.
> 
> As an alternative quick fix, what if you were to use a 0 byte txt file locally in it's place instead? If the txt file is deleted regen the transform and upload?
> 
> Might be better to have an assettransformindex table like craft does to know if the transform has been generated, but, I appreciate that could be a bit more work.

**Comment by aelvan** [comment]
This wont be fixed for the Craft 2 version. I'll take it into consideration when I port the plugin to Craft 3.
