### ISSUE TITLE
Errors when source path does not exist

### ISSUE THREAD

**Issue by antcooper** [aelvan/Imager-Craft#122]
I've noticed that if an image subfolder is missing, the transform throws a Craft Error rather than failing gracefully:

**Internal Server Error**
Source folder “/srv/users/serverpilot/apps/myapp/public/uploads/articles/71793/” does not exist

Is it possible to handle this better? Many thanks.

**Comment by wei2go** [comment]
It also happens when the image file itself does not exist. I know it might be very unlikely to happen, but it would be better to have a fallback (e.g. show original image) instead of killing the whole page.

**Comment by aelvan** [comment]
By setting the `suppressExceptions` config setting to `true`, the exception will not be thrown and instead `null` will be returned to the template. This can be used to fall back to the original image, a fall back image, or whatever.
