### ISSUE TITLE
Letterbox: Rounding error throws Exception (Because of precision)

### ISSUE THREAD

**Issue by christianruhstaller** [aelvan/Imager-Craft#124]
If you have special case the calculation of the width/height returns an rounding error which will create a one pixel offset which results in a Exception in the Point.php:

`A coordinate cannot be positioned outside of a bounding box (x: 0, y: -1 given)`

In this specific case I describe the bug when the width will be used as a guide in ImagerService.php but will also be true for the height (ImagerService.php on line 865-870)

Given following:
The image is 340x340px in size.

The transform: 
```
{
    width: 250,
    height: 250,
    mode:  'letterbox',
}
```
Line 870 creates the rounding error:

```
$height = ceil($originalSize->getHeight() * ($width / $originalSize->getWidth()));
```

This will display 250 as a result. But will be rounded to 251. But how? Because the calculation goes like this:

```
$originalSize->getHeight() = 340
$width = 250
$originalSize->getWidth() = 340
```

`(250 / 340) = 0.735294117647059`

But php will give following result:
`0.73529411764706`

So the multiplication with 340 won't give the same result. 
PHP sets the precision by default on 14 which for this case is to unprecise.

The problem here is ceil. The other problem is when to decide to go 1 pixel up and when not to. For now just add or remove 1 pixel from the transformer and the problem should be solved for that specific case.  

This is quite an edge case in my opinion and maybe a **wontfix** but still wanted to share it if someone else has the problem: It's not your fault. :)

**Comment by aelvan** [comment]
Thanks for tracking down this bug!

I've implemented a fix for this in 1.6.4. The use of ceil() is needed when doing crops to ensure that you don't get blank pixels at the sides. I decided that the best fix was to not do the calculation at all if the aspect ratio of the original image and the transformed image is the same. If you you can think of any side-effects of this, or cases where this doesn't solve the original problem, please open this thread and let me know.
