### ISSUE TITLE
Property "Craft\Imager_ImageModel.0" is not defined.

### ISSUE THREAD

**Issue by helvetication** [aelvan/Imager-Craft#126]
I'm using Imager on my first project, and it's been great, but since I uploaded all the site content, I've started getting an internal server error on several pages: "Property "Craft\Imager_ImageModel.0" is not defined."

I was able to quell the error on one page by removing images from the entry one at a time. There was a particular image causing the page to throw that error, but I can't figure out why.

I can't check all the pages this way - they feature dozens of images from multiple entries. Do you have some insight into why this error gets thrown?

**Comment by aelvan** [comment]
Never seen that error before. Can you post the whole stack trace, either here or in a separate gist. And your template code that creates this image (try to strip it down to the minimum that creates the error).

**Comment by helvetication** [comment]
Sure. The stack trace is attached. 
[stack-trace.txt](https://github.com/aelvan/Imager-Craft/files/1261118/stack-trace.txt)

I'm using a macro for all my imager instances. In my template, I call it like this:

{% for image in game.gallery.limit(1) %}
    {{ macros.responsiveImg(image, {class:'game__thumb'}) }}
{% endfor %}

Here's the macro itself:

{% macro responsiveImg(image, params={}) %}

  {%- set defaults = {
    class: '', 
    sizes: [{width:2400},{width:1200},{width:1024},{width:768},{width:480}],
    ratio: 16/9,
    lazy: false,
    config: {
      format: 'jpg',
      allowUpscale: false,
      mode: 'crop',
      jpegQuality: 80,
      position: image.focusPctX ~ '% ' ~ image.focusPctY ~ '%',
      interlace: true,
    }
  } -%}

  {%- set params = defaults | merge(params) -%}

  {%- set sizes = [] -%}

  {%- for size in params.sizes -%}

    {%- if size.height -%}
      {%- set h = size.height -%}
    {%- elseif size.width -%}
      {%- set w = size.width -%}
    {%- endif -%}

    {%- if size.ratio -%}
      {%- set r = size.ratio -%}
    {%- else -%}
      {%- set r = params.ratio -%}
    {%- endif -%}

    {%- if h and h <= image.height -%}
      {%- set sizes = sizes | merge([{height: h, ratio: r}]) -%}
    {%- elseif w and w <= image.width -%}
      {%- set sizes = sizes | merge([{width: w, ratio: r}]) -%}
    {%- endif -%}
  {%- endfor -%}


  {%- set transformedImages = craft.imager.transformImage(image,sizes,params.config) %}


  {%- if params.lazy -%}
    <img class="lazyload {{params.class}}"
      src="{{craft.imager.base64Pixel(2,1)}}"
      data-sizes="auto"
      data-srcset="{{craft.imager.srcset(transformedImages)}}"
      alt="{{image.title}}" />
  {%- else -%}
    <img class="{{params.class}}"
      src="{{transformedImages[0]}}"
      sizes="100%"
      srcset="{{craft.imager.srcset(transformedImages)}}"
      alt="{{image.title}}" />
  {%- endif -%}

{% endmacro %}

**Comment by aelvan** [comment]
I'm guessing the problem is `src="{{transformedImages[0]}}"`. I believe that should be `src="{{transformedImages[0].url}}"`.

The error message is weird, but it might be because it's inside a macro. But try that and see if it helps.

**Comment by helvetication** [comment]
That got rid of the error, great! Thanks!
