### ISSUE TITLE
Feature Request: more control over save path?

### ISSUE THREAD

**Issue by BryceBubbles** [aelvan/Imager-Craft#127]
Firstly, Imager is amazing and I don't Craft without it.

This is a straight up feature request - would it be possible to have more control over the save path on a case by case basis? Partly for making paths shorter, but also for making different paths not bound by the source path. 

My general setup is:
- An uploads directory in root for all images uploaded via Craft. 
- Asset source directories inside uploads. 
- And sometimes sub-directories inside source directories - in order to sandbox which images can be seen/accessed in asset fields.

So say I had an image at:
`/uploads/products/category-slug/product-slug/some-fairly-long-image-name-that-was-uploaded.jpg`

By default it's saved to something crazy long like:
`/imager/uploads/products/category-slug/product-slug/123/some-fairly-long-image-name-that-was-uploaded_479ae72bdd7482352fa8b29e02f07ad3.jpg`

With hashFilename true and an extremely short imager directory name, it could be:
`/i/uploads/products/category-slug/product-slug/123/d4e2587509863008b59854cf8d132376.jpg`

Then hashPath true can be shorter:
`/i/bacffd8650c52165bfbd8cfaa29214f3/123/d4e2587509863008b59854cf8d132376.jpg`

But perhaps you still want some readability and want to keep the "category-slug/product-slug" part? 
So it would be nice if you could string replacing the "uploads/products" part with say "p":
`/i/p/category-slug/product-slug/123/d4e2587509863008b59854cf8d132376.jpg`
Or you could flatten the source path part into the filename:
`/i/p/category-slug-product-slug-123-d4e2587509863008b59854cf8d132376.jpg`

And a bit more extreme, perhaps for this specific transform you want to save to somewhere outside the imager directory, and you have unique products slugs in a channel, so you know there shouldn't be any clashes if you do:
`/product-images/product-slug-123-d4e2587509863008b59854cf8d132376.jpg`

Would be nice not to have the 123 from the numbered directory either, but I'm guessing it's needed for some reason I don't understand?

So to end my long request... I know the default path generation in Imager is made to be foolproof, and that this could cause issues if you don't know what you're doing. But if you know you want images in a specific place, named specifically, it would be nice to be able to opt in to doing that. 

So would some sort of setting for this be possible, or is there an internal reason why it wouldn't work?

Cheers

**Comment by aelvan** [comment]
Well, the main reason for maintaining the whole source + asset path inside the imager system path, is to avoid name collisions. If I skipped the source path for instance (a very early bug), images with the same path/filename in different sources would overwrite each other. The file id path segment is there to be able to do more fine-grained transform clearing (via the element action). There would be no way to clear transforms for one asset if all the transforms for that asset didn't have a common identificator, either in the filename or the path. 

Anyways, this is a common feature request, and I'll be looking at improving this - but only for the Craft 3 version.
