### ISSUE TITLE
Imgix path is missing in URL ?

### ISSUE THREAD

**Issue by 0xsven** [aelvan/Imager-Craft#129]
Support for imgix has caught my attention! I have upgraded imager to the latest version and deployed my s3 bucket with the original images to imgix. 

(in the examples below bucket and source have been replaced)

This is my s3 url:
`https://s3-us-west-1.amazonaws.com/my-bucket/work-summary/work1.jpg`

This is an imgix url that delivers the image just fine:
`https://mysource.imgix.net/work-summary/work1.jpg`

This is what imager spits out on my page:
`https://mysource.imgix.net/work1.jpg`

**As you can see the path `work-summary/` is missing in the imager URLs. Any idea why?** 

Here is my imager config:
```
  'imgixEnabled' => true,
  'imgixDomains' => ['mysource.imgix.net'],
  'imgixUseHttps' => true,
  'imgixSourceIsWebProxy' => false,
  'imgixShardStrategy' => 'cycle',
  'imgixGetExternalImageDimensions' => true
```

**Comment by 0xsven** [comment]
I have not set `imgixUseCloudSourcePath`. So the default `true` should be applied. Not sure why but the 'subfolder' is not added to the url for me..

> imgixUseCloudSourcePath [bool]
> 
> Default: true
> If enabled, Imager will prepend the Craft source path to the asset path, before passing it to the Imgix URL builder. This makes it possible to have one Imgix source pulling images from many Craft sources when they are on the same S3 bucket, but in different subfolder.

**Comment by 0xsven** [comment]
I have peeked a little into your code and have found this:

```
                if ((craft()->imager->getSetting('imgixUseCloudSourcePath', $transform) === true) && in_array($image->getSource()->type, array("S3", "Rackspace", "GoogleCloud"), true)) {
                    $path = implode("/", [$image->getSource()->settings['subfolder'], $image->getPath()]);
                } else {
                    $path = $image->path;
                }
```
So this means that the source needs to be an S3 source. This is the cause of my issues. I am using local sources and then upload the imager files via imager to S3! 

Hmm.. do I have to convert all my sources to S3 sources... ?

**Comment by aelvan** [comment]
Hi,
You don't have to have the files on S3, if the files are on a local server, you could set up a "Web Folder" source in Imgix and point it to you server. But that makes it a bit harder to use Imgix when developing locally.

> I am using local sources and then upload the imager files via imager to S3!

Not sure what you mean by this, but generally, if you use Imgix, all the transforms happen on Imgix' side, so all the settings for paths/urls/aws/etc in Imager, isn't really relevant anymore.

>Hmm.. do I have to convert all my sources to S3 sources... ?

You need to create a new source in Craft, set it up as you old one (don't forget custom fields), and move all the images over (which can be a problem if you have alot of images).

**Comment by 0xsven** [comment]
> Not sure what you mean by this, but generally...
What I wanted to say is that up to now I am using Local Folders for image sources. The transform would happen on my server and the result would be uploaded to S3 via imager. 

> You need to create a new source in Craft, set it up as you old one (don't forget custom fields), and move all the images over (which can be a problem if you have alot of images).
Okay I think this is the best solution. Will try that!

Thank you so much for creating this neat little library.

**Comment by 0xsven** [comment]
I have figured out a faster way:

1. Upload all original images to S3 manually (I have used Transmit for that)
2. Change the asset source to S3 and point it to the right folder (from step 1)

That's it :) Works

(Please don't try this on a staging server first)
