### ISSUE TITLE
Accessing Preparsed Imager transform URLS / srcset URLS

### ISSUE THREAD

**Issue by NickyTesla** [aelvan/Imager-Craft#130]
Hi there -- not sure if this is an issue or I'm just having an issue. 

I'm using Imager in conjunction with Preparse and the ElementAPI.   I'm trying to save all my image transforms on upload, and then export the URLS as part of the API.

Not sure how to access the URLS in the api though because I don't have access to the {{ craft.imager.srcset(transformedImages) }} like I would in a normal template, AFAIK.  

Is there a way to access the transformed URLS, or to easily save them to the Entry or something?

**Comment by NickyTesla** [comment]
OK, I think I figured it out.  Took me a bit to realized that the preparsed content was available in the 

You just output the preparsed template content as such: {{ craft.imager.srcset(transformedImages) }} and then reference the srcSet string in the the ElementAPI as $entry->preparsedContent.  

Hopefully this isn't too hard to apply to matrix fields with images

**Comment by aelvan** [comment]
It's actually no point using the value in the preparse field, if the only purpose is to pre-generate the image transforms. I'd actually advice against it, as there are cases where the images might be updated without the entry being resaved (ie, an image was moved, renamed, whatever). Then the preparsed value will be incorrect.

The whole point of pre-generating the transforms in the field, is that the next time you do the Imager transform, the cache will be used.
