### ISSUE TITLE
Curl Timeout at runPendingTasks

### ISSUE THREAD

**Issue by lukasNo1** [aelvan/Imager-Craft#131]
A call to the request url (shown below) takes longer than the defined 500ms Curl timeout, which leads to an error.

If I set the Timeout in craft/plugins/imager/services/ImagerService.php on line 1890 to 5000ms it works.

`$options[CURLOPT_TIMEOUT_MS] = 5000;`

Request url: https://www.DOMAIN.com/index.php?p=actions/tasks/runPendingTasks

Request for running tasks immediately failed with error number 28 and error message: Operation timed out after 500 milliseconds with 0 out of -1 bytes received

**Comment by aelvan** [comment]
The whole point of that curl call is to make the request time out as fast as possible. It's suppose to only trigger Crafts runPendingTasks, which will do the real work, and then time out as fast as possible to let the original request continue.

The flaw is that an error message is logged when it's doing what it's intended to do. :) I'll fix that at some point.

**Comment by aelvan** [comment]
Fixed for Imager 2.0.
