### ISSUE TITLE
Imager saving imges not in imager folder

### ISSUE THREAD

**Issue by kaspar-allenbach** [aelvan/Imager-Craft#132]
I'm diving into imager and I'm not sure if I'm doing this right or if I make wrong assumptions.

I have this code:

```

{% for asset in entry.image %}

  {% set tONEx = craft.imager.transformImage(asset, { width: 135, ratio: 1/1 }) %}
  {% set tTWOx = craft.imager.transformImage(asset, { width: 270, ratio: 1/1 }) %}

  <img
      alt="{{ imgParam.title }}"
      data-sizes="auto"
      data-srcset="
        {{ imgParam.url(transformParamONEx) }} 1x,
        {{ imgParam.url(transformParamTWOx) }} 2x"
      class="lazyload"
  />

{% endfor %}
```
So this works well but I see that in the folder structure the images are still saved in the parent folder of the images and not in the imager folder. Is imager even applied or are there still the native craftcms transforms applied?

**Comment by aelvan** [comment]
You're using a mix of Imager and Craft built-in transforms in this code. `imgParam` that you're referring to here isn't in the code sample, so not sure what that is. But, the correct way to implement Imager would be something like this:

```
{% for asset in entry.image %}

  {% set tONEx = craft.imager.transformImage(asset, { width: 135, ratio: 1/1 }) %}
  {% set tTWOx = craft.imager.transformImage(asset, { width: 270, ratio: 1/1 }) %}

  <img
      alt="{{ asset.title }}"
      data-sizes="auto"
      data-srcset="
        {{ tONEx.url }} 1x,
        {{ tTWOx.url }} 2x"
      class="lazyload"
  />

{% endfor %}
```

The reason why you were seeing images being created in the images folder (assuming you mean the assets source folder for your images?) is that you're using a Craft built-in transform when you do `imgParam.url(transformParamONEx)`. 

It does not explain why you don't see images being created in the Imager folder, they should when you do `craft.imager.transformImage(asset, { width: 135, ratio: 1/1 })`. If you still have issues, please provide more details regarding webserver- and config-setup.

**Comment by kaspar-allenbach** [comment]
Hi. Yeah my approach was all wrong. I now used your image tag examples closely. I thought I could just replace the craft transform tags and be done with it. 🤡
