### ISSUE TITLE
cURL error

### ISSUE THREAD

**Issue by dnizeix** [aelvan/Imager-Craft#133]
I am getting this fatal error:

> cURL error “7” encountered while attempting to download “http://my.old.ip.no/project-folder/public/assets/images/logos/logo_clientname.png”. The error was: “Failed to connect to my.old.ip.no port 80: Timed out”

My IP number changed, and apparently Imager is trying to fetch an image from an old, no longer valid URL.

I cleared all Craft caches, but the error persists.

**Comment by aelvan** [comment]
Have you changed the asset url to your new IP (assuming you're passing a Craft Asset to Imager)?
