### ISSUE TITLE
Unable to open SVG

### ISSUE THREAD

**Issue by artmem** [aelvan/Imager-Craft#136]
I'm using Imager with an assets field, and it works fine with jpgs and pngs, but when I try to use an svg,  I get an error:
Unable to open image assets/images/logo-ch.svg
/craft/app/vendor/pixelandtonic/imagine/lib/Imagine/Gd/Imagine.php(96)
`public function open($path)
... 
093         $resource = @imagecreatefromstring($data);
094 
095         if (!is_resource($resource)) {
096             throw new RuntimeException(sprintf('Unable to open image %s', $path));
097         }
`

**Comment by aelvan** [comment]
Looks like you are using GD as your image driver. As far as I know, GD has no support for SVGs at all. Imagick has support for opening SVGs, so you could in theory open them and save them to a bitmap format. But it's flaky at best, and it all depends alot on how the SVG is made.

I think the best option is to not use Imager at all to process SVGs. Use a conditional to check filetype, and do something else with it. :)
