### ISSUE TITLE
Support for named (ie, Admin/CP generated) asset transforms.

### ISSUE THREAD

**Issue by ncc-jwood** [aelvan/Imager-Craft#138]
It would be super helpful to be able to pass in the name of an asset transform that's already generated instead of having to create it inline.

**Comment by M-Drummond** [comment]
What about something like this :

`<img src="{{ craft.imager.transformImage( image, {width: image.getWidth('md') } ) }}"  title="{{ image.title }}" alt="{{ image.title }}" class="{{ class }}" >`

**Comment by aelvan** [comment]
Imager X added a concept of [named transforms](https://imager-x.spacecat.ninja/usage/named-transforms.html) (not the ones in the CP, but let's you define in a config file and reuse easily).
