### ISSUE TITLE
Imager with s3: Assets not uploading

### ISSUE THREAD

**Issue by rizzledizzle** [aelvan/Imager-Craft#140]
I've seen the other s3 issues at the moment but mine differs slightly. Imager transforms are being generated on the server (from s3 hosted files), but the transformed files are not being uploaded back to my S3 bucket. 

I've set up the `imagerUrl => https://my-bucket-name.s3.amazonaws.com/imager/`. When i go to load a page, i get a lot of 403 errors for the transformed images where it tries to find them at `https://my-bucket-name.s3.amazonaws.com/imager/`. When i look directly in the S3 bucket on the AWS console the `imager` folder has not been created and the filers aren't there. I've cleared all caches. Looking at the folder specified `imagerSystemPath` i can see the transformed files are there on my server, they just never make it to my bucket.

All native aspects of craft assets work fine with my s3 bucket (view, upload, delete). Have i missed something?

**Comment by aelvan** [comment]
Have you set up the aws config settings in Imager? Same user as the one you use in Craft?

Also, did you add this after having run the site with local transforms? If the transformed images already exists in your `imagerSystemPath`, they won't be uploaded automatically after changing the settings. You need to empty the Imager transformed images cache to force the uploading.

**Comment by rizzledizzle** [comment]
Hi Aelvan, sorry it looks like i was doing a few things wrong - the major one being incorrect key settings. one of those long days! working perfectly now - thanks for your help.
