### ISSUE TITLE
Imgix instructions need updating with how to find API key

### ISSUE THREAD

**Issue by tomdavies** [aelvan/Imager-Craft#141]
Imgix have changed both where your account API key can be found and what it's called.

You now need to go to click your name in the top bar => "Account" => "Show Key"

Currently Imager's instructions say:

```
'imgixSignKey' => '',  // this is also called `security token`, and you'll find it in your Imgix source 
```

Confused me for ages until I found it on the account page - happy to PR for this if you're busy!

**Comment by aelvan** [comment]
Hi Tom,

Not sure if this has actually changed. The imgixSignKey/security token is only available (and relevant) when you've set your source to be secure. 

As far as I can tell it's still there in our sources. The key in Account is the API key, which is not needed for doing transforms like this.

**Comment by tomdavies** [comment]
Hey André,

Thanks for the quick reply, yeah sorry I misunderstood. Developer is an idiot...

Cheers for Imager!

**Comment by aelvan** [comment]
Haha, no problem! Enjoy.
