### ISSUE TITLE
Server Requirements

### ISSUE THREAD

**Issue by sheixt** [aelvan/Imager-Craft#143]
After installing Imager on a project and moving it to a live environment we are having images saved (in the admin panel) without error however the files (within `imager/uploads/XXX/`) are not generated.

I'm lead to believe that this is an environment issue, probably where a PHP module or something isn't installed.

So that I can check the environment is setup correctly is it possible to have the server requirements for Imager? 

I think this would be beneficial for the Readme file for other user going forward.

**Comment by aelvan** [comment]
The requirements follow Crafts requirements. If Craft runs, and you're able to use the built-in trannsforms, you should be able to use Imager.

Do you get any errors, or are the images just not being transformed? I'd have a look at the `imagerSystemPath` setting, maybe trying to configure it with an absolute path. Not all servers return the correct path for `$_SERVER['DOCUMENT_ROOT']` ($_SERVER['DOCUMENT_ROOT'] . '/imager/' being the default setting).

**Comment by sheixt** [comment]
Firstly thanks for the rapid response!

I had assumed that Imager would be doing more with regards to the image compression.

To be honest, I have only utilised Imager (because is ace!) and have completely ignored the standard asset type. Perhaps I need to create a test bed with that before going forward.

I'll look at this today/tomorrow and will feedback with anything I find, just in case it can help anyone else. So if you don't mind leaving this issue open until then that would be great.

**Comment by aelvan** [comment]
Sure, let me know what you find out.

**Comment by sheixt** [comment]
I'm inclined to think this isn't a PHP module issue. After reviewing the `$server['DOCUMENT_ROOT'` as suggested, the response indeed seemed incorrect. 

Sadly, amending this hasn't fully resolved the issue. When viewing any page on the front-end, I encounter a craft error similar to this: `Internal Server Error. Target folder “388/” does not exist and could not be created`. 

The file path `/var/www/imager/uploads/` appears to be correct. 

Upon reviewing the `craft.log` file I can't seem to distinguish why this may happen.

`[error] [application] Tried to create a folder at /var/www/imager/uploads/388/, but could not.`
`error] [exception.Twig_Error_Runtime] exception 'Craft\Exception' with message 'Target folder “/var/www/imager/uploads/388/” does not exist and could not be created' in /SERVER_PATH/craft/plugins/imager/services/ImagerService.php:228` 

Don't suppose you could point me in the right direction?

(I've replaced the actual path with "SERVER_PATH" to obscure the site this is being used on due to a NDA.)

**Comment by aelvan** [comment]
This sounds like a permissions issue. If you have your assets locally, are you able to upload files to the server through Craft? Check that the permissions (and user/group) is the same on the imager folder as your uploads folder.

**Comment by Odusanya** [comment]
Hi @aelvan, I'm currently experiencing the same issue, can yes to answer your question, it works locally, but I get this error once I push to the remote server

**Comment by aelvan** [comment]
@Odusanya Ok, as I wrote, this sounds like a permissions issue. Are you able to create new folders and upload new images to the server via the Craft control panel? If so, can you compare the permissions of your asset source's folder with the image folder and check if they are the same? Make sure that the owner and group on the imager folders is the same as your webserver's running.

**Comment by Odusanya** [comment]
Hey @aelvan, you were right, just a quick update on how I solved this.

I simply updated the server permissions to allow `/var/www/imager/uploads/` or whatever your ImageSystemPath is, to read and write folders and sub-folders.

It was a simple permissions issue
