### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by timbertens** [aelvan/Imager-Craft#145]
I'm running CraftCMS 2.6.2999
and Imager 2.6.4

and I'm getting "A non-numeric value encountered" in 
/Applications/MAMP/htdocs/tcs.local/etc/plugins/imager/services/ImagerService.php(1025)

I believe I had it before with an older version of the plugin, but not 100% sure

```
1013      * @param $transform
1014      * @return \Imagine\Image\Point
1015      */
1016     private function _getCropPoint($resizeSize, $cropSize, $transform)
1017     {
1018         // get default crop position from the settings
1019         $position = $this->getSetting('position', $transform);
1020 
1021         // get the offsets, left and top, now as an int, representing the % offset
1022         list($leftOffset, $topOffset) = explode(' ', $position);
1023         
1024         // get position that crop should center around
1025         $leftPos = floor($resizeSize->getWidth() * ($leftOffset / 100)) - floor($cropSize->getWidth()/2);
1026         $topPos = floor($resizeSize->getHeight() * ($topOffset / 100)) - floor($cropSize->getHeight()/2);
1027         
1028         // make sure the point is within the boundaries and return the point
1029         return new \Imagine\Image\Point(
1030             min(max($leftPos, 0), ($resizeSize->getWidth() - $cropSize->getWidth())), 
1031             min(max($topPos, 0), ($resizeSize->getHeight() - $cropSize->getHeight()))
1032         );
1033     }
1034 
1035 
1036     /**
1037      * Returns the filter method for resize operations
```

**Comment by aelvan** [comment]
You're probably passing in an invalid value to the `position` parameter for one of your transforms. For debugging purposes, I'd try outputting the value you're passing to `position` to your template without doing the transform, and inspect those. It should either be one of the built in keywords (like `center-center`), or a percentage pair (like `50% 40%`).

**Comment by timbertens** [comment]
you are totally right, one of the dev's entered 'center center' instead of 'center-center'
for some reason the former has worked in previous versions.
anyhow, it is fixed now.  thanks for the quick help!
