### ISSUE TITLE
Optimized versions of transformed images not uploading to S3

### ISSUE THREAD

**Issue by cavellblood** [aelvan/Imager-Craft#149]
It doesn't seem like the optimized versions of the transformed images are being uploaded to S3. When I run a performance report with [GT Metrix](https://gtmetrix.com) on my site all the images have a cache time of 5 minutes. This corresponds to the [300 second default for `awsCacheDurationNonOptimized` config setting](https://github.com/aelvan/Imager-Craft#awscachedurationnonoptimized-int).

These same images are also reported as needing optimization.

The documentation mentions that the images will be replaced once the optimization has been run. I have `'jpegoptimEnabled' => true` and  `'optipngEnabled' => true` in my `config/imager.php` file and occasionally I'll see those tasks being run in the Craft control panel so that seems to be working.

Any suggestions on how to get the optimized versions uploaded to the S3 bucket? My initial thought was to change the `awsCacheDurationNonOptimized` to `1209600` and that would clear up the short cache time issue but not the optimizing issue.

**Comment by aelvan** [comment]
Any errors in the imager.log file, or the php error log? Are you sure that the path to jpegoptim and optipng is correct and PHP is able to trigger it at all?

Could also be that you're running into the issue described in this pull request: https://github.com/aelvan/Imager-Craft/pull/146

Could you try implementing that fix and see if it helps?

**Comment by cavellblood** [comment]
There is no `imager.log` file present and the `phperrors.log` only has a few errors that are related to UserSessionService.php from over a month ago.

I verified the paths for `jpegoptim` and `optipng`. I'm not sure how to test if php is able to trigger it. It seems that something is able to trigger is successfully when I see the task running in the Craft control panel. 

<img width="401" alt="screen shot 2017-12-27 at 3 45 24 pm" src="https://user-images.githubusercontent.com/727740/34394190-3bdd5b44-eb1d-11e7-8909-b38c98b34216.png">

**Comment by cavellblood** [comment]
I've increased the `max_execution_time` in the `php.ini` file to `300` and restarted `php7.1-fpm` and `nginx` and it seems to be working now! The cache time on the images is now `1209600` or 14 days.

So it seems that setting the `max_execution_time` to `300` fixed it.
