### ISSUE TITLE
Stripping or Preserving ICC Color Profiles

### ISSUE THREAD

**Issue by smockensturm** [aelvan/Imager-Craft#150]
Is Imager affected by this? Does Imager preserve color profiles?

https://craftcms.stackexchange.com/questions/14429/image-transform-is-turning-my-jpegs-dark

**Comment by fbnntt** [comment]
Having a similar problem here, any tips?

**Comment by aelvan** [comment]
Imager does not remove color profiles by default. If `removeMetadata` is set to `true`, all meta data, including color profiles, will be removed.
