### ISSUE TITLE
Base64 image throwing 404 errors in srcset

### ISSUE THREAD

**Issue by terryupton** [aelvan/Imager-Craft#151]
Bit of an odd one and I am not sure if Imager specific? 
I am using a practice in accordance with the lazysizes documentation and recommendation;
https://github.com/aFarkas/lazysizes#modern-transparent-srcset-pattern

So as an example my code for an image looks like this;
```
{% set image = entry.bannerImage.first() ?? fallbacks.bannerImage.first() %}
{% set mode = 'fit' %}
{% set imageSizes = [
    { width: 1560 },
    { width: 1200 },
    { width: 1000 },
    { width: 780 },
    { width: 600 },
] %}

{# Set Srcset Transform #}
{% set transformedImages = craft.imager.transformImage(image, imageSizes, { mode: mode, jpegQuality: 80 }) %}
{% set srcImage = transformedImages[2] %}


<noscript>
  <img src="{{ srcImage }}" alt="{{ entry.title }}" />
</noscript>
<img
  src="{{ srcImage }}"
  srcset="{{ craft.imager.base64Pixel(srcImage.width, srcImage.height) }}"
  data-sizes="auto"
  data-srcset="{{ craft.imager.srcset(transformedImages) }}"
  class="lazyload"
  alt="{{ entry.title }}"
/>
```
However, I am finding that when I do a link integrity check (using multiple applications) I am getting lots of 404 errors as it is finding the following urls where the srcset image is displayed e.g:
`http://cvpal.loc/<svg xmlns='http:/www.w3.org/2000/svg' width='8736' height='5824' style='background:transparent'/>`

Secondary to this when I view the actual source code (not inspector) I can see the following:
```
data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20width%3D%271000%27%20height%3D%27667%27%20style%3D%27background%3Atransparent%27%2F%3E
```
But it seems the browser is splitting this into two clickable elements the first part and the second part after the comma. The second part if clicked also links off to the 404 error above: `http://cvpal.loc/<svg xmlns='http:/www.w3.org/2000/svg' width='8736' height='5824' style='background:transparent'/>`

Not sure where to go from here? Not sure if this is because imager is actually include the protocol? or if it is a misinterpretation by the browsers and integrity tools?

Any thoughts/ideas?

**Comment by aelvan** [comment]
I haven't used that pattern, but I bet the issue is that the srcset attribute doesn't accept a base64 encode svg, which is what Imager returns. Just try replacing `{{ craft.imager.base64Pixel(srcImage.width, srcImage.height) }}` with the base64 encode gif from the example, `data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==`.

**Comment by terryupton** [comment]
Thanks @aelvan - does it matter that the example is just a 1px gif? I had thought the reason for the SVG to specify the width/height was to ensure the image was the right size initially? Does 'craft.imager.base64Pixel' only output SVG?

**Comment by aelvan** [comment]
Yes, at the moment it's SVG only. Should probably make more options for the Craft 3 version.
