### ISSUE TITLE
Including with ratio as variable

### ISSUE THREAD

**Issue by klick** [aelvan/Imager-Craft#153]
Hi.
I am trying to include a twig file containing an image transformation with passing the `ratio` value like so:

`{% include '_includes/header-image.twig' with {'ratio':'9/3'} %}`

In `_includes/header-image.twig` i grab the ratio and stuff it into the imager function like so:

`{ ratio: ratio, position: 'center-center', jpegQuality: 80 }`

The image comes out without any transformation applied. Does anyone have an idea what might the problem be here? I can print the variable just fine so no math operation is being done on 9/3. Also imager log has no complaints showing.

Thanks in advance.

**Comment by aelvan** [comment]
The ratio parameter takes a number value, not a string. Try:

```
{% include '_includes/header-image.twig' with {'ratio':9/3} %}
```

**Comment by klick** [comment]
I’m sure that i did try that and it didn’t work. Now it does. It’s late Friday here. I guess I should call it a week. 

Thanks!
