### ISSUE TITLE
Retina Images

### ISSUE THREAD

**Issue by DenisG0** [aelvan/Imager-Craft#154]
Hi,

I was wondering if there was a way to generate a srcset that responded to the 1x, 2x of retina images? 

Thank you!

**Comment by msiemens** [comment]
I'd be interested in this too!

**Comment by aelvan** [comment]
The idea of making images tailored to the pixel density of the screen (ie 2x, 3x, 3.14x, 4x, etc), really is an anti-pattern and not something you should use in 2018 unless you have some very specific use-case where it makes sense. What you should do instead is use srcset and sizes per the responsive images spec. I still find [this article by Eric Portis from 2014](https://ericportis.com/posts/2014/srcset-sizes/) being one of the best primers as to why this is the way to go. 

In short, by using sizes and srcset, the browser will be given the task to pick the most appropriate image from a range of images supplied by the srcset. Given the following img tag:

```
<img src="fallback.jpg" sizes="100vw" srcset="img1.jpg 400w, img2.jpg 600w, img3.jpg 800w, img4.jpg 1200px, img5.jpg 1600px">
```

Let's say you're on a legacy mobile phone with a screen resolution of 320x540px and a 1x pixel density, the browser will look at the supplied images and go, "Aha, the smallest image that is still bigger than the size of teh screen, is... img1.jpg, which is 400px wide".

Then, let's say you're on a more modern mobile with a screen resolution of 360x620px, and something like a 2x pixel density. The browser goes, "Aha, 360px, but the density is 2x, so we ideally want an image that's 720px wide... Let's pick img3.jpg, which is 800px!". 

But, you may also have a scenario like the last one, where the user in addition is on a slow connection, or maybe have turned on a setting in the browser to save bandwidth where possible, and the browser goes, "Hmm, ideally I would like to pick the 800px image, but seeing as that file probably is four times bigger than the 400px one... I'll pick the 400px one.".

So yeah, let the browser decide. :)

(And if you really want to create 1x and 2x images, you can with Imager, but you have to tell it what the 1x and 2x size should be. That's not something Imager would know, that's wholly dependant on your design.)

**Comment by wallythewebdev** [comment]
@aelvan - I know this answers was wrote a little while ago but I have a continuation to this question (its been driving me mad so any help would be great). 

What if (and in my case) you have different art directions for larger screens and smaller screens i.e. on a smaller screen you need the full zoomed out image, but on larger screens a zoomed in image (to fill space) _example below_.

![image](https://user-images.githubusercontent.com/28821463/147075504-4f63f775-cfb6-4b17-b941-a5a55710b7e8.png)

From the example above, you can see there is a lot of difference in visible space on the image and I'm trying to crop them so pixels that are not going to be seen (i.e. the whole cat on desktop) are not loaded. 

I've used a few variations of code below to try and achieve this (including transforming the image twice - one using `mode: 'fit'` for mobile and one using `mode: 'crop'` - but retina display devices (Iphones...) always use the cropped desktop version.  
  
```
    {% set headerImg = entry_dev.headerImage.image.one() %}

      {% set transformedheaderImg = craft.imager.transformImage(headerImg, [
      { width: 2000, ratio: 16/3, jpegQuality: 96 },
      { width: 1301, ratio: 16/3, jpegQuality: 95 },
      { width: 1025, ratio: 16/3, jpegQuality: 93 },
      { width: 769, ratio: 16/9, jpegQuality: 90 },
      { width: 569, ratio: 16/9, jpegQuality: 85 },
      { width: 401, ratio: 16/9, jpegQuality: 85 },
    ], { allowUpscale: false, mode: 'crop' }) %}

      <div class="header-image-wrapper {{ entry.headerImage.filter }}">
        <picture class="background-image careers-header-img">
          <source sizes="
          (max-width: 401px) 401px,
          (max-width: 569px) 569px,
          (max-width: 769px) 769px
          (max-width: 1025px) 1025px,
          (max-width: 1301px) 1301px,
          2000px"
          srcset="{{ craft.imager.srcset(transformedheaderImg) }}">

          <img src="{{ headerImg.url }}" alt="{{ headerImg.title }}" />
        </picture>
      </div>
```

Do you know of a way around this type of issue, I can see the benefit of the devices picking pixel density images to display, but this logic fails when you have a set image to show at different screen sizes. 

Thanks W
