### ISSUE TITLE
craft.imager.serverSupportsWebp() - Trying to get property of non-object

### ISSUE THREAD

**Issue by rjgux** [aelvan/Imager-Craft#156]
craft.imager.clientSupportsWebp() seems to work fine, but craft.imager.serverSupportsWebp() results in the following -

`yii\base\ErrorException: Trying to get property of non-object in /Users/rich/repos/empress/deploy/vendor/aelvan/imager/src/services/ImagerService.php:229
Stack trace:
#0 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/rich/rep...', 229)
#1 /Users/rich/repos/empress/deploy/vendor/aelvan/imager/src/services/ImagerService.php(229): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/rich/rep...', 229, Array)
#2 /Users/rich/repos/empress/deploy/vendor/aelvan/imager/src/variables/ImagerVariable.php(126): aelvan\imager\services\ImagerService::hasSupportForWebP()
#3 /Users/rich/repos/empress/deploy/vendor/twig/twig/lib/Twig/Extension/Core.php(1595): aelvan\imager\variables\ImagerVariable->serverSupportsWebp()
#4 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/helpers/Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(aelvan\imager\variables\ImagerVariable), 'serverSupportsW...', Array, 'method', false, false)
#5 /Users/rich/repos/empress/deploy/storage/runtime/compiled_templates/55/55d4116b11445ba1358ac87c98152d751f98bb0b7659f4eac70f3f8de9172f0f.php(34): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(aelvan\imager\variables\ImagerVariable), 'serverSupportsW...', Array, 'method')
#6 /Users/rich/repos/empress/deploy/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_04d1d65202612dcbbfc1f1c5bc693a3dd6a89119ec3aa180bdfe099df70f7183->doDisplay(Array, Array)
#7 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#8 /Users/rich/repos/empress/deploy/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#9 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#10 /Users/rich/repos/empress/deploy/storage/runtime/compiled_templates/bf/bf70d5e71167b935080bc05922d027347f1e095f143384641de5bb551d1ebbf1.php(27): craft\web\twig\Template->display(Array, Array)
#11 /Users/rich/repos/empress/deploy/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_b18cc2ca88e60d3398b187385ad00b2cd0a4d7613b61d3b7520d0fce601590f7->doDisplay(Array, Array)
#12 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /Users/rich/repos/empress/deploy/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#14 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#15 /Users/rich/repos/empress/deploy/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#16 /Users/rich/repos/empress/deploy/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#17 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('index', Array)
#18 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/View.php(356): craft\web\View->renderTemplate('index', Array)
#19 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/Controller.php(120): craft\web\View->renderPageTemplate('index', Array)
#20 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/controllers/TemplatesController.php(79): craft\web\Controller->renderTemplate('index', Array)
#21 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#22 /Users/rich/repos/empress/deploy/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /Users/rich/repos/empress/deploy/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('render', Array)
#25 /Users/rich/repos/empress/deploy/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#26 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/Application.php(240): yii\base\Module->runAction('templates/rende...', Array)
#27 /Users/rich/repos/empress/deploy/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#28 /Users/rich/repos/empress/deploy/vendor/craftcms/cms/src/web/Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 /Users/rich/repos/empress/deploy/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /Users/rich/repos/empress/deploy/public/index.php(35): yii\base\Application->run()
#31 {main}`

**Comment by aelvan** [comment]
This has been fixed. Thanks for reporting!
