### ISSUE TITLE
Source folder not found after upgrade to Craft 3

### ISSUE THREAD

**Issue by jnissenyt** [aelvan/Imager-Craft#157]
Hi! 

I am trying to upgrade my project to Craft 3. The installation of the plugin with composer worked fine but now I get this exception:

yii\base\Exception: Source folder “files/General” does not exist. 
in path/to/project/src/vendor/aelvan/imager/src/transformers/CraftTransformer.php:186

This folder does exist in the public/ folder and the imagerSystemPath is set to the public folder. 

Since I have only recently started working with Craft und Imager, I don't know what causes this problem. I would highly appreciate it, if you maybe have a hint on how to solve this. 

Thank you & kind regards
Julia

**Comment by aelvan** [comment]
Hi,

Sound like something's off with the way the asset source is set up, or a bug in Imager related to that. What's your asset source's File System Path?

**Comment by jnissenyt** [comment]
Hi,

the assets File System Path is assets/assets/

**Comment by aelvan** [comment]
Myeah, that probably won't work, you need to provide a full path. Something like `/myrootfolders/myprojectfolder/public/assets`.

Also, **very important**, you shouldn't set the `imagerSystemPath` to point directly to your public root (neither in Craft 2 nor 3). This has to be a separate folder for storing your transformed files. It will seemingly work, but if you go to the clear caches tool and delete imager transforms, it'll completely wipe out the contents of your public folder.

**Comment by jnissenyt** [comment]
Okay thanks, that worked! I still have to figure out how to set relative paths but this lets me work again, thanks a lot. 

I'm sorry, the imagerSystemPath is not my public folder but public/imager.

**Comment by aelvan** [comment]
Cool. 

Craft 3 uses Yii 2 aliases to make things like this more manageable if you need the path to be different depending on your environment. The current version of Imager 2.0 that's on github does not support this, but I have fixed this in my local dev-branch. Will push and tag a beta2 version shortly.

**Comment by jnissenyt** [comment]
Good to know, thank you!
