### ISSUE TITLE
Uninitialized string offset: 0 error

### ISSUE THREAD

**Issue by robzor** [aelvan/Imager-Craft#16]
Hi there,

I upgraded Imager and am now getting the error above when I load certain pages that request Imager transforms. I'm using S3 for all my assets.

Any ideas?

More info:

`src/plugins/imager/services/ImagerService.php(1467)`
```
if ($removeInitial && ($r[0] == '/')) {
  $r = substr($r, 1);
}
```

**Comment by aelvan** [comment]
Ah, yeah, I have an idea of why that happends. Let me check and I'll get back to you.

**Comment by aelvan** [comment]
Can you try to replace the imager/services/ImagerService.php file with this one:
[ImagerService.php.zip](https://github.com/aelvan/Imager-Craft/files/104975/ImagerService.php.zip)

**Comment by robzor** [comment]
Seems to have fixed it on my end, thanks! This is only with a quick test though, I'll let you know if I see anything else :)

**Comment by aelvan** [comment]
This bugfix has been rolled out in 1.0.3.
