### ISSUE TITLE
letterbox mode - padding

### ISSUE THREAD

**Issue by terryupton** [aelvan/Imager-Craft#160]
An idea for a feature request would be to add the ability to add some padding to the letterbox resize option. So you could include say 10px of padding that would be created around the graphic in the bg-color selected. 

Although I suppose this could be argued that this can be done with CSS.

**Comment by sm9** [comment]
+1 for this feature request. My use case is that I'm using imager to output company logos of various sizes and proportions but want them to all fit within the same white rectangle. The logos are semi-transparent PNG files. I'm using the letterbox resize option and this works well, but I'm having to add padding using CSS. The downside of the CSS padding is it means that if I want to copy the images to post on Facebook or Twitter, the images don't include the padding so don't look as good, so it means having to Photoshop them slightly each time if using on social media. My current code is below.

```{% set image = entry.logo.one() %}
        {% set transformedImage = craft.imager.transformImage(image, { width: 600, height: 400, mode: 'letterbox', letterbox: { color: '#fff', opacity: 1 }, %}
        <div class="logo-container" style="border: 1px solid #eee; padding: 20px;">
          <img src="{{ transformedImage.url }}" />
        </div>```

**Comment by aelvan** [comment]
Imager X added the [pad transform parameter](https://imager-x.spacecat.ninja/transform-parameters.html#pad-int-array).
