### ISSUE TITLE
'UrlBuilder requires at least one domain' error

### ISSUE THREAD

**Issue by romanov-sky** [aelvan/Imager-Craft#163]
Hello! Thanks for your work. Please help, I am trying to set up Imager with Imgix and GCS (and the same result with Web folder) i get this error when running code in a template (Craft 3 latest):

`UrlBuilder requires at least one domain
in /srv/app/1soul/htdocs/1soul/vendor/imgix/imgix-php/src/Imgix/UrlBuilder.php at line 23`
full error page https://screenshots.firefox.com/PVMMC7DWn3TWu5i0/www.tvorenie.co

my Imager setting:
  'imgixEnabled' => true,
  'imgixDomains' => array('tvorenie-co.imgix.net'),
  'imgixUseHttps' => true,
  'imgixSignKey' => '',
  'imgixSourceIsWebProxy' => false,
  'imgixUseCloudSourcePath' => true,
  'imgixShardStrategy' => 'cycle',
  'imgixGetExternalImageDimensions' => true,
  'imgixDefaultParams' => array('auto'=>'compress,format', 'q'=>80),

my template code:
`{% set entries = craft.entries.section('read,creation,basics').limit(1) %}
{% for entry in entries %}	
{% if entry.photo | length %}
{% for image in entry.photo %}
{% set transformedImage = craft.imager.transformImage(image, { width: 1000 }) %}
<img src="{{ transformedImage.url }}">
{% endfor %}	 
{% endif %}
{% endfor %}	`

**Comment by aelvan** [comment]
Looks like you're trying to use the imgix configuration from Imager 1.0 (craft 2) for Imager 2.0 (craft 3). Have a look at the ["What's new in Imager 2.0"](https://github.com/aelvan/Imager-Craft/wiki/What's-new-in-Imager-2.0%3F) article, specifically the section in Imgix profiles. Also see the relevant configuration docs here:

https://github.com/aelvan/Imager-Craft#imgixprofile-string

**Comment by romanov-sky** [comment]
you are absolutely right, thank you!

**Comment by j-greig** [comment]
Having the same problem, maybe the docs could be clearer.... or maybe I'm an idiot!

So do these settings go inside `return array(` in the imager.php file?
