### ISSUE TITLE
how to set focal point for one image only

### ISSUE THREAD

**Issue by romanov-sky** [aelvan/Imager-Craft#164]
Hello André! If i need to set/change a focal point to just one of the photos, not for all images),  is that  possible?

**Comment by aelvan** [comment]
Yes, you can apply the `position` transform parameter to any individual transform you're doing.

**Comment by matt-adigital** [comment]
Is there a way to get this to inherit the focal point set on the asset through the native cms functionality?

We have a news channel where the focal points for the image thumbnails on the index page are all going to be in different places so it would be perfect if the client can set the focal point through editting the image in the cp assets section and then have imager respect that value when generating the transform.

Is there a way of doing this currently and if not, could it be a feature request please?

**Comment by daltonrooney** [comment]
@matt-adigital You can get the focus point coordinates from the CMS with something like this:

```
{% if asset.hasFocalPoint %}
   {% set focalPoint = asset.getFocalPoint() %}
   {% set position = focalPoint.x * 100 ~ '% ' ~ focalPoint.y * 100 ~ '%;' %}
{% else %}
   {% set position = 'center center' %}
{% endif %}
```
And then your transform might look like this:

```
{% set transformedAsset = craft.imager.transformImage(asset, { width: 500,position: position }) %}
```

**Comment by aelvan** [comment]
@matt-adigital @daltonrooney You can also pass `asset.getFocalPoint()` directly to Imager:

`{% set transformedAsset = craft.imager.transformImage(asset, { width: 500, position: asset.getFocalPoint() }) %}`

**Comment by matt-adigital** [comment]
I recieved an error using your method @daltonrooney saying that a non numeric value was encountered but using the method described by @aelvan works perfectly! Thank you both of you.

For future reference for others attempting to do this it might be worth adding an explanation to the readme file here: https://github.com/aelvan/Imager-Craft#position-string

Cheers.

**Comment by aelvan** [comment]
Yeah, there was a typo in @daltonrooney's example, an extra semicolon in the string, I've fixed it now. 

I'll make sure to update with an example. I'm also contemplating a way of making the native focal point the default value, just haven't landed how to implement it yet.

**Comment by daltonrooney** [comment]
@aelvan Your version is much more clear than mine! Just cleaned up my image macros quite a bit... thanks for the plugin & support.

**Comment by romanov-sky** [comment]
this is cool, thank you!
