### ISSUE TITLE
Documentation link in Craft CMS backend

### ISSUE THREAD

**Issue by LauraMontgomery** [aelvan/Imager-Craft#166]
A nice easy one for you, the documentation link in the backend of Craft points to:
https://github.com/aelvan/imager/blob/craft3/README.md

And just needs updating to:
https://github.com/aelvan/Imager-Craft

**Comment by aelvan** [comment]
Thanks! This has actually been updated in the latest commit, it's just not visible yet since I haven't tagged a new version. It'll be fixed when the next version is pushed.
