### ISSUE TITLE
Setting unknown property: craft\models\AssetTransform::ratio

### ISSUE THREAD

**Issue by howells** [aelvan/Imager-Craft#167]
Using ratio like so: 

`{% set urlMobile = image.getUrl({ width: 800, ratio: 16/9 }) %}`

seems to issue the following error:

`Setting unknown property: craft\models\AssetTransform::ratio`

Any idea what's up? Everything else working as usual...

**Comment by aelvan** [comment]
Yeah, `ratio` is an Imager specific transform parameter, so you can't use that when using the native transform syntax. You'd have to use Imager directly, `{% set urlMobile = craft.imager.transformImage(image, { width: 800, ratio: 16/9 }) %}`, if you want to use `ratio`.

**Comment by howells** [comment]
@aelvan wow, sorry I impress myself with my stupidity sometimes.
