### ISSUE TITLE
Images not uploading to GCS

### ISSUE THREAD

**Issue by umkasanki** [aelvan/Imager-Craft#169]
I'm trying to connect the GCS but it does not work for me. Tell me please what I'm doing is not right?

My config file:
[imager.zip](https://github.com/aelvan/Imager-Craft/files/1952206/imager.zip)

**Comment by aelvan** [comment]
You need to put the key file somewhere on your server, and reference it with the `keyFile` config setting. Seems like you've pasted it into the config setting.

If you put your key in a folder named `keys` inside your project root, the gcs config should look something like this:

        'gcs' => [
            'keyFile' => $_SERVER['DOCUMENT_ROOT'] . '/../keys/gcs-31a21242xxxx.json',
            'bucket' => 'imagertest',
            'folder' => '',
        ]

**Comment by umkasanki** [comment]
Thanks for the quick response.
Unfortunately there was an error.
Screenshot:
![screenshot-2018-4-26 yii base errorexception](https://user-images.githubusercontent.com/496132/39322415-80655432-4992-11e8-8cc4-4336bb480981.png)

I tried to write this:
```

    public $storages = ['gcs'];
    public $storageConfig = [
        'gcs' => [
            'keyFile' => '@webroot/craft/config/gcs-key.json',
            'bucket' => 'originals-site',
            'folder' => 'transformed',
        ],
    ];`

```
The error was gone. But the GCS did not connect

**Comment by umkasanki** [comment]
Thank you very much
