### ISSUE TITLE
cURL error 6

### ISSUE THREAD

**Issue by bogdangrab** [aelvan/Imager-Craft#171]
Hi. 
I've installed the imager plugin, but I am receiving this error on the production server:
`cURL error “6” encountered while attempting to download “https://domain.com/gallery/foto_banner.jpg”. The error was: “Could not resolve host: domain.com”`
Have you stumbled upon this issue? Or do you have any ideas on how to solve this issue?

**Comment by aelvan** [comment]
Did you solve this? Sounds like a DNS issue on your server. Or maybe an SSL issue. Start with doing a `ping domain.com` on the server and work from there.
