### ISSUE TITLE
Placeholder function only supports jpg images

### ISSUE THREAD

**Issue by peirix** [aelvan/Imager-Craft#175]
Would be nice to have supports for multiple filtypes.

Workaround now, for those looking, is to transform the image first, setting the format to jpg, and then throw that formattet image in to the placeholder function. You probably want to use a transformed image anyway, to have control over how big the image used in the placehoder is.

**Comment by aelvan** [comment]
[Imager X](https://imager-x.spacecat.ninja/) adds support for also using other types of images.
