### ISSUE TITLE
Windows file paths

### ISSUE THREAD

**Issue by proimage** [aelvan/Imager-Craft#179]
I'm testing on Windows in a local XAMPP environment, and Imager is generating paths with a mix of forwards and backwards slashes, eg. `/imager\images\6172\my-image.jpg`. Browsers aren't understanding this and don't load the referenced image; manually converting the backslashes `\` to forwards slashes `/` using dev tools allows the image to be loaded.

**Comment by aelvan** [comment]
Right, I think I know the reason for that, my bad. Can you check if the image in being created correctly, ie if it exists in `/imager/images/6172/my-image.jpg`?

**Comment by proimage** [comment]
Yes, the image gets generated properly.

**Comment by aelvan** [comment]
Can you test something for me, I don't have a windows dev environment available atm. Can you switch out line 49 in the LocalTargetImageModel.php file in /vendor/aelvan/imager/src/models, with this one:

```
$this->url = ImagerHelpers::stripTrailingSlash($config->imagerUrl).FileHelper::normalizePath($source->transformPath.'/'.$this->filename, '/');
```

The only difference being the second parameter of `normalizePath` being set to `'/'`.

Let me know if that works and I'll push a fix for it shortly.

**Comment by proimage** [comment]
Yup, that seems to fix the problem! I also verified that images still get generated properly, just in case. ;)

**Comment by proimage** [comment]
Somewhat related, @aelvan: https://github.com/aelvan/craft-imager-do-spaces-driver/issues/2
