### ISSUE TITLE
An isDark or isLight function

### ISSUE THREAD

**Issue by howells** [aelvan/Imager-Craft#180]
I don't think this is available right now, or at least I can't spot it in the docs, but it would be amazing if Imager could expose an isDark and isLight function to determine the image's brightness. I'd love to automate whether a piece of overlay text should be white or black.

I use a similar function in TinyColor, which takes a hex as an input: not sure how you'd do that with images:

https://github.com/bgrins/TinyColor#islight

**Comment by aelvan** [comment]
I've added a ton of color utilities to Imager 2.1.0 that was just pushed. Check out the template variables section in the docs. 

The methods take a color value as parameters, not an image. So you'll need to get the color you want to test with from the image using something like getDominantColor. This probably gives the best result if you resize and blur the image a little bit before sampling it. Planning on making a blog post with some hints and tips if I get a chance in the near future.
