### ISSUE TITLE
Missing documentation for region setting in AWS storage config

### ISSUE THREAD

**Issue by jamealg** [aelvan/Imager-Craft#182]
What is region supposed to be set to? Is it simply the name of the region? The subdomain of the region? I'm in U.S. East (North Virginia). I tried using that exactly but my transformed assets aren't being uploaded. The subdomain I see in my uploaded assets in AWS is just `s3.`so I tried `s3` and that doesn't work either.

**Comment by dwhoban** [comment]
It is supposed to be the region from this table: https://docs.aws.amazon.com/general/latest/gr/rande.html
So for `Asia Pacific (Sydney)` I use `ap-southeast-2`

**Comment by frankharrison-wj** [comment]
Would be good to get that into the docs – too me a while to figure this out!

**Comment by aelvan** [comment]
I've added an example to the `storageConfig` doc.

**Comment by frankharrison-wj** [comment]
Great. I love this plugin!

**Comment by jamealg** [comment]
Thank you both!
