### ISSUE TITLE
Documentation for Client Supports WebP Incorrect

### ISSUE THREAD

**Issue by tcherokee** [aelvan/Imager-Craft#183]
Just noticed that the documentation for the [Client Supports WebP](https://github.com/aelvan/Imager-Craft#craftimagerclientsupportsforwebp) seems to be incorrect. It currently says `craft.imager.clientSupportsForWebp()`. However when I use that, I get an error. This seems to work though, `craft.imager.clientSupportsWebp()`, and is also in line with the code for checking if the server supports webP.

**Comment by aelvan** [comment]
Fixed. Thanks for letting me know.
