### ISSUE TITLE
Feature Request: merge in your inlining plugin for SVGs

### ISSUE THREAD

**Issue by adrienne** [aelvan/Imager-Craft#184]
It would be great if this could handle inlining SVGs, then it would be a really one-stop solution for images!

**Comment by aelvan** [comment]
Sorry, but I don't think it really belongs in Imager. In addition to using Inlin for inlining svg's, we also use it for inlining javascript and css, so it feels more relevant as a separate plugin. Also, there's Craft's built-in `svg` twig function now which can be used if you only want to deal with svgs.
