### ISSUE TITLE
Minimum stability issue upgrading 2.1.0

### ISSUE THREAD

**Issue by joomkit** [aelvan/Imager-Craft#186]
ON upgrade via composer getting this error:
 Problem 1
    - Installation request for aelvan/imager v2.1.0 -> satisfiable by aelvan/imager[v2.1.0].
    - aelvan/imager v2.1.0 requires imgix/imgix-php ^2.1.0 -> satisfiable by imgix/imgix-php[2.1.0] but these conflict with your requirements or minimum-stability.

Minimum stability flags are not set anywhere in imager or imgix or craft composer file.
Have tried adding dev flag to each but still no luck.

Any ideas on how to resolve?

**Comment by aelvan** [comment]
Is that the whole error? Sure it's not conflicting with the requirements of some other plugin? I know ImageOptimize for instance has an older requirement.

**Comment by joomkit** [comment]
It was a conflict with ImageOptimise plugin and version of imgix. Have managed uninstall image optimise and resolve now.
