### ISSUE TITLE
imager.php config formatting

### ISSUE THREAD

**Issue by marksimons** [aelvan/Imager-Craft#187]
Craft 3 + Imager

I've installed MozJpeg as per Nystudio's blog post. But it references Craft 2 and I am aware its slightly different for Craft 3. So apologies for a basic Q..

In the /config/imager.php that I have created how do I enable mozjpeg and optimizeType = runtime?

Do I simply add this and nothing else? Or will Imager know that mozjpeg is already installed?

```
'optimizerConfig' = [
    'mozjpeg' => [
        'extensions' => ['jpg'],
        'path' => '/usr/bin/mozjpeg',
        'optionString' => '-optimize -copy none',
    ]
],
'optimizeType' => 'runtime'
```

Thanks for your help

**Comment by aelvan** [comment]
Imager does not autodetect and enable anything by default, you need to configure exactly what you want it to do. 

The relevant parameters are `optimizeType`, `optimizerConfig` and `optimizers`. Looks like you've got the configuration for the first two set up correctly (assuming `/usr/bin/mozjpeg` actually exists). But you also need to indicate which optimizers you want to run with `optimizers`. Like this:

```
'optimizeType' => 'runtime'
'optimizers' => ['mozjpeg'],
'optimizerConfig' = [
    'mozjpeg' => [
        'extensions' => ['jpg'],
        'path' => '/usr/bin/mozjpeg',
        'optionString' => '-optimize -copy none',
    ]
],
```

**Comment by marksimons** [comment]
Thank you sir
