### ISSUE TITLE
Issues with getting files from S3 with non ascii codes in name

### ISSUE THREAD

**Issue by bossanova808** [aelvan/Imager-Craft#19]
I am seeing errors like the attached

but if I go to the url directly (https://images.imagescience.com.au/Brands/Hahnemuhle/Hahnem%C3%BChle_long_NEW.jpg) - it loads fine.

I am thinking that's an issue with the encoding of the name?

Error:
![curl](https://cloud.githubusercontent.com/assets/731309/13040414/d8341578-d3ff-11e5-901d-f3ee933e7f48.png)

I have tried some quick tests with url_encode and curl_escape and it's not working.

**Comment by bossanova808** [comment]
(and very sorry to be bombarding you!)

**Comment by aelvan** [comment]
Trying to find a solution for this, but non-ascii filenames being transferred between filesystems really is a b****. 

Not sure if you know, but you can set `'convertFilenamesToAscii' => true` in the Craft config to make sure you never have to deal with these issues. It's standard in all my installs. ;)

**Comment by aelvan** [comment]
Could you try replacing the /craft/plugins/imager/models/Imager_ImagePathsModel.php file with the one attached in the zip, and let me know what happends.

[Imager_ImagePathsModel.php.zip](https://github.com/aelvan/Imager-Craft/files/131331/Imager_ImagePathsModel.php.zip)

**Comment by bossanova808** [comment]
Hi Andre

Your updated file works, thanks!

That said, I am also going to engage that config item (and rename any files with unusual chars in them already!) - as I like that and it's probably the more robust solution.  

But this does work and is great for any that slip through and doubtless others will hit this over time - much appreciated!!

**Comment by aelvan** [comment]
Ok, great. I'll test it a bit more thoroughly before pushing it out in the next version.

**Comment by bossanova808** [comment]
Hi Andre

Having another issue in this same area - I use a LAMP stack at work, but have set up a WAMP stack at home.  I'm getting an http 0 status on image urls that load fine in the browser and on the LAMP stack all is working well.  However there's no non ascii in the files, so this is more of a mystery - any ideas??

![2016-03-12_10-09-08](https://cloud.githubusercontent.com/assets/731309/13718085/af6580e2-e83a-11e5-9e8e-db07ff8448d8.png)

**Comment by bossanova808** [comment]
Ok I puzzled this one out - I'm using a self signed cert on the WAMP setup, so I need to add

CURLOPT_SSL_VERIFYPEER => false,

To the curlopts.  

Any chance you want to add this as a setting maybe?  Surprised that no one has sun in to this as I would have thought self signed certs were fairly common in dev environments?

Also you might want to append `curl_error($ch)` to where you throw the exception so cURL errors can be seen perhaps?
