### ISSUE TITLE
Make second argument of craft.imager.transformImage() optional

### ISSUE THREAD

**Issue by benface** [aelvan/Imager-Craft#191]
In this function:

> craft.imager.transformImage(image, transform [, transformDefaults=null, configOverrides=null])

...the `transform` argument should be optional, and it should be the equivalent of passing an empty object, which we may want to do if we just want to use the default Imgix profile's `defaultParams`.

**Comment by jz-wilson** [comment]
@benface, I found a workaround for this if you retrieve your assets height and width from Craft
`{% set image = block.image.one() %}
{% set image_height = image.height %}
{% set image_width = image.width %}`

And pass them as your transform sizes you can keep them the same without having to specify each file every time. 

Hopefully that works for you! Worked for me!

**Comment by benface** [comment]
@jz-wilson Hmm, I don't think we're talking about the same thing. In my case, the "workaround" is simply to pass an empty object:

```
craft.imager.transformImage(entry.imageField.first(), {})
```

This is because I have this in my `imager.php` config (notice I'm using imgix with `defaultParams`):

```
    'transformer' => 'imgix',
    'imgixProfile' => 'default',
    'imgixConfig' => [
        'default' => [
            'domains' => ['myapp.imgix.net'],
            'useHttps' => true,
            'signKey' => getenv('IMGIX_SIGN_KEY'),
            'sourceIsWebProxy' => false,
            'useCloudSourcePath' => true,
            'shardStrategy' => 'cycle',
            'getExternalImageDimensions' => false,
            'defaultParams' => ['auto' => 'compress,format'],
        ],
    ],
```

No need to pass image dimensions as they are part of the asset objet passed to `craft.imager.transformImage`. Maybe you're experiencing a different issue?

**Comment by aelvan** [comment]
This wont be changed. Incidentally the Imgix transformer could do something meaningful when not passing in any transform parameters (because of `defaultParams`), but that's not really the case with the Craft transformer (or any other ones that might get added in the future).

**Comment by benface** [comment]
Makes sense, I understand. Thank you for considering it. :)
