### ISSUE TITLE
Does This Have an Opacity Option?

### ISSUE THREAD

**Issue by kgrote** [aelvan/Imager-Craft#192]
Does this plugin have an option to adjust the opacity of an image with transparency? I see the `colorBlend` option kind of has this except you have to specify a solid color to mix with rather than a pure transparency. Thanks!

**Comment by kgrote** [comment]
My client uses their CMS to build HTML emails for copy/pasting into their email marketing program. Since many email clients don't support modern CSS I use an opacity filter (CE Image in EE currently) to generate a transparent image.

**Comment by aelvan** [comment]
Myeah, I guess that depends on what you compare it with. The color blend effect doesn't really try to emulate any specific color blend, it's just... _a_ color blend. ;)

**Comment by kgrote** [comment]
Fair enough :D I ended up using the watermark feature to get the look I was going for.

**Comment by kgrote** [comment]
Heyo,

I just ran into another HTML Email-specific need: rounded corners. Since a lot of email clients don't support `border-radius` I need to cut the image corners manually.

Just a feature request, no desperate need for this to be resolved soon. Thanks!

**Comment by warrebuysse** [comment]
@kgrote If the amount of transformations is limited, maybe use a service like Cloudinary to pass through your email images. Cloudinary can easily change opacity (and quite a lot of other things), and it's (up to a certain point) free. We're using it for some of our clients for the exact same reason.

**Comment by aelvan** [comment]
Imager X adds an [opacity effect](https://imager-x.spacecat.ninja/effects.html#opacity-float-array).
