### ISSUE TITLE
Settings in imager.php are being ignored

### ISSUE THREAD

**Issue by klick** [aelvan/Imager-Craft#194]
Hi. It seems that all path and useFilenamePattern settings are getting ignored, no matter what I do. Did configs somehow changed since 2 or am I missing something else?

My config:

```
<?php
return array(
        '*' => array(
		'jpegoptimEnabled' => true,
		'optipngEnabled' => true,
		'jpegQuality' => 80,
		'useFilenamePattern' => false,
		'filenamePattern' => '{basename}_{transformString|hash}.{extension}'
	),
	'www.site.de' => array(
		'imagerSystemPath' => '@webroot/build/images/',
		'imagerUrl' => 'https://static.site.de/',
		'interlace' => true
       ),
       'site.localhost' => array(
                'curlOptions' => array(
                        CURLOPT_SSL_VERIFYPEER => false,
                        CURLOPT_SSLVERSION => 1,
                        CURLOPT_SSL_CIPHER_LIST => 'TLSv1',
		),
		'imagerSystemPath' => '@webroot/image/',
                'imagerUrl' => 'https://site.localhost/imager/'
       )
);
```

**Comment by aelvan** [comment]
Are you using the Craft 2 or Craft 3 version? Your config file is a mix of how things use to work in the Craft 2 version, and some that were introduced in the Craft 3 version (namely `useFilenamePattern` and `filenamePattern`).

**Comment by aelvan** [comment]
Ok, for Craft 3, the `filenamePattern` should work. `useFilenamePattern` has to be set to `true` though, it's `false` in your pasted config. But you tried with `true`? What's the filename of the transforms that're generated?

For an overview of what changed, you can read [this article](https://github.com/aelvan/Imager-Craft/wiki/What's-new-in-Imager-2.0%3F). In terms of your config, have a look at optimizers, jpegoptim and optipng isn't enabled and configured the way they used to. I also thought `curlOptions` was wrong, but that's just me forgetting how my own plugin works... ;)

**Comment by klick** [comment]
Thanks aelvan, will look into all of this.

> but that's just me forgetting how my own plugin works... ;)

I know that feeling very well. :)
