### ISSUE TITLE
Gif placeholder not working

### ISSUE THREAD

**Issue by Moorst** [aelvan/Imager-Craft#195]
When I try and use the 'gif' type on a placeholder, it's not outputting anything;

```
{% set image = entry.featuredImage.one %}
{% set transformedImages = craft.imager.transformImage(image,
    [
        { width: 2048 },
        { width: 1600 },
        { width: 1200 },
        { width: 800 },
        { width: 400 } 
]) %}
<img sizes="100vw" src="{{ craft.imager.placeholder({ width: 3, height: 2, type: 'gif' }) }}" 
srcset="{{ craft.imager.srcset(transformedImages) }}" alt="{{ image.title }}">
```

I've tried defining a colour but still not luck. I'm also using imgix as the transformer, not sure if that would affect this functionality?

**Comment by tyssen** [comment]
I'm getting the same on v2.1.2. As soon as I add `type: 'gif'` as a parameter, there's no output.

**Comment by aelvan** [comment]
Encountered this oldie. Tracked it down to having to do with imageDriver being set to `'auto'` in Craft's general config. Fixed for the next release.
