### ISSUE TITLE
Debug webp generation?

### ISSUE THREAD

**Issue by chromadesign** [aelvan/Imager-Craft#197]
Hi,

I'd like Imager to generate webp images but somehow it doesn't seem to seem to pick up that webp is installed on my server. I checked the packages and they are installed, I can also generate webp images via ssh. Is there any way to debug what the problem is?

Thanks,
Manuela

**Comment by aelvan** [comment]
Hi,

How have you configured Imager to use webp? Based on what you write I assume you're trying to used it through the cwebp cli tool? Make sure that is enabled, and that the path is correct. If it can't find cwebp in the provided path, or if Imagick or GD doesn't support it and you're trying to use it through the image driver directly, you should see an error message in your console, something like "This version of {imageDriver} does not support the webp format...."

**Comment by terryupton** [comment]
I have a very similar issue.
I am getting the following error:
`$msg = Craft::t('imager', 'This version of {imageDriver} does not support the webp format. You should use “craft.imager.serverSupportsWebp” in your templates to test for it.', ['imageDriver' => ImagerService::$imageDriver === 'gd`

However, everything is setup and configured and I have the exact same setup on another Craft install that does work. Both work on the same homestead version, use the same PHP version and the same Imagick versions.

Here is some of my config:
```
<?php

return array(
    '*' => array(
        // ------------------------------------------------------------
        // Environment: ALL
        // ------------------------------------------------------------
        // 'fillAttribute' => 'width',
        // 'fillInterval' => '200',


        'imagerSystemPath' => '@webroot/transforms/',
        'imagerUrl' => '@web/transforms/',
//      'transformer' => 'craft',

//        'cacheEnabled' => true,
//        'cacheDuration' => 31536000, // 1 year
//        'cacheDurationRemoteFiles' => 31536000, // 1 year


//      'hashPath' => true

        'jpegQuality' => 80,
        'pngCompressionLevel' => 0,
        'useCwebp' => true,
//        'path' => '/usr/bin/cwebp',


        'pngCompressionLevel' => 0,
        'allowUpscale' => false,
        'smartResizeEnabled' => false,
        'removeMetadata' => true,
        // 'filenamePattern' => '{basename}-{transformString|shorthash}.{extension}',
//        'filenamePattern' => '{fullname}.{extension}',
        'fillTransforms' => true,
        'fillInterval' => '200',

        'interlace' => 'line',

        'optimizers' => ['mozjpeg', 'pngquant', 'optipng'],

        'optimizerConfig' => [
            'mozjpeg' => [
                'extensions' => ['jpg'],
                'path' => '/usr/bin/mozjpeg',
                'optionString' => '-optimize -copy none',
            ],
            'optipng' => [
                'extensions' => ['png'],
                'path' => '/usr/bin/optipng',
                'optionString' => '-o2 -strip all',
            ],
            'pngquant' => [
                'extensions' => ['png'],
                'path' => '/usr/bin/pngquant',
                'optionString' => '--strip --skip-if-larger',
            ],
        ]
    )
);
```
PHP version | 7.2.14
Image driver & version | Imagick 3.4.3 (ImageMagick 6.9.7-4)
Craft edition & version | Craft Solo 3.1.11
Imager | v2.1.4
WebP Support | enabled
imagick module version | 3.4.3

**Comment by aelvan** [comment]
There was an issue with spaces in paths making cwebp fail, which was Terry's issue. Closing this due to lack of response on the original issue.
