### ISSUE TITLE
Use w/ Element API?

### ISSUE THREAD

**Issue by movingobjects** [aelvan/Imager-Craft#198]
Are there any examples showing Imager used with [Element API](https://github.com/craftcms/element-api)?

I want to use Imager to transform images and use them in a JSON feed w/ Element API, but can't figure out how to correctly call the `transformImage` function within `element-api.php`.

**Comment by movingobjects** [comment]
Here's what I came up with that seems to be working, but not sure if this is the correct way to access the plugin.

```
'transformer' => function(Entry $entry) {

    $imager = new aelvan\imager\services\ImagerService();
    $image  = $entry->image->one();

    $resizedImage = $imager->transformImage($image, [
        'width' => 100
    ]);

    return [
        'image' => $resizedImage->url
    ];
},

```

**Comment by aelvan** [comment]
Guess you could do it that way, but I think the Craft-way would be to access the service through the static $plugin variable on the Plugin's main class. Something this:

```
Imager::$plugin->imager->transformImage(image, ['width' => 100]);
```

(where `Imager` is `aelvan\imager\Imager`, you could `use` that, or add the namespace to the class). 

I _think_ the result will be the same though, all initialization should have been done anyway, but..

**Comment by movingobjects** [comment]
That's exactly what I was looking for. Thanks @aelvan!

**Comment by katiasmet** [comment]
Hi @aelvan Is it also possible to access the `serverSupportsWebp` and `clientSupportsWebp` functionality ? 

It says the following : 
```
"Calling unknown method: aelvan\imager\services\ImagerService::serverSupportsWebp()"
}
```

Thx!

**Comment by aelvan** [comment]
Yeah, the service method is just named differently than the template variable, and it's a static. Try: `ImagerService::hasSupportForWebP();`

**Comment by katiasmet** [comment]
Nice it works 👍
Thanks for the quick response! 

For others: 
You can import this like so: use aelvan\imager\services\ImagerService 
You can use following function for client support: 
```

**Comment by Saboteur777** [comment]
(For future reference)

In case you want to use a combination of Element API + Imager + Imager Pretransform (without defining already defined transform again), you can do that this way: 

```
$imager = new ImagerService();
$transforms = ImagerPretransform::$plugin->getSettings()->transforms;

$images = $imager->transformImage($image, $transforms);
```
