### ISSUE TITLE
Discussion: Fallback image in devMode

### ISSUE THREAD

**Issue by urbantrout** [aelvan/Imager-Craft#200]
Just a thought:

Wouldn't it be nice to just output a placeholder image instead of throwing an exception when there is no image found in dev mode. This would make life easier if there a assets missing when working with a multi-server setup (development/staging/production)

**Comment by davidhellmann** [comment]
Good Idea!

**Comment by aelvan** [comment]
[Imager X](https://imager-x.spacecat.ninja/) has support for both fallbackImage (for when image transforms fail) and mockImage (for completely replacing all images sent to Imager).
