### ISSUE TITLE
Disable gif transforms

### ISSUE THREAD

**Issue by Moorst** [aelvan/Imager-Craft#204]
Is it possible to disable gifs being transformed? I've set the Craft setting "transformGifs" to false but Imager isn't respecting this.

**Comment by aelvan** [comment]
Assuming that you actually want to transform gifs, just not animated gifs? You can use `craft.imager.isAnimated` in your templates to check if it's animated, and do a fallback solution if it is.

**Comment by Moorst** [comment]
Ok thanks - yes I was referring to animated gifs should have been clearer. 

I suppose it would be useful to have this as a global option rather than having to add this check everywhere I'm performing transforms.

**Comment by aelvan** [comment]
This wont be added as a config setting. Please note that you can use the [frames transform parameter](https://github.com/aelvan/Imager-Craft#frames-string) to only transform one frame, if what you want to achieve is to not have to transform the whole animated gif. If you want to skip transforming the animated gif altogether, I think this belongs in the template using the `craft.imager.isAnimated` template variable.
