### ISSUE TITLE
SubFolder Setting when Using Imager with Imgix

### ISSUE THREAD

**Issue by Osze** [aelvan/Imager-Craft#206]
For using Imager with Imgix. 

Is it possible to add a setting for a sub folder in the imgix config profile for web folder setup?

I'm using one source / website in IMGIX and would like to have different imgix-config-profile / asset volume in Craft. 

now I'm using the domains setting like:
'domains' => ['domain.imgix.net/assets/local'],

but would be better for validation if this would work:

'domains' => ['domain.imgix.net'],
'subFolder' => ['/assets/local'],

**Comment by aelvan** [comment]
This was solved with release v2.1.8, which adds the `addPath` setting for Imgix configs (check the example in the docs).
