### ISSUE TITLE
Add support for fingerprinting with imgix

### ISSUE THREAD

**Issue by mijewe** [aelvan/Imager-Craft#207]
When using Imgix, is there currently a way to fingerprint images so that they're cache-busted automatically as per https://docs.imgix.com/best-practices/fingerprinting-images-improve-page-load-speed ?

When updating an image (either replacing it, or doing an in-CMS crop) I need to go and manually purge the image from imgix, but it would be good if the image could be fingerprinted to avoid the need for this.

Cheers.

**Comment by aelvan** [comment]
Automatic purging through Imgix' API has been implemented in 2.1.2.
