### ISSUE TITLE
Feature requuest: add support for Craph QL

### ISSUE THREAD

**Issue by j2is** [aelvan/Imager-Craft#209]
I've been playing around with the Craph Ql plugin, any thoughts about adding Imager support?

**Comment by aelvan** [comment]
As far as I can tell, this is something that Mark has to build in support for in CraftQL. It might be that you can use imager by enabling the `useForNativeTransforms` config setting, but that depends on how transforms were implemented in CraftQL.

**Comment by j2is** [comment]
Thanks, I commissioned Mark to do this since opening this issue, it's now in the `imager` branch [https://github.com/markhuot/craftql/tree/imager](url)
