### ISSUE TITLE
How to not stretch an image if the set transform width exceeds its base width?

### ISSUE THREAD

**Issue by Osiruss** [aelvan/Imager-Craft#215]
More of a question. I have a base setup for transforms which maxes out at 1200px width and travels to said max in various intervals with srcset. If say I have an image that is only 300px wide, how do I set up imager so that it checks if the image is above (or at) the transform width and transforms only if that is the case? At the moment I've got smaller images being transformed to larger sizes resulting in blurry content. I'm sure there is a setting somewhere for this but I can't for the life of me find it.

Thank-you

**Comment by aelvan** [comment]
You can set the config setting `allowUpscale` to `false` to keep images from upsizing.
