### ISSUE TITLE
Feature request: use empty files locally to record transform done

### ISSUE THREAD

**Issue by moldedjelly** [aelvan/Imager-Craft#218]
I'm using S3 to store my images, and CDN to deliver so I have the imagerUrl set to "https://XXXXXX.cloudfront.net/imager/". As far as I can tell, after a transform is done and saved up to S3, subsequent loads of a page with transform requests, actually check if the cache of the remote file is stored locally - more as a way to detect if the transform has been done. This storage locally seems a bit of wasted local storage space since the image is loaded from the CDN URL... I'm wandering if it would make sense to add a line (controlled by a config setting perhaps) after line 313 in CraftTransformer.php which actually overwrites the local file with an empty file so that it acts as a record that the transform has been done. Would this update make sense, or am I not seeing any ramifications?

**Comment by moldedjelly** [comment]
I forked a version and applied changes to 2 files to get this functionality working in case anyone needs it :) Keeps local storage nice and lean while still using the file system to record whether transforms have been done (avoiding the database).

**Comment by aelvan** [comment]
Happy that it works for you. But this would break for instance if using post-optimizers, so it's a bit more complicated. I'm thinking about other solutions for not having to use disk-space for the cache, for the next major version.
