### ISSUE TITLE
Clearing imager cache deletes ALL assets

### ISSUE THREAD

**Issue by christopherdowson-contrast** [aelvan/Imager-Craft#224]
Using the clear cache function in utilities consistently deletes ALL of my assets folders.

Not just the cache files and folders - EVERYTHING.

![image](https://user-images.githubusercontent.com/46570789/53497651-8f009500-3a9c-11e9-8ccf-2061560878d7.png)

**Comment by aelvan** [comment]
Sounds like you maybe configured the imagerSystemPath to be the same folder as your asset folder?

**Comment by christopherdowson-contrast** [comment]
That's a definite possibility - I'll check the config.
