### ISSUE TITLE
Dependency google/protobuf fails to install

### ISSUE THREAD

**Issue by drball** [aelvan/Imager-Craft#225]
Hi, I can't install this right now because a required dependency (google/protobuf) can't be found.

**Comment by aelvan** [comment]
Still works fine for me. What's the error you're seeing?

**Comment by drball** [comment]
Hi again, I've done another build today and have had the same problem. I've been doing this in the meantime, and not had a problem. Here's the error:

`  - Installing google/protobuf (v3.6.1): Downloading (failed)    Failed to download google/protobuf from dist: The "https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/48cb18e5c419ddd23d9badcfe4e9df7bde1979b2" file could not be downloaded (HTTP/1.1 302 Found)`

Screenshot (apologies for PHPStorm's ghastly console styles):
![screen shot 2019-03-06 at 12 26 03](https://user-images.githubusercontent.com/5682340/53881259-202abb00-400b-11e9-8f9a-36e9f19e4b46.png)

**Comment by drball** [comment]
Okay so I have more information on this, and have got it working. 
I encountered the problem after I added plugin ttempleton/craft-nocache 
I have noticed that my composer-lock file is now different. The source url for google/protobuf had changed from: 
https://github.com/google/protobuf.git 
to:
https://github.com/protocolbuffers/protobuf-php.git

and the dist url had changed from:
https://api.github.com/repos/google/protobuf/zipball/48cb18e5c419ddd23d9badcfe4e9df7bde1979b2
to:
https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/48cb18e5c419ddd23d9badcfe4e9df7bde1979b2

I reverted these 2 lines (I know it's not good to edit composer.lock but what else am I to do?) and it now downloads that dependency and builds fine.

**Comment by aelvan** [comment]
Have experienced the same thing now, but it seems to be an issue with the package. Seems like some package servers have an error in the package. Removing vendor, running `composer clear-cache`, and re-installing fixed the issue for me. 

I suspect this is a temporary issue that is outside of my control, but I'll leave this open for now, so people can report if they see this continuing to happen.
