### ISSUE TITLE
Transformed image model 's getWidth() and getHeight() return 0 when no width/height passed to transform

### ISSUE THREAD

**Issue by benface** [aelvan/Imager-Craft#228]
I'm using Imgix to simply compress images while keeping their original dimensions, like this:

```
craft.imager.transformImage(originalImage, { auto: 'compress,format' })
```

The issue is that the transformed image model returned by that function call has no dimensions (`getWidth()` and `getHeight()` return 0).

Whereas if I simply do this:

```
craft.imager.transformImage(originalImage, { width: originalImage.getWidth() })
```

Then the resulting model's `getWidth()` and `getHeight()` return the correct dimensions.

Thank you :)

**Comment by aelvan** [comment]
This was a bug, has been fixed for the next release which will be out shortly. Thanks for reporting!
