### ISSUE TITLE
Purge proxy sources

### ISSUE THREAD

**Issue by jorenvanhee** [aelvan/Imager-Craft#232]
Would you accept a pull request that adds purging for proxy sources? If so, would it be ok if I used fingerprinting (#207), or would you rather have it work via the imgix purge endpoint (https://api.imgix.com/v2/image/purger).

**Comment by aelvan** [comment]
Hi,

Not sure I understand the use case. Automatic purging was added in 2.1.2, but is the problem that you're using a web proxy source, and it's currently not working with that?

**Comment by jorenvanhee** [comment]
Yep that's right. I solved it yesterday by writing a plugin specifically for the fingerprinting of assets. It looked like something that was better off in a separate plugin. ~~I can put it here if it's published?~~ https://github.com/glue-agency/craft-fingerprint-assets
