### ISSUE TITLE
Clear Caches does not clear transforms if setting different imagerSystemPath

### ISSUE THREAD

**Issue by hmoldo** [aelvan/Imager-Craft#236]
In my config/imager.php i set:
'imagerSystemPath' => '@webroot/img/'

Working ok for creating transforms, however with clear caches the transforms are still there.
The problem is that the alias @webroot is not translated to its value.

I fix it by getting the path like:
$path = Yii::getAlias(self::$plugin->getSettings()->imagerSystemPath);

**Comment by aelvan** [comment]
Right, I was accessing the `imagerSystemPath` setting wrong in register cache options event. There will be a fix for this in the next release.
