### ISSUE TITLE
Transformed image model's height is wrong when width and height are used

### ISSUE THREAD

**Issue by benface** [aelvan/Imager-Craft#238]
I have an `image` that is 2000 x 1500 pixels. I am transforming it to 1920 x 1080 like this:

```
{% set transformedImage = craft.imager.transformImage(image, {
    width: 1920,
    height: 1080,
}) %}
```

After this, `transformedImage.width` correctly returns `1920`, but `transformedImage.height` returns... `3413` ??? Strangely, if I omit the `height` param, it correctly returns `1440` (keeping the same ratio as the original image).

Here's my full Imager config:
```
return [
    'transformer' => 'imgix',
    'jpegQuality' => 80,
    'allowUpscale' => false,
    'useForNativeTransforms' => true,
    'useForCpThumbs' => true,
    'imgixProfile' => 'default',
    'imgixApiKey' => getenv('IMGIX_API_KEY'),
    'imgixConfig' => [
        'default' => [
            'domains' => ['mysite.imgix.net'],
            'signKey' => getenv('IMGIX_SIGN_KEY'),
            'shardStrategy' => 'crc',
            'getExternalImageDimensions' => false,
            'defaultParams' => ['auto' => 'compress,format'],
        ],
    ],
];
```

Thank you very much :)

**Comment by aelvan** [comment]
What type of image are you trying to transform, is it a craft Asset or external image?

**Comment by benface** [comment]
@aelvan Sorry, it’s a Craft asset (stored in a S3 volume).

**Comment by aelvan** [comment]
I've tested and are not able to recreate. Is it just this one image that gives the wrong result, or can you recreate this with all images?

**Comment by benface** [comment]
@aelvan Huh. It's not just one image, but it's also not all my images... I was able to find a pattern: it only occurs when the original image's aspect ratio is lower than the transform's aspect ratio. So I'm able to reproduce it with a 2000 x 1500 image (1.333 aspect ratio) and a 1920 x 1080 transform (1.777 aspect ratio) because 1.333 < 1.777, but not on a 2000 x 1000 image with the same transform because 2 > 1.777.

**Comment by benface** [comment]
Also interesting: when it occurs, it's like the aspect ratio is reversed. In my original example, I got a height of 3413 for a width of 1920, and if you flip them it gives the correct ratio: 3413 / 1920 = 1.777 (same as 1920 / 1080).

**Comment by benface** [comment]
Hey @aelvan, I was able to reproduce this with a blank 2000 x 1500 JPEG image, but only with the `imgix` transformer (with the `craft` transformer it works as expected). Here's a template you can use to reproduce the issue:

```
{% set image = craft.assets.filename('2000x1500.jpg').one() %}
Original Width: {{ image.width }}<br>
Original Height: {{ image.height }}<br>
<br>

{% set transformedImage = craft.imager.transformImage(image, {
    width: 1920,
    height: 1080,
}) %}
Transformed Width: {{ transformedImage.width }}<br>
Transformed Height: {{ transformedImage.height }}<br>
<br>
```

Expected output:
```
Original Width: 1920
Original Height: 1080

Transformed Width: 1920
Transformed Height: 1080
```

Actual output:
```
Original Width: 2000
Original Height: 1500

Transformed Width: 1920
Transformed Height: 3413
```

Thank you!

**Comment by benface** [comment]
Oh, new information! I can only reproduce with `allowUpscale` set to `false`.

**Comment by aelvan** [comment]
This has been fixed for the next release.
