### ISSUE TITLE
Dependency tinify/tinify requires libcurl >=7.20.0

### ISSUE THREAD

**Issue by cscomfort** [aelvan/Imager-Craft#239]
It looks like this was addressed in 2.0.1.2, but I'm running into a tinify, libcurl dependency error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tinify/tinify 1.5.2 -> satisfiable by tinify/tinify[1.5.2].
    - tinify/tinify 1.5.2 requires lib-curl >=7.20.0 -> the requested linked library curl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
  Problem 2
    - tinify/tinify 1.5.2 requires lib-curl >=7.20.0 -> the requested linked library curl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - aelvan/imager v2.1.10 requires tinify/tinify >=1.1.1 -> satisfiable by tinify/tinify[1.5.2].
    - Installation request for aelvan/imager v2.1.10 -> satisfiable by aelvan/imager[v2.1.10].
```

**Comment by aelvan** [comment]
I think there must be some other plugin, or your main composer.json file, that requires a newer version of tinify/tinify that has the lib-curl requirement. As the error message correctly states, Imager requires only tinify/tinify >=1.1.1 (1.1.1 being the last version without the lib-curl requirement), but composer has determined that you need 1.5.2.

Maybe you've installed https://packagist.org/packages/alexk/tinify which requires tinify/tinify ^1.5? Or maybe required https://packagist.org/packages/cinghie/yii2-tinify which requires tinify/tinify ^1.5.2?

**Comment by cscomfort** [comment]
Yep, I totally missed that. Thanks for taking the time to reply. Cheers.

**Comment by cscomfort** [comment]
Hi @aelvan,

Coming back to this issue after working around it in some other projects by forcing the `--ignore-platform-reqs` flag with composer.

However, after some testing on a new Craft 3 project, I'm running into some dependency discrepancies between my local environment (latest version of Laravel Homestead) and my server environment.

In my local environment when I run `composer create-project craftcms/craft`, followed by `composer require aelvan/imager`, tinify 1.5.2 gets installed:
```
...
  - Installing tinify/tinify (1.5.2): Loading from cache
...
```
However, in my server environment , I do see tinify 1.1.1 getting installed:
```
...
  - Installing tinify/tinify (1.1.1): Loading from cache
...
```

This may come down to a general misunderstanding on my part of how Composer handles dependencies. Would it be the case that Composer would elect to install tinify 1.5.2 if it determined that an appropriate version lib-curl is present on the system -- or should it always max out at version 1.1.1? If it's the former, I can see how starting my project locally (where lib-curl is available) would result on a `composer.lock` file that required tinify 1.5.2 and then, in turn, cause the issue when deploying to my server environment where lib-curl is not available.

If you have a moment, can you please help clarify the expected behavior in this case?

Cheers!

**Comment by cscomfort** [comment]
I just sorted this out after revisiting the Composer documentation, and now have my composer.json configured to match my server environment:

```
"config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0",
      "lib-curl": "7.19.7"
    }
  }
```

Sorry for the confusion on my part.

**Comment by bymayo** [comment]
I also had this issue, and it seemed to crop up after changing from Imager to Imager X.

Even removing the `composer.lock` and `vendor` folders, and reinstalling (Without cache) still didn't resolve the issue.

Adding `--ignore-platform-reqs` did fix the issue, but it scares me a little!
