### ISSUE TITLE
Thumbnails not refreshed when using `useForCpThumbs` due to browser (and Imgix) caching the image

### ISSUE THREAD

**Issue by benface** [aelvan/Imager-Craft#242]
Craft's default behaviour when generating CP thumbnails is to add the asset's last modified timestamp to the URL, so that when you replace an asset (or edit it with the image editor), the thumbnail refreshes, busting the browser's cache. But Imager doesn't do that, so the thumbnail refreshes but with the exact same URL, and the browser loads the outdated cached thumbnail.

That would be easily fixed when using the `craft` transformer; I think you would only have to replace line 224 of `src/Imager.php` from

```
$event->url = $transformedImage->url;
```

to

```
$event->url = $transformedImage->url . (strpos($transformedImage->url, '?') === false ? '?' : '&') . 'v=' . $event->asset->dateModified->getTimestamp();
```

But with the `imgix` transformer, it wouldn't work for two reasons:

1. Imgix caches images remotely, so even though they are purged on replace, it doesn't take effect quickly enough for the freshly updated image to be available when the thumbnail refreshes;
2. Not always the case, but when Imgix URLs are signed with a `signKey`, adding anything to the URL breaks the signature.

If Imgix accepted some kind of "version" parameter for cache busting (both server-side and client-side) this would be pretty easy to fix, but it doesn't seem to have anything like that, so I imagine it's tricky.

**Comment by aelvan** [comment]
As we talked about on Discord, this is not really possible to fix, given how Imgix an Craft work. Only solution would be to rename image on save, which is something that could be done in a separate plugin, doesn't really fit into Imager.

**Comment by benface** [comment]
@aelvan Thank you for your time discussing this. I understand it's not possible to fix it when using Imgix, but maybe when using the `craft` transformer it could add the asset's last modified timestamp to the URL like Craft does? I don't actually care since I won't be using `useForCpThumbs` without Imgix, but just a suggestion...
