### ISSUE TITLE
Imager can’t manipulate remote images stored as variables

### ISSUE THREAD

**Issue by onebrightlight** [aelvan/Imager-Craft#25]
I have a client project that is trying to grab various YouTube videos from their channel. Most have a high res thumbnail, but a few do not. I was attempting to find a middle ground by using the medium size thumbnail from YouTube and crop them, but it appears that a remote file that is stored as a variable is inaccessible to the plugin:

```
{% set externalImage = video.video_mediumres %}

{% set transformedImage = craft.imager.transformImage(externalImage, {
    width: 480,
    height: 270,
    mode: 'crop' }) %}

<a href="{{ entry.youtubeUrl }}" class="video-link"><div class="videoThumbnail"><img src="{{ transformedImage.url }}"></div></a>
```

This results in this error:
>**Internal Server Error**
>An unknown image object was used.

However, using the value that’s stored in `video.video_mediumres`, which is `https://i.ytimg.com/vi/axBJlbq3m4o/hqdefault.jpg`, instead of actually using `video.video_mediumres` causes the plugin to function as expected.

Is there any way to manipulate these remote images?

**Comment by aelvan** [comment]
What kind of object is `externalImage`? If you do `{{ dump(externalImage) }}`, what does it say? Is it a string or some kind of other object?

**Comment by onebrightlight** [comment]
Ah, it’s indeed “some kind of other object.”

```
object(SimpleXMLElement)[655]
  public 0 => string 'https://i.ytimg.com/vi/axBJlbq3m4o/hqdefault.jpg' (length=48)
```

**Comment by aelvan** [comment]
Right, and Imager just takes AssetFileModels and strings. Think you can "cast" it to string with something like `{{ externalImage ~ '' }}` or maybe `{{ externalImage | t }}`. Twig is a bit stupid in cases like this..

**Comment by onebrightlight** [comment]
That did it! Thanks for the explanation.
