### ISSUE TITLE
s3 setup - after craft upgrade to 3

### ISSUE THREAD

**Issue by billymedia** [aelvan/Imager-Craft#250]
Am i right in saying that imager scales and uploads resized images to amazon s3, using the options set in the imager.php config file? Images are being resized to the local imager folder, but the s3 one is empty.  The site can upload to AS3 ok.  What am i doing wrong?

Here is my config:

```'addVolumeToPath' => true,
    'cacheEnabled' => true,
    'imagerSystemPath' => '@webroot/imager/',
    'imagerUrl' => 'https://BLAH.s3.amazonaws.com/imager',
    'storages' => ['aws'],
    'storageConfig' => [
      'aws'  => [
        'accessKey' => 'BLAH',
        'secretAccessKey' => 'BLAH',
        'region' => 'eu-east-1',
        'bucket' => 'BLAH',
        'folder' => 'imager',
        'requestHeaders' => array(),
        'storageType' => 'standard',
      ]
    ]

**Comment by billymedia** [comment]
Investigating the log files and found errors like this:

```2019-06-06 03:09:28 [-][1][d37c3b5e43b91b63fcfb482b04c057e4][error][aelvan\imager\externalstorage\AwsStorage::upload] An error occured while uploading to Amazon S3: Error executing "PutObject" on "https://BLAH.s3.eu-east-1.amazonaws.com/imager/team/6171/testimage_3528d8f03267e09edcc0a2e088a20b9c.jpg"; AWS HTTP error: cURL error 6: Could not resolve host: BLAH.s3.eu-east-1.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)```

I have the correct bucket, and the correct region (which is US East N. Virigina, us-east-1).

Im at a loss as to how to resolve this, any help would be appreciated.

**Comment by aelvan** [comment]
Your region says **eu**-east-1, not us-east-1?

**Comment by billymedia** [comment]
Im such an idiot!!!! thanks!
