### ISSUE TITLE
Imager breaking Animated GIF

### ISSUE THREAD

**Issue by adamesSAS** [aelvan/Imager-Craft#251]
We've used Imager on several of our sites and have not encountered an issue when it comes to animated GIFs, however when trying to use it for one of our sites it breaks our animated GIFs. We tried disabling Imagick, to no avail, and the only solution that worked for us was to use an if statement to wrap the images with and then call it without an Imager transformation.

```
{% if image.getExtension() != "svg" or craft.imager.isAnimated(image) != true %}
<img {{ lazyAttr }}srcset="{{ craft.imager.transformImage( image, { width: 400, height: 400, mode: 'fit' } ).url }} 400w, {{ craft.imager.transformImage( image, { width: 600, height: 600, mode: 'fit' } ).url }} 600w, {{ craft.imager.transformImage( image, { width: 800, height: 800, mode: 'fit' } ).url }} 800w" alt="{{ image.title }}" class="{{ lazyClass }}" >
{% else %}
<img {{ lazyAttr }}src="{{ image.getUrl() }}" alt="{{ image.title }}" class="{{ lazyClass }}">
{% endif %}
``` 

The GIFs themselves are not huge in size but do have a lot of frames. Is there a frame limit to Imager handling the processing of GIFs? Another thought on this is the images are hosted on Google storage instead of in the Craft assets folder. Could it being an external reference have anything to do with it?

FYI we are using v2.1.10.

**Comment by sk8stevieuk** [comment]
I'm having the same issues when using animated GIFs. All other file types seem to work, a fix would be great.

**Comment by aelvan** [comment]
I need some more information about what "breaks" means. Are you seeing any error messages, or are the transforms just timing out/running out of memory? 

Transforming an animated gif basically means to transforms each of the frames individually, as if they were separate images, and then saving the resulting gif. So if there's 100 frames, that means it's the equivalent of transforming 100 images. For each transform. There's no fix for that, that's just a limitation of using PHP/a webserver to transform images.
