### ISSUE TITLE
Feature Request: Use `{transformString}` as a path?

### ISSUE THREAD

**Issue by proimage** [aelvan/Imager-Craft#252]
I've come to appreciate the `{transformString}`-named subfolders that Craft's native Image Transform process generates (eg `/images/_1280x800_crop_center-center_none/image_filename.jpg`). It clutters up the "root" image folder less, and kinda groups things together.

It seems like it would be fairly straightforward to implement something similar in Imager. Something as simple as parsing for forward slashes in the `filenamePattern` config option would work nicely: `filenamePattern: '{transformString}/{fullname}--{fullname|shorthash}.{extension}'`.

Another option would be to introduce a separate config option explicitly for adding extra folders to the path, one that parses vars like `{filenamePattern}`.

Thoughts?

**Comment by aelvan** [comment]
I guess it could be doable, if you want that folder to be at the level before the actual file. Imager still needs to put the transforms for a specific image inside a structure that's `<imagerSystemPath>/<volume>/<id>/...` to be able to do cache breaking. So, is that still useful then, or were you thinking of having that transform string folder directly under the system path? 

Come to think of it, doing that would mean that there would only ever be one image image inside each folder, so... guess not. :)

**Comment by proimage** [comment]
Ah, hmm. I guess the end result I'd been wanting to achieve would be where the `<id>` bit is replaced by the Craft-esque pattern, so you'd end up with:

`<imagerSystemPath>/<volume>/<transformString>/<filenamePattern>`

I guess that would be more of a core change (or an option in settings) than a `filenamePattern` parsing enhancement.

**Comment by aelvan** [comment]
This would make it impossible to do fine-grained cache breaking, so it's not a no-go.
