### ISSUE TITLE
Server Error on grayscaling a black and white image

### ISSUE THREAD

**Issue by G17creative** [aelvan/Imager-Craft#254]
Our client occasionally uploads black and white images which we're transforming with the grayscale effect, this in turn breaks the page.

I've set 'suppressExceptions' to 'true' in the config but still getting the error. I've tried applying 'suppressExceptions' directly into the image transform and the error is still showing.

Not 100% on the correct way to do this so any help would be much appreciated, thanks!

**Comment by aelvan** [comment]
I need a stack trace to see where the error occurs, and preferably an example image that causes the error to occur.
