### ISSUE TITLE
Improve abstraction of transformers

### ISSUE THREAD

**Issue by Mosnar** [aelvan/Imager-Craft#255]
We use this plugin extensively and after wanting to look at switching our transformer service to an in-house transformer service, I found that the transformers were fairly tightly coupled to the services. Ideally, we'd be given an opportunity to register our own transformer providers. I'd hate to nullify all of the hardwork that went into this amazing plugin (and more, have to adjust all of my templates upon migrating!). If you're open to a PR and you don't have time to do it, I'd be happy to look at implementing this.

**Comment by aelvan** [comment]
Yes, I was planning on making transformers an extendable part of Imager, like effects and external storages, but never got around to it before the 2.0 release. I'll look into it for the next major release.

**Comment by aelvan** [comment]
[Imager X](https://imager-x.spacecat.ninja/extending.html) adds support for custom transformers.
