### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by boscho87** [aelvan/Imager-Craft#257]
https://github.com/aelvan/Imager-Craft/blob/craft3/src/helpers/ImagerHelpers.php#L370 causes this error! 

a simple `if(isstring($v)){}` around this line solved the issue for me....

What could be the Problem here?

I Updated from Craft2 to Craft-3.2 i did not Change anything in the Templates

**Comment by aelvan** [comment]
You're passing a DateTime object to one of the transform properties. Maybe you're using a field value for something, and the return value of the field has changed? The solution is to not do that - an `if` would just hide the underlying problem.

**Comment by boscho87** [comment]
sorry did not know much about the plugin.... my former co-worker installed it.... could fixt it with  a simple array_filter on the transform object.
