### ISSUE TITLE
Feature Request: Docs Wiki

### ISSUE THREAD

**Issue by kmgdevelopment** [aelvan/Imager-Craft#259]
This plugin obviously has a ton of features and it's a real pain to scroll around and CTRL+F looking for the right section of the README file. Would love to see the docs moved over to Github's wiki section for easier navigation. Thanks!

**Comment by aelvan** [comment]
Oh, I love the ability to use CTRL-F. ;)

I won't spend any time on this now, but for the next major version, I'll probably create some proper docs with vuepress or similar.

**Comment by aelvan** [comment]
[Imager X](https://imager-x.spacecat.ninja/) has much improved docs.
