### ISSUE TITLE
Issues with image files extensions

### ISSUE THREAD

**Issue by superflausch** [aelvan/Imager-Craft#26]
Not 100% sure what's happening but I noticed the following behaviour. Images with a capitalised file extension (e.g. JPG instead of jpg) get somehow generated but end up not being processed (compression) properly. If I change the extension from JPG to jpg and clear the cache the new file gets generated correctly.

Not sure if this is a bug or an environment thing. Let me know if I can provide additional info.

Cheers

Pascal

**Comment by aelvan** [comment]
You are correct, this was a bug in Imager. It has been fixed in 1.0.6 which I just pushed. Thanks for discovering this. :)
