### ISSUE TITLE
The `noop` setting isn't wired in yet, but is documented.

### ISSUE THREAD

**Issue by meredevelopment** [aelvan/Imager-Craft#260]
Hi, I've just attempted to use the `noop` config setting and see it's not working because it's not been completed: 

```
if ($config->getSetting('noop', $transform)) {
    // todo : just return source image unmodified
}
```

For now I've added this to the `transform` function in the `CraftTransformer` class as a workaround but would like to see it in the core please.

```
if (ImagerService::getConfig()->getSetting('noop')) {
    $msg = Craft::t('imager', 'Noop activated, returning “{path}”.', ['path' => $sourceModel->url]);
    Craft::info($msg, __METHOD__);
    $transformedImages[] = $sourceModel;
    return $transformedImages;
}
```

Thanks!

**Comment by aelvan** [comment]
This has been fixed for the next release.
