### ISSUE TITLE
allowUpscale documentation

### ISSUE THREAD

**Issue by darylknight** [aelvan/Imager-Craft#263]
In the docs, `allowUpscale` is listed under the global configuration settings here: https://github.com/aelvan/Imager-Craft#allowupscale-bool. However, setting this in imager.php under `'*'` doesn't seem to do anything. However, it does work if you create a transform and pass it as an option like this:

`{% set imageSizes = [{ width: 530, allowUpscale: false }] %}`.

Am I just misunderstanding the layout of the docs, or are they incorrect?

**Comment by jan10** [comment]
You can adjust the settings like this:

```php
<?php
/**
 * config/imager.php
 */

  return array(
    'allowUpscale' => false,
  );
```

**Comment by darylknight** [comment]
Ok, thank you.
