### ISSUE TITLE
webp support is not detect

### ISSUE THREAD

**Issue by MrGlasspoole** [aelvan/Imager-Craft#264]
I get this:
![Imager](https://user-images.githubusercontent.com/2067170/62791963-88a42980-bace-11e9-841c-1227ad720d47.jpg)

I wrote my hoster and they say webp is supported and they tested it and it does work.

Edit:
I made my own test with:
```
<?php
$filename = dirname(__FILE__) .'/example.jpg';

$im = imagecreatefromjpeg($filename);

$webp =imagewebp($im, str_replace('jpg', 'webp', $filename));
imagedestroy($im);

var_dump($webp);
?>
```
and that works.

**Comment by aelvan** [comment]
What method for generating webp are you using; the cwebp runtime, or the image driver (ie GD/Imagick)? And if it's the second, which image driver are you using?

**Comment by MrGlasspoole** [comment]
Its all default except:
```
<?php
return array(
        '*' => array(
        'imagerUrl' => 'https://mydomain.net/imager/',
		'jpegQuality' => 90,
		'cacheDuration' => 31536000
	)
);
```
So Imager is using Imagick?

It's a simple webhosting with just ftp (no ssh).

Doing this shows a NO:
```
    {% if craft.imager.serverSupportsWebp() %}
      YES
    {% else %}
      NO
    {% endif %}
```

**Comment by aelvan** [comment]
Your test above is using `imagewebp`, which is a GD function. If you haven't configured which imageDriver to use in Craft, and you have both GD and Imagick installed, Craft will auto select Imagick. Imager uses the imageDriver configured in Craft.

So, looks like you have webp support in GD, not Imagick. You can either change imageDriver to GD (this will affect all transforms and may not be a desired solution), get webp support in Imagick (which is probably a long and winding road), or install the cwebp runtime on the server (which may not be possible if this is a shared environment).
