### ISSUE TITLE
Use imager with headless craft and graphql

### ISSUE THREAD

**Issue by Jones-S** [aelvan/Imager-Craft#267]
Hi there
I tried to get my head around the usage of imager with a headless craft installation, but did not have any success so far.

I also did not find any documentation on that.

I have the following situation:
I upload a normal image to a volume and I get the url of the asset via graphql.
How could I now get a specific image transform for that asset via imager?

Do I have to write something custom that runs commands like `craft.imager.transformImage(image, { width: 1000 })` or how could I achieve this?
(And if yes, where would I write this? Would that be a service? Any pointers are very welcome...)

Thank you in advance
Cheers

**Comment by Jones-S** [comment]
Well I totally missed that I can request image transforms with graphql as well: https://github.com/markhuot/craftql#transforms
I think this could solve my problems.

**Comment by aelvan** [comment]
In the case of the CraftQL plugin, this is something that needs to be added to that plugin. I'm looking into if it's possible to add custom directives to the built-in GraphQL support (which is what would be needed).
