### ISSUE TITLE
Feature Request: Craft CMS 3.3 GraphQL support

### ISSUE THREAD

**Issue by EternalBlack** [aelvan/Imager-Craft#269]
Would be awesome to use Imager from GraphQL that got introduced in Craft CMS 3.3.

**Comment by aelvan** [comment]
Not sure if it's possible to add custom directives at the moment, there is currently no documentation for it at least. If possible, I'll add it.

**Comment by aelvan** [comment]
[Imager X](https://imager-x.spacecat.ninja/usage/graphql.html) adds support for GraphQL.
