### ISSUE TITLE
Facebook external image fails

### ISSUE THREAD

**Issue by mustasj** [aelvan/Imager-Craft#27]
Trying to load an image from [facebook](https://external.xx.fbcdn.net/safe_image.php?d=AQAAfofPs1cgXSjc&url=https%3A%2F%2Fwww.facebook.com%2Fads%2Fimage%2F%3Fd%3DAQLu016oF-JVlnJCtuOLDeSlAMG6C9GzAKEpS5vVvqvsRNrImzC_ANVizjWDQ32PPKi0wopC6AZbysRgwSYkFgbDl9E5U0abejll0BZbiKPboqd_qb4eObeSNG_sXeeOimBeh04F5MHLx5fg7JE1_An9) that i get from the placid plugin with the graph api.
I get this error when it tries to transform: 

> Source folder “/Users/bruker1/Lokale sider/Mind/wwwhttps://external.xx.fbcdn.net/” does not exist

The other pictures from the feed is being transformed. This is the only one with the safe_image.php in the url, maybe some restrictions?

**Comment by aelvan** [comment]
This was fixed in the latest release.
