### ISSUE TITLE
Apply focal point automatically

### ISSUE THREAD

**Issue by timkelty** [aelvan/Imager-Craft#270]
If an asset has a focal point set, that should always be used, unless the imager tag is explicitly setting a `position`.

So, this shouldn't be necessary: 

```
{% set transformedAsset = craft.imager.transformImage(asset, { width: 500, position: asset.getFocalPoint() }) %}
```

@aelvan if you agree, I can work on a PR

**Comment by missmatsuko** [comment]
Haha sorry, I spoke too soon. I had some other code that was setting the focal point. Anyways, maybe it *should* be a new keyword in config for `position`.

<strike>Agreed! But I found that it seems to use the focal point when [`position` in config](https://github.com/aelvan/Imager-Craft#position-string) is set to `null`. Maybe this should be explicitly documented, if it is the expected behaviour. And perhaps `null` should be the default value rather than `50% 50%`.</strike>

**Comment by timkelty** [comment]
> maybe it should be a new keyword in config for position

Like: `position: 'focalPoint'` or something?

That could be a way to go to avoid a breaking change…but honestly I can't think of a reason you wouldn't want to crop to a focal point by default if one existed.

**Comment by aelvan** [comment]
@timkelty @missmatsuko Thanks for the PR's, and bringing up the issue. One thing to keep in mind is that Imager also can transform external images which doesn't have a focal point, in which case it would be nice to have a default position to fall back on. Which makes setting position to 'focalPoint' or null, less attractive. Also, I don't want to do something that without warning could change the transforms for existing projects.

So I'm thinking that maybe a new config setting (`useNativeFocalPointAsDefaultOrSomething`) that is set to false by default, would be the cleanest solution for Imager 2. And then set it to true for the next major version. 

I'll leave this over and give it some more thought.

**Comment by timkelty** [comment]
Thanks @aelvan!

**Comment by timkelty** [comment]
> And then set it to true for the next major version.

…or in the next major you might even be able to drop that config setting all together.

**Comment by aelvan** [comment]
I decided to go ahead and add this in v2.3.0. No config setting, Imager will automatically add it when transforming Asset elements, external url's will still use the config setting. 

Thats for contributing!

**Comment by darylknight** [comment]
This is great - just saw it in the patch notes. Never even occurred to me really, but of course you'd want to default to the focal point if there is one.
