### ISSUE TITLE
rotate images?

### ISSUE THREAD

**Issue by MrGlasspoole** [aelvan/Imager-Craft#273]
Is there a function/transform for rotating images?

For responsive images on phones you sometimes need them as landscape and sometimes as portrait.

**Comment by aelvan** [comment]
Wouldn't you usually crop and resize images to achieve that in a responsive website? 

Anyways, no, there is no way of rotating with Imager, but it can easily be done with CSS.

**Comment by MrGlasspoole** [comment]
Ok, so i need to upload the pictures already rotated.

The problem is i cant think of a way how to do it in the template how to make a image (landscape) the alternative for the other image (portrait).

It does not work with CSS. Only with JavaScript because you need to recalculate the view port.

I have pictures where it does not make sense to crop because i need to show the whole picture.
On a phone in portrait mode they are bigger than needed and if the pictures where in landscape they would take less bandwidth.
