### ISSUE TITLE
Imager stores uploads in wrong folder aws cloudfront

### ISSUE THREAD

**Issue by geoffreyvandamme** [aelvan/Imager-Craft#275]
Hi Guys, 

I'm experiencing a very strange problem with my imager/aws-cloudfront configuration, everything has been working up to now perfectly, but all of a sudden, imager started uploading my images in aws in the wrong folder;

i'm working with a craft multisite setup, and it seems that imager now stores everything in my bucket in a data-folder (and then subfolders depending on the website it is on), instead of my predefined folder that it should store in. The strangest thing is that on my local environment, everything still works as it should (and imager uploads in the folder i defined), but on my staging environment, the images upload in that data-folder. Do you guys have a clue what i'm doing wrong here? (or is there some update that causes this? since it has been working perfectly up to now?) here is my imager.php config:

`<?php

  return array(
    '*' => array (
      'cacheEnabled' => true,
      'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] .'/imagertransforms/',
      'hashRemoteUrl' => true,
      'imagerUrl' => 'https://mycloudid.cloudfront.net/definedfolder',
      'storages' => ['aws'],
      'storageConfig' => [
        'aws' => [
          'accessKey' => 'mykey',
          'secretAccessKey' => 'myaccesskey',
          'region' => 'eu-west-3',
          'bucket' => 'mybucket',
          'folder' => 'definedfolder',
          'requestHeaders' => array(),
          'storageType' => 'standard',
          'cloudfrontInvalidateEnabled' => true,
          'cloudfrontDistributionId' => 'mycloudid',
        ]
      ],
    )

);`

**Comment by aelvan** [comment]
Which version of Imager are you using?

**Comment by geoffreyvandamme** [comment]
v2.1.10, the latest version, also updated my craft setup and the amazon aws plugin to be shure, but the problem persists

**Comment by geoffreyvandamme** [comment]
@aelvan if i connect locally with my remote db from staging, everything is working fine to, it's when i'm actually uploading images from my staging environment

**Comment by aelvan** [comment]
How have you set up multisite, du you have the old setup with separate index files in different folders? Or does Craft auto-detect based on the URL? 

Btw, 2.2.0 is the latest version, released a couple of days ago. There's a fix for an error that seems related to this, but.. not quite.

**Comment by geoffreyvandamme** [comment]
hmmmz, yeah i'm working with the old setup with seperate index files, different web folders for the different websites, with an imager folder for the transforms, on amazon it's also storing the files like this, it's taking the folder structure from my domain and subdomains

**Comment by geoffreyvandamme** [comment]
@aelvan updated to the latest version of imager, but problem still persists :(

**Comment by aelvan** [comment]
Well, if you have separate index files in different folders, `$_SERVER['DOCUMENT_ROOT']` will resolve to different paths. So it's more surprising that this works locally and used to work (?) on staging. 

To debug further, you could try to dump the paths in question using `Craft::dd([$path, $config->imagerSystemPath, $uri]);` on line 143 of CraftTransformer.php. This should output something like:

```
[
    0 => '/my/local/path/web/imager/s3images/352/myimage.jpg'
    1 => '/my/local/path/web/imager/'
    2 => 's3images/352/myimage.jpg'
]
```

Where the second path is stripped from the first, to get the final relative path to upload to (third).

But, I'm pretty sure you'll solve this by not using `$_SERVER['DOCUMENT_ROOT']` and instead define the actual path, either directly in the setting or via an alias.
