### ISSUE TITLE
Clone method is deprecated

### ISSUE THREAD

**Issue by mikestecker** [aelvan/Imager-Craft#28]
I was trying to use the `colorBlend` option and I'm getting the following error on imager/services/ImagerService.php(1134):

`Imagick::clone method is deprecated and it's use should be avoided`

I installed Imagick on my local machine using Homebrew.

`imagick module version => 3.3.0`
`PHP Version => 5.5.35`

**Comment by mikestecker** [comment]
I fixed mine manually, but here's all that needed to be changed:

on imager/services/ImagerService.php, line 1134 change to:
`$alphaChannel = clone $imagickInstance;`

on imager/services/ImagerService.php, line 1139 change to:
`$clone = clone $imagickInstance;`

**Comment by fThues** [comment]
Thanks! I just submitted PR #37.
