### ISSUE TITLE
Imager generating transforms in wrong location during console commands

### ISSUE THREAD

**Issue by bossanova808** [aelvan/Imager-Craft#280]
I'm not sure if I am missing some config somewhere, but when I run various console commands, imager is generating transforms in my root directory, rather than under `/web` as I would expect and it otherwise does normally.

(These console commands update order statusses, so these transforms are for images in emails I'm pretty sure).

Any tips for config or is this maybe a bug?

**Comment by aelvan** [comment]
How have you configured your `imagerSystemPath`? Might be that it's using a global var or an alias that isn't defined for console commands? Or maybe the environment isn't set properly, although then you probably wouldn't be able to access the database either..

**Comment by bossanova808** [comment]
Yep for sure that is configured - working find on dev/staging/production with all transforms created under `/web` ... _except_ when I run console commands.  So in general the env is ok as indeed the DB can be accessed etc.

That said, perhaps you are right - the document root may not be set for console commands?  I am using:

`'imagerSystemPath' => realpath($_SERVER['DOCUMENT_ROOT']) . '/_201904_imager-transforms/',`

Given there's no web server here I guess that is it, huh?  Might have to put a console command test in there and build the path manually under those circumstances.

**Comment by aelvan** [comment]
Yeah, that is probably it. When you said `...is generating transforms in my root directory...`, did you mean the root of your project (I first thought you meant at the root of your disk)? If so, it makes sense, `DOCUMENT_ROOT` is defined, but the root is where your `craft` script is, which is in your project root. Try substituting your `imagerSystemPath` with:

`'imagerSystemPath' => '@webroot/_201904_imager-transforms/',`

Or define a separate alias that is configured for all environments.

**Comment by bossanova808** [comment]
Yep I meant project root, not `/` whch would have been a bit of a bigger issue ;)

`@webroot` seems a sensible solution, will give that a go.  Thanks!
