### ISSUE TITLE
Gifsicle being ignored

### ISSUE THREAD

**Issue by devotoare** [aelvan/Imager-Craft#287]
I have the below config set up. However, gifsicle doesn't appear to be being used for animated gifs. I am using a Docker container with Alpine linux and have installed gifsicle and if I bash in I can run the command manually. 

Why I don't think it's being used is because it is taking a 2.9mb gif and turning it into an 11.1mb gif. However if I run the the command manually using the options in my option string it comes out at 1.4mb. So clearly something isn't right.

Any help would be appreciated.

```
    'optimizers' => ['gifsicle'],
    'optimizerConfig' => [
        'gifsicle' => [
            'extensions' => ['gif'],
            'path' => '/usr/bin/gifsicle',
            'optionString' => '--optimize=3 --colors 64'
        ]
    ]
```

**Comment by aelvan** [comment]
Have you checked your logs for any error messages?
Have you tested to see if the transformed file has the same size if you remove gifsicle?

**Comment by devotoare** [comment]
The error logs are empty and removing/adding gifsicle has no effect.

**Comment by aelvan** [comment]
Ok, but if you are running in devMode when testing, you should have a log entries whether or not the optimizer fails. If the command is run, it'll say something like `Command "<gifsicle command>" returned "<result>"`. If the executable can't be found, it says something like `Optimizer GifsicleOptimizer could not be found in path <path>`.

If neither is in your log, the optimizer hasn't been run at all. If you're running them as a job (`optimizeType` set to `job`), your queue is probably not being run. Try changing `optimizeType` to `runtime` just to check if that's the case.

**Comment by devotoare** [comment]
I did that and got `Command "/usr/bin/gifsicle --optimize=3 --colors 16 -b "/var/www/html/web/assets/imager/s3/10902/gif-10-lossy_50ab3d46eadbd4af6b845e0994e3cada.gif"" returned ""`. The problem is the resulting image is 3x larger in size than the original (1.7mb > 5.4mb). But if I manually run the exact same command on the original image it comes out at 1.1mb. 

Would the empty return indicate nothing is actually happening?

**Comment by aelvan** [comment]
No, most of the time there will be no return value, that's ok.

The fact that the transformed file is bigger than the original, isn't unusual. When Imagick transforms the image, it basically takes out every frame, transform them individually, and merge them together into a single file. The result is like taking x number of images and saving them individually, the frame-to-frame optimizations that other tools do, won't be applied. 

But, that's where gifsicle helps. But just to clarify, the command _is_ running now? Was that after setting `optimizeType` to `runtime`? And now the file got smaller, but not as small as compressing the original?

**Comment by devotoare** [comment]
Yes I got that after setting `optimizeType` to `runtime`, and correct. The result is smaller than before, but not as small as just running `gifsicle` directly. Is ImageMagick being used even when gifsicle is? Is there a way to bypass that? 

Edit:
I guess it would need that still for cropping/sizing... hmm.

**Comment by aelvan** [comment]
Yeah, Imagick has to do the transform, gifsicle is only used for post optimizations.

But resizing, cropping and other basic transform things are actually available in gifsicle, so in theory you could use only gifsicle in some cases. But not in a way that's supported in Imager currently. In the next major version, there will be support for custom transformers, which will make it possible to make a custom gifsicle transformer and used that directly.

**Comment by devotoare** [comment]
Cool, thanks for the help!
