### ISSUE TITLE
How to handle 301 image redirects

### ISSUE THREAD

**Issue by kaspar-allenbach** [aelvan/Imager-Craft#290]
I have a few images on a site which receive quite some traffic because they are well ranked in the google image search.

But because of the `transformString` variable in the filename the url results in a 404 when I try to optimize the images.

I guess it's not a good idea to remove the `transformString` altogether from the filename.

Is there some best practice to handle this?

**Comment by aelvan** [comment]
> But because of the transformString variable in the filename the url results in a 404 when I try to optimize the images.

Not sure what you mean? Are the images that are indexed already transformed? But if you change the transform, the filename changes, is that what you mean?

**Comment by kaspar-allenbach** [comment]
> But if you change the transform, the filename changes, is that what you mean?

Jep. That's what I mean. I'm playing with jpgQuality a bit and so the transform changes. I wonder if there is a possibility to have a consistent filename

**Comment by aelvan** [comment]
Ah, ok.. No, you could play with the `filenamePattern` I guess (you can use it on a per transform basis), but I think it would be rather hard to pull off, unless you can pinpoint exactly where that one transform is being done, and do an exception for exactly that transform. 

I think I'd rather go a more traditional route and create a new transform that you're happy with, and create a 301 redirect in your webserver.
