### ISSUE TITLE
Create source folder if it doesn't exist.

### ISSUE THREAD

**Issue by tmrkp** [aelvan/Imager-Craft#293]
Hey,

we get the following error on a regular basis: Source folder “...” does not exist. This is caused, because that folder is excluded from our git repository. So when people clone the repo to their local machine, they are missing the source folder.

The error makes perfect sense to me, but I thought it would maybe be possible to just create the missing folder to avoid that error and if that fails as well you can still throw an error "source folder is missing and could not be created". Or is there a reason for this, I'm not aware of?

It's definitly not a major issue and can easily be fixed manually, but I thought it would just be nice to have and could avoid confusion for new users.

**Comment by aelvan** [comment]
Well, I can of course try to create it like I do with the target folder but.. If the source folder does not exist, the source files are not there either. So you'll just get an error about the file you're trying to transform is missing? So it doesn't get you anywhere. Unless I completely misunderstood what you meant..?

**Comment by tmrkp** [comment]
Yeah, you're right. Creating the folder would not solve the problem. Even if I create it manually, I would the the source files itself as well. A programmatic solution is not possible.
