### ISSUE TITLE
Imager equivalent of generateTransformsBeforePageLoad native setting

### ISSUE THREAD

**Issue by romainpoirier** [aelvan/Imager-Craft#296]
On a page showing several images with each a few images transforms (for several breakpoints + Retina), I end up with a lot of images transforms required.

However, this requires so much memory that these pages doesn't load, and end with a server error (like `max_execution_time`). Even if these images will not be shown, they block the page rendering. In that way, I found Imager less convenient that the native Craft way, because of this.

Is there any option that disable the images generation before page load? With the native Craft way, there's the `generateTransformsBeforePageLoad` config. I'm looking for an Imager equivalent.

I know there's now Imager X, but it's a paid plugin and the automatic generation of transforms features are not working the same way.

**Comment by aelvan** [comment]
See my reply [here](https://github.com/aelvan/Imager-Craft/issues/282#issuecomment-549518050).
