### ISSUE TITLE
Add 'retina option' for transform 

### ISSUE THREAD

**Issue by m9dfukc** [aelvan/Imager-Craft#32]
~~Please add the option for automatically transform the image to retina and nonretina resolutions and output the image tag with `srcset` the attribute.~~

Sorry this was actually meant for https://github.com/mmikkel/RetconHTML-Craft ... to many browser tabs open ;)

**Comment by aelvan** [comment]
If you use `srcset` and `sizes` (as per the specifications), talking about "retina" is irrelevant. The browser will pick the most appropriate image depending on the device's capabilities, including, but not restricted to, pixel density.

Read more [here](https://ericportis.com/posts/2014/srcset-sizes/).
