### ISSUE TITLE
Enhancement: Alpha Compositing 

### ISSUE THREAD

**Issue by pixeljitsu** [aelvan/Imager-Craft#36]
It would be very handy to be able to create an alpha channel from an external grayscale image. See this for exactly what I'm describing: http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x31

The same would be true of combining images which already contain alpha channels: http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x50

**Comment by aelvan** [comment]
I agree, that would be sweet. Any suggestion as to how to syntax for something like that should be? How would one handle cases where the mask has a different size than the base image? Should it be part of the transformImage method, or a separate method?

**Comment by pixeljitsu** [comment]
Just from my own desire for this feature, I would expect that if I were trying to add an alpha to an image, that the alpha I've created would already be at the size I need to be.  So in the case that the source image and alpha image were different sizes, I would expect the alpha image to be stretched to fit the destination size. You can see that in [#31](http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#) the alpha is just stretched to fit the destination size.  I don't think that it would need to be any more versatile than this since this is a pretty custom process to begin with.

As far as where in the chain it should be, that's a bit tricky.  I can envision the need to add an alpha to an existing image (1:1) and then have the image resized up or down with the alpha already applied.  I can also see wanting to resize & crop an image to the size of the exiting alpha image and then apply it.

[#50](http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#) almost just like watermarking so that should not be that hard to pull off.  I have a use-case for this right now where I have a book publisher's site where they have cover photos of the books and separate author headshots in the site content.  For the social share images on the book's pages they want the book photo and the author photo composited over a common background image. Right now I'm photoshopping this manually I'd love to make the site do this for myself and the client without the need for one-off edits.

I suppose the main thing is to attempt to maximize utility and create templated image funcitons that will offer dynamic results w/o the client having to open photoshop or pay to have it done for them.

**Comment by aelvan** [comment]
This can be implemented in Imager 2.0 using a custom effect. This will not be added as a built-in effect in Imager.
