### ISSUE TITLE
Percentage base resizing

### ISSUE THREAD

**Issue by fractorr** [aelvan/Imager-Craft#39]
I am looking to resize images down by say 50% or 25% it doesn't look like this can be done with this right now.  I was looking at the code and was thinking I could add a mode called 'percent' and then add a check in the function _getResizeSize and return the sizes based on the width or height parameter.  Do you think this would be all that is needed to do percent based sizing?

**Comment by aelvan** [comment]
Considering how easy it would be to do this in twig, I don't see the point of adding extra functionality to the plugin to achieve this. You could simply go `{ width: image.getWidth()*0.5 }` in your transform object to resize to 50%.

**Comment by fractorr** [comment]
Being newish to Craft / Twig I was not aware that I could do that but I added that check in your code which took like 30 seconds and it worked perfectly.  So I just do this: 

{% set transformedImageThumb = craft.imager.transformImage(asset, { mode: 'percent', percent: 10 }) %}
