### ISSUE TITLE
Clear cache to greedy?

### ISSUE THREAD

**Issue by alexbech** [aelvan/Imager-Craft#4]
When clearing caches, the Imager-plugin seems to delete the .gitignore file in my imager directory.

**Comment by aelvan** [comment]
Using the built-in functionality for Craft, so this is not something I can change.

**Comment by benface** [comment]
Is this still the case for the Craft 3 version @aelvan? I'm experiencing this as well.

**Comment by aelvan** [comment]
I haven't tested this in Craft 3, but I assume it works the same as in Craft 2. Imager only registers the cache location to Craft, and the native cache clearing functionality is responsible for actually deleting the files. 

You should probably exclude web/imager/* (or whichever folder you've set the system path to be in) in your root .gitignore instead.

**Comment by benface** [comment]
> You should probably exclude web/imager/* (or whichever folder you've set the system path to be in) in your root .gitignore instead.

That's what I ended up doing, thanks :)
