### ISSUE TITLE
Optimizing message isn't going away

### ISSUE THREAD

**Issue by carlosperez** [aelvan/Imager-Craft#40]
I have the optimizing message in the Craft admin left nav showing constantly. In the craft_tasks table in the db, I notice there is an old entry for imager in there. Is it safe to just delete it to get rid of the message?

![screen shot 2016-07-11 at 7 56 11 am](https://cloud.githubusercontent.com/assets/1263213/16729857/248f1f70-473d-11e6-9ced-cd641c8fcb8b.png)

**Comment by aelvan** [comment]
Yes, you should just delete it. But notice that there will be some images that haven't been optimized by TinyPNG. 

The underlying reason for the task being stuck, is probably that the php request timed out. Check out [this support article](https://craftcms.com/support/stuck-tasks) for an explanation on why tasks get stuck in Craft (this is an Craft issue, not an Imager issue, per se).
