### ISSUE TITLE
FR: WebP Format

### ISSUE THREAD

**Issue by johanneslamers** [aelvan/Imager-Craft#41]
The average WebP file size is 25% – 34% smaller compared to JPEG file size. WebP compresses 34% better than libpng, and 26% better than pngout for loseless images. So an option to save the file as WebP would be awesome.

**Comment by aelvan** [comment]
I've looked into this from time to time and considered adding it. Unfortunately, the Imagine library which Craft uses, and which Imager piggybacks on, doesn

webp support in Imagick isn't very widely available.

**Comment by aelvan** [comment]
I've looked into this from time to time and considered adding it. Unfortunately, the Imagine library which Craft uses, and which Imager piggybacks on, doesn't support webp. I'd had to add this to Imager and do a switch to save the file with this for webp, and with Imagine for all other filetypes. Which feels a bit dirty. But, doable. 

But also, webp is supported by GD in PHP 5.5 and newer, but support in Imagick isn't very widely available. Even in the latest Ubuntu LTS, 16.04, Imagick isn't compiled with webp support. People can of course compile Imagick themselves and add it, but I don't think many will. Which questions how useful it'd be.

A different take on it, which I've considered, is doing the conversion with [Googles cwebp binary](https://developers.google.com/speed/webp/docs/using), which is easy to install on most distros. Then the files would be transformed to png or jpg first, and then converted to webp as a post optimization. Either in a transparent way to the end user by way of the format parameter, or something that's enabled with a setting.

The downside of this would be that Imager would actually be creating twice as many transformed files, which I guess could impact performance quite a bit. 

Let me know if you have any thoughts on this. I'm definitely interested in adding webp support, just not sure what the best way would be yet. :)

**Comment by johanneslamers** [comment]
I think the conversion with Googles cwebp binary would be a better fit. Because using WebP in the front-end you'll need to have a fallback. So twice as many transformed files can be a good thing. 

```
<picture>
  <source type="image/webp" srcset="images/butterfly.webp">
  <img src="images/butterfly.jpg" alt="a butterfly">
</picture> 
```

**Comment by aelvan** [comment]
Support for webp has been added to version 1.1.0. 

Most of the time I spent on this thing was getting a server environment up and running with support for webp. You can use either GD, Imagick or the cwebp binary, depending on what you can get working. GD has some limitations (no transparency for instance), and using the cwebp method is a little bit slower since it has to create a temporary jpeg or png file first to have something to convert from. But cwebp is probably the easiest one to get working. 

Let me know how it works for you if you try it.
