### ISSUE TITLE
Exception with Multi-Lang

### ISSUE THREAD

**Issue by slimiles** [aelvan/Imager-Craft#42]
Hi

I use Imager for every CraftCMS project and I'm really in love with your plugin. Thanks for this!

Today I started a new project with **Multi-Lang**. After the installation and setup of the languages (DE is default and EN is 2nd), I'm running every time in this exception (image):

![imager-failure](https://cloud.githubusercontent.com/assets/3016343/16916509/77429164-4cfd-11e6-8283-04acd6c68af9.png)

For a better insight in my problem, I reproduced a example in this repo: [imagerMultiLang](https://github.com/slimiles/imagerMultiLang). 

I really hope you can help me, because it's a customer project and I'm already in delay. ;-)

Thanks and Cheers from Switzerland,
Selim

**Comment by aelvan** [comment]
There seems to be a problem with the setup of your asset sources. The error indicates that Imager can't find the source file in .../imagerMultiLang/public/en/uploads/images/content/. I guess what you want is to have the uploads in .../public/uploads/..., not .../public/en/uploads.., .../public/de/uploads... etc? 

How is your file system path and url set up on this asset source?

**Comment by slimiles** [comment]
I use [HeartyConfig for CraftCMS](https://github.com/mmikkel/HeartyConfig-Craft). In my **general.php** is this UploadPath defined: 
```
'uploadPath' => PUBPATH . 'uploads',
'uploadUrl' => CRAFT_SITE_URL . 'uploads',
```
And in this setup is in the AssetSource:

![imager](https://cloud.githubusercontent.com/assets/3016343/17013314/f25f951e-4f1d-11e6-9c08-ace7d5b8e66a.jpeg)

**Comment by slimiles** [comment]
I figured it out with some help. With this settings in `general.php`, it works:
```
'uploadPath' => BASEPATH . 'public/uploads',
'uploadUrl' => CRAFT_SITE_URL . 'uploads',
```

Thanks anyway,
Selim

**Comment by slimiles** [comment]
I figured it out with some help. With this settings in `general.php`, it works:
```
'uploadPath' => BASEPATH . 'public/uploads',
'uploadUrl' => CRAFT_SITE_URL . 'uploads',
```

Thanks anyway,
Selim
