### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by benjamminf** [aelvan/Imager-Craft#44]
This might be a bit outside the scope of Imager but it'd be pretty useful if it supported PDF files for generating thumbnails of PDF documents. I found a couple of Craft plugins out there that do this but they were all abandoned and didn't work. I thought it might suit being a feature in Imager.

Love the plugin too by the way, an absolute must-use for all sites 👍

**Comment by aelvan** [comment]
Was considering this for a long while, but... I think some else should make a plugin called `Pdfer`. :)
