### ISSUE TITLE
cacheDuration set to false

### ISSUE THREAD

**Issue by aelvan** [aelvan/Imager-Craft#45]
Since Craft already has a `cacheDuration`, and it can be set to `false` to always cache, Imager should do the same.

**Comment by aelvan** [comment]
Was added to 1.2.0.

**Comment by matt-adigital** [comment]
Could this please be added to the documentation as a note against the cacheDuration and what values it can accept? Just been googling around to see if it can accept false before I eventually found it here. Thank you.
