### ISSUE TITLE
WebP Format and srcset generation

### ISSUE THREAD

**Issue by exophunk** [aelvan/Imager-Craft#46]
Hi, I've tried to use the new ability to output webp images for responsive images with srcset="".

Now, when I choose the webp format and then output the transforms into srcset with `craft.imager.srcset(transformedImages)`, the generated output is invalid, because for some reasons the image widths don't get appended. It only outputs `w` instead of e.g. `800w`

`srcset="image1.webp w, image2.webp w"` instead of `srcset="image1.webp 800w, image2.webp 300w"`

And the srcset doesn't work without the widths specified correctly. It seems to be that Imager has a problem with getting the image width, if it's a webP image? With jpg, it works perfectly fine.
Any solution to this?

Thanks, Robert

**Comment by aelvan** [comment]
Right. I'll look into this, but I guess the reason is that the built-in php `getimagesize` function might not be working for webp in some cases. What method do you use to generate webp; gd, imagick or cwebp?

**Comment by aelvan** [comment]
This should have been fixed in v1.1.1 which was just pushed.

**Comment by exophunk** [comment]
Yes this worked, thank you for the update
