### ISSUE TITLE
Imager caches not cleared by craft()->templateCache->deleteAllCaches();

### ISSUE THREAD

**Issue by roberttolton** [aelvan/Imager-Craft#47]
Hi,

I'm using `cache-clear` from:
https://github.com/themccallister/craft.cache-clear

This lets me, for example, after deploying to staging, clear all caches in the system. However, Imager caches don't get cleared.

It uses `craft()->templateCache->deleteAllCaches();` to clear the cache, but Imager doesn't seem affected by this?

Is there a hook that could be added to trigger Imager's cache clearing?

Thanks,

**Comment by aelvan** [comment]
Yeah, the Imager cache isn't deleted when the template cache is, that would wreck havoc in most scenarios.

There isn't a service method right now for deleting the Imager cache, but I could of course add that. But, why do you need to clear the Imager cache when you deploy? Imager doesn't use the database, like the template cache, so unless you have the imager transforms folder in your repo, which you shouldn't, the transforms will be created if there were any changes.

**Comment by roberttolton** [comment]
I have `public/imager` in my `.gitignore` so they're not in the repo.

When I deploy (which is DeployHQ using SFTP), it clears Craft's template cache for obvious URL reasons, but all the images that use Imager don't load and can't be found until I clear all the caches in the admin panel.

All I do is upload images to fields within Craft locally, dump my database to SQL file which then all gets uploaded and imported to staging.

**Comment by roberttolton** [comment]
Perhaps I can add a bash script that dumps the contents of `public/imager` after a deploy, that should be ok, right?

**Comment by aelvan** [comment]
I've added controller actions for clearing caches, see the "Controller actions" section of the documentation.
