### ISSUE TITLE
[Request] Add Cloudfront invalidation after transformed images back to S3

### ISSUE THREAD

**Issue by mikestecker** [aelvan/Imager-Craft#48]
_I'll preface this by saying my knowledge is limited and I might not be using the correct terminology so excuse me :-)_

I've noticed that on pages with a number of image transformations that there can be a timing issue with hitting the Cloudfront URL before the transformed images have finished uploading back to S3.

I found another [plugin that does invalidation](https://github.com/sjelfull/Craft-CloudFrontInvalidation) but maybe it would be good to trigger something like this after the upload process to S3 has finished?

Here's what was happening in my case:

1. User hits webpage that isn't cached
2. Template loaded, imager triggered (pulls source asset from S3, resizes, pushes back to S3), returns with the Cloudfront URL rather than S3 url.
3. User's browser loads rendered/cached webpage, hitting the Cloudfront url to the image... but that image hasn't finished uploading to S3 so Cloudfront returns 404.

So I was thinking if there was a way to trigger Cloudfront to re-cache the image after the upload process has been confirmed as complete?

Thoughts?

**Comment by aelvan** [comment]
Cloudfront invalidation is a good idea. I've actually run into problems myself with transforms not invalidating when using Cloudfront with S3. I'll have a look at it.

That said, I don't really understand why this would be a problem in your case. The file should be done uploading to S3 before the template is rendered and the user hits it. Unless there's a second user that hits the same page between the transform is generated in the imager system path, and the file being uploaded to S3.. I can see that happening for high-traffic scenarios.. Do you have alot of traffic on the site you're seeing this on?

Anyways, it'd be nice to have cloudfront invalidation in there for other scenarios too, so. I'll look into it. :)

**Comment by aelvan** [comment]
This has been added to 1.2.0. Read the documentation for config settings (and a "please note" warning).
