### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by isaachorton** [aelvan/Imager-Craft#5]
When trying to run a simple transformation I am encountering a permission denied error.

This:
```
{% set image = craft.assets().limit(1).first() %}
{% set transformedImage = craft.imager.transformImage(image.url, { width: 1000 }) %}
```

Results in this:
```
imagejpeg(agarwal-ajay_d4e4e04a52bfbdbeab5ba4d2cf1d1390.jpg): failed to open stream: Permission denied
/craft/app/vendor/imagine/imagine/lib/Imagine/Gd/Image.php(697)
```

The full stack trace is attached. I double checked my permissions and can run ```setTransform``` with no issues.

[RuntimeException.pdf](https://github.com/aelvan/Imager-Craft/files/37524/RuntimeException.pdf)

**Comment by isaachorton** [comment]
A quick update on this. When I use the default ```imagerSystemPath```, everything works correctly. It doesn't look like the settings in the ```imager.php``` config file are being used.

**Comment by aelvan** [comment]
Yes, looks like the path is blank. Are you sure the path you have set in imager.php is valid?

**Comment by isaachorton** [comment]
Yes. If I hardcode the path into the plugin config.php it works. It looks like the ```/craft/config/imager.php``` file is being ignored. Here is what I currently have

```
return array(
  '*' => array(
    'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/assets/files/_t/',
    'imagerUrl' => '/assets/files/_t/',
  ),
);
```

**Comment by aelvan** [comment]
Sorry for the late reply. I've tested this and it works for me. 

What OS/Webserver are you on?

**Comment by isaachorton** [comment]
I ended up resolving the issue by changing the permissions on the config file from 0755 to 0777. Not sure why craft needs write permission? 

Thanks for replying. Can I make a donation for this add-on? It's been super useful. :)
