### ISSUE TITLE
Add picture element support

### ISSUE THREAD

**Issue by tortilaman** [aelvan/Imager-Craft#50]
I think it would be great to have support for the `<picture>` element. It's not that imager doesn't have support for it now, it's just that there's no way to grab one one of the sizes from the `transformImage()` command and use it in different `<source>` tags within your `<picture>` tag. 

I might be mistaken about this, but if this isn't possible, I think it would be really great if it was added, as currently you have to do a separate `transformImage()` for each `<source>`

I would try and do it myself, but I have no knowledge of PHP, and no time to learn at the moment.

**Comment by aelvan** [comment]
What's the desired output that you want? Not sure I understand how Imager can help in automating the use of <picture> and <source>.

**Comment by tortilaman** [comment]
I realized shortly after this that there's no need to have a function or anything explicitly created to suit this use case. As imager creates an array of image transforms, you can just access it like any other array. I might suggest adding information on this to the readme though, as information on implementing responsive imagery that includes srcset and not the picture element seems rather incomplete.

**Comment by aelvan** [comment]
Ok. But, I'm curious, what are you trying to achieve?

**Comment by tortilaman** [comment]
I just wanted a fully modern image implementation that would work for all devices.

**Comment by aelvan** [comment]
Sure, but there's no reason why Imager should need to know anything about <picture>. For each source in the picture element, you create a separate set of images with Imager, and what markup you put around it is totally up to you. 

I might not understand what you feel is missing, that's why I asked for an example of what you're trying to achieve.
