### ISSUE TITLE
error calling craft.imager.hasSupportForWebP 

### ISSUE THREAD

**Issue by magicspon** [aelvan/Imager-Craft#53]
Hello,

I tried to create a webp image but my version of GD doesn't support it, so i got the following error:

```
This version of GD does not support the webp format. You should use “craft.imager.hasSupportForWebP” in your templates to test for it.
```

I then tried to use `craft.imager.hasSupportForWebP` but then got another error
```
Neither the property "hasSupportForWebP" nor one of the methods "hasSupportForWebP()", "gethasSupportForWebP()"/"ishasSupportForWebP()" or "__call()" exist and have public access in class "Craft\ImagerVariable"
```

Cheers

**Comment by aelvan** [comment]
This was an error in the error message. :) It was suppose to say `You should use “craft.imager.serverSupportsWebp” in your templates to test for it.`. Fixed for next version.

So, you can use `craft.imager.serverSupportsWebp` to test for server support for webp in your templates.

**Comment by magicspon** [comment]
Thanks
