### ISSUE TITLE
Frequent getimagesize(): Read error!

### ISSUE THREAD

**Issue by cmalven** [aelvan/Imager-Craft#54]
On a site we're using Imager for, we're getting frequent `getimagesize(): Read error!` both on the live server (Microsoft Azure) and locally, both using `imagick` and both referencing the same source assets stored on Amazon S3.

We're receiving the same error regardless of which assets are being referenced on the affected entry. What else can we provide to help track this down?

Attached is one such example of the error in action:

![fireshot capture 002 - php notice_ - http___localhost_3000_insights_fiv](https://cloud.githubusercontent.com/assets/610118/19197444/80f03fd8-8c7f-11e6-9be1-df269591f79b.png)

**Comment by aelvan** [comment]
Haven't encountered this before. Does it happen consistently for certain images, or completely at random? Is this on pages with a lot of images, or does it also happen on pages with few images? 

It's worth noting that when you have images on an external system, Imager will download and cache the file locally, transform it, and then upload it to the service again, which takes quite a while. If the PHP process times out, things can be in a bit of a flux, where partially downloaded files exists, which PHP could have problems with reading. But, I've done a lot of safe-guarding concerning this, and I've never encountered that such an errors occurs at this point. Should happen before Imager gets to this point. But, what settings do you have for execution timeout in PHP? What webserver are you running locally, Apache or nginx?

**Comment by cmalven** [comment]
Thanks for the response @aelvan Since originally posting we've discovered some other file storage oddities on the server that may point to something outside of Imager. I'll chime in again if it turns out to be specific to imager, but until then we can close this issue.
