### ISSUE TITLE
FR: pngquant

### ISSUE THREAD

**Issue by lexbi** [aelvan/Imager-Craft#55]
Hey,

Wondering if you will be looking into integrating [pngquant](https://pngquant.org/) for lossy png compression? I presume this is what tinypng uses, but, don't want to use them as I believe they add their own meta data & you need to pay if you use over 500 images per month.

Many thanks,
Joe

**Comment by aelvan** [comment]
I'll add it to my todo-list. :)

**Comment by lexbi** [comment]
Woop, thanks dude!

**Comment by timkelty** [comment]
👍

**Comment by aelvan** [comment]
This has been implemented and will be in the next release.

**Comment by lexbi** [comment]
thanks so much!
