### ISSUE TITLE
Interlace breaks animated gif

### ISSUE THREAD

**Issue by BryceBubbles** [aelvan/Imager-Craft#56]
This could be an issue for ImageMagick to fix, but as I came across it while using your awesome plugin I thought I'd check here first.

So when interlacing is used when converting an animated gif, the image becomes broken. 
Here's a stackoverflow question (not mine) detailing the issue, with an answer (not mine) that mentions needing to mark the interlaced flag in each header (not sure if that's the solution here or not).
http://stackoverflow.com/questions/33594336/gif-image-getting-distorted-on-interlacing

My current workaround will be to specifically disable interlacing for gif images from within my twig template.

Cheers

**Comment by aelvan** [comment]
Right. I haven't actually implemented support for animated gifs in Imager. If it works atm, it's ImageMagick doing a better-than-expected job. ;)

I'll keep this in mind when I (hopefully) get the time to look into animated gifs.

**Comment by frankharrison-wj** [comment]
Any idea if/when animated GIF support might appear? Just asking as we're starting a new project and might effect how we approach images... Great plugin btw, loving how well this thing works :)

**Comment by aelvan** [comment]
Support for animated gifs has been added in version 1.5.0.
