### ISSUE TITLE
Bug creating targetPath in ImagerService transformImage()

### ISSUE THREAD

**Issue by marionnewlevant** [aelvan/Imager-Craft#57]
Not sure what to do about it yet, but I am encountering this problem (starting around line 177). This is on mediatemple, which probably has something to do with it

        // $pathsModel->targetPath is set properly.
        // IOHelper::getRealPath($pathsModel->targetPath) - returns false
        if (!IOHelper::getRealPath($pathsModel->targetPath)) {
            IOHelper::createFolder($pathsModel->targetPath, craft()->config->get('defaultFolderPermissions'), true);
            // IOHelper::getRealPath($pathsModel->targetPath) - STILL returns false
            $pathsModel->targetPath = IOHelper::getRealPath($pathsModel->targetPath);
            // $pathsModel->targetPath is now false

            // IOHelper::getRealPath(false) returns our public path
            if (!IOHelper::getRealPath($pathsModel->targetPath)) {
                throw new Exception(Craft::t('Target folder “{targetPath}” does not exist and could not be created',
                  array('targetPath' => $pathsModel->targetPath)));
            }
        }
        // no error got thrown, $pathsModel->targetPath is false, and things don't work...

**Comment by marionnewlevant** [comment]
IOHelper::createFolder was failing silently (3rd arg: true). Fixed my permissions and got things working. I think you just need to move the assignment to $pathsModel->targetPath after the test to see if the path exists.

**Comment by aelvan** [comment]
Right, that logic was flawed. And moving the assignment of `$pathsModel->targetPath` after the test sounds like the best solution. Thanks for reporting and debugging!
