### ISSUE TITLE
Error Related to Cloudfront Invalidation

### ISSUE THREAD

**Issue by brettburwell** [aelvan/Imager-Craft#61]
Hi there, 

After enabling Cloudfront invalidation in my config file and adding the corresponding `cloudfrontDistributionId` I'm seeing an 'Array to string conversion' php error coming from line 1560 of the `craft/app/lib/S3.php` file: 

```
$rest = new S3Request('POST', '', '2010-08-01/distribution/'.$distributionId.'/invalidation', 'cloudfront.amazonaws.com');
```

This is probably stating the obvious, but best I can tell, the `$distributionId` above isn't being set correctly somewhere. I'm not a plugin dev or I'd dig into it on my end. 

For what it's worth, it only appears to be happening on the initial page load (with and without caching enabled). And when I disabled the Cloudfront invalidation the rest of Imager's AWS related functionality is working brilliantly. I've bumped into this same error on two separate projects (both running the latest version of Imager and Craft). 

Any thoughts would be much appreciated. 
And thanks for the great plugin. Imager is amazing.

**Comment by aelvan** [comment]
The `$distributionId` is passed to the S3 library method as a parameter, and Imager get's it from the settings. Are you sure that you've set it correctly in your config file? And that it's just a plain string?

**Comment by brettburwell** [comment]
Thanks for the follow up @aelvan. I'm almost certain it's set correctly. It's just a plain string and I've triple checked that I've grabbed the correct distribution ID in AWS. 

Below is what my `config.php` file looks like. Everything but the invalidation is working as expected. Is there anything in there that looks out of place / incorrect? 

```
return array(

  // Base Config
  'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/imager/',

  // Image Settings
  'allowUpscale' => false,
  'cacheDuration' => false,
  'cacheDurationRemoteFiles' => 7776000,
  'instanceReuseEnabled' => true,
  'interlace' => true,
  'jpegQuality' => 85,
  'resizeFilter' => 'hermite',

  // AWS S3 / Cloudfront
  'awsEnabled' => true,
  'awsAccessKey' => 'XXXXXXXX',
  'awsSecretAccessKey' => 'XXXXXXX',
  'awsBucket' => 'foo.com',
  'awsFolder' => 'imager',
  'imagerUrl' => 'http://XXXX.cloudfront.net/imager/',
  'awsCacheDuration' => 7776000,

  // Cloudfront Invalidation
  'cloudfrontInvalidateEnabled' => true,
  'cloudfrontDistributionId' => 'XXXXXXXXXX'
);
```

**Comment by aelvan** [comment]
Hi again Brett. I've set up a testcase and this seems to work for me. Your setup looks correct, so as long as that distribution id is correct I have no idea what could be wrong.

Right before that line in S3.php, could you try putting:

```
         print_r($distributionId);
         die();
```

Just to test if that id still is a string at that stage.

What PHP version are you running? (not that it should matter, but...)

**Comment by brettburwell** [comment]
Thanks again for the followup André. 

I just double checked the distribution id again and it's definitely correct. I put those lines into the `S3.php` file and it printed out the distribution id in the template. 

The site is running PHP7 on DigitalOcean + ServerPilot. 

Beyond the `imager.php` config, is there anything I'd need to setup in the Cloudfront area of my AWS account? Doesn't seem like the issue is on that end, but I'm scratching my head as to what the issue might be. The Origin is setup and working. The only issue seems to be with the invalidation.

**Comment by aelvan** [comment]
There shouldn't be anything more you need to set up in cloudfront. What credentials does your user have? Full access to cloudfront, or just readonly?

What throws me off a bit is the fact that the error is on line 1560. The only thing that happends on that line that may create that error is the concatination of the distribution id and the rest of the url. Can you still confirm that that's the line it fails on?

**Comment by brettburwell** [comment]
I just checked again and the error is on line 1570 of that `S3.php` file. My apologies if I had that wrong in my previous post. The full error is attached below in case it's helpful. 

The current IAM policy attached to the user has public read privileges. As a test, I created a new policy that granted full `AllowAllCloudFrontPermissions` access and attached it. That didn't seem to do the trick either. I also ran the original policy through the AWS policy simulator and tested all of the Cloudfront actions, which successfully passed. So I'm guessing it's not a policy / credentials issue.

I'm fully aware that this is a free add-on and don't expect you to go down the rabbit hole with me, but if you had any more clues / advice on things to check I'd very much appreciate it. 

![s3-error](https://cloud.githubusercontent.com/assets/1228671/21658166/121aa43e-d28b-11e6-93f0-8bfb1e7fae62.jpg)

**Comment by aelvan** [comment]
Interesting, line 1570 makes more sense. I'm able to recreate this error by supplying an incorrect distribution id, it appears that there's an error in the error handler. :) An error is raised, and `$paths` is passed into `sprintf` which doesn't work since it's an array. 

Try deleting `,{$paths}` in that line, that should result in an error message that actually shows what the issue is. 

Think we're getting closer. :)

**Comment by brettburwell** [comment]
Okay. I'm a liar! It looks like part of the issue was needing to add a proper IAM policy. When I deleted `,{$paths}` and reloaded I got the following error: 

```
[AccessDenied] User: arn:aws:iam::xxxxxxxxx:user/schulershook is not authorized to perform: cloudfront:CreateInvalidation
```
I took a second stab at adding a Cloudfront policy and attached it to the user and that appears to have helped. The odd thing is, the php error is no longer displaying, but now on the first load I see a generic looking `Internal Server Error` (attached below). When I reload the page everything is fine. 

To test out the invalidation I dropped a pink jpg into the site. Then I replaced that same asset with an updated (green) version of the image. I can see from Issue #52 that the invalidation wouldn't happen on replacement for the reasons you noted. But I also selected `Clear Imager transforms` from the Assets' dropdown with the asset in question selected. When I reload the page again I see the generic `Internal Server Error` on initial load. On the second load I see the original pink image, not the updated green image that I'd expect to see.

Maybe I'm misunderstanding how the invalidation should work. But even still, the random `Internal Server Error` leaves me wondering if/where something is failing.

Sorry if this is a pain. I very much appreciate you continuing to troubleshoot this with me.

**Comment by aelvan** [comment]
That error probably means that the invalidation does not happen. I assume you're running i devMode? Have you checked your php error log?

**Comment by brettburwell** [comment]
Hi André. 

I was able to track down some more info. Over the weekend (in prep for the project launch) I switched the site to HTTPS and forced CloudFront to serve all assets from HTTPS as well. I'm not sure why, but this appears to have updated the error messages that are being returned. 

Here's the sequence of events I followed: 
1. Upload a new image and add to entry
2. Replace the image in the Assets section of the admin. 
3. Select that image and then select `Remove Imager transforms` from the actions menu. 
4. Reload the page the image is being used on. I also tried re-saving the entry with no luck (the site is running in dev mode and the templates aren't being cached, but wanted to make sure I wasn't missing something silly). 

Below is the error I'm seeing reported in the `craft.log` file (I omitted the full stack trace for brevity). I'm not seeing anything in the `phperrors.log`.  
```
2017/01/16 22:31:35 [error] [exception.Twig_Error_Runtime] Craft\Exception: HTTP status “403” encountered while attempting to download “http://foo.cloudfront.net/general/test.jpg?mtime=20170116162808” in /foo/craft/plugins/imager/models/Imager_ImagePathsModel.php:247
Stack trace:
#0 /foo/craft/plugins/imager/models/Imager_ImagePathsModel.php(193): Craft\Imager_ImagePathsModel->_downloadFile('/Users/bburwell...', 'http://foo...')
#1 /foo/craft/plugins/imager/models/Imager_ImagePathsModel.php(50): Craft\Imager_ImagePathsModel->_getPathsForUrl('http://d3qzbx7r...')
#2 /foo/craft/plugins/imager/services/ImagerService.php(166): Craft\Imager_ImagePathsModel->__construct(Object(Craft\FocusPoint_AssetFileModel))
#3 /foo/craft/plugins/imager/variables/ImagerVariable.php(26): Craft\ImagerService->transformImage(Object(Craft\FocusPoint_AssetFileModel), Array, Array, NULL)
#4 /foo/craft/app/vendor/twig/twig/lib/Twig/Template.php(615): Craft\ImagerVariable->transformImage(Object(Craft\FocusPoint_AssetFileModel), Array, Array)
#5 /foo/craft/app/etc/templating/BaseTemplate.php(64): Twig_Template->getAttribute(Object(Craft\ImagerVariable), 'transformImage', Array, 'method', false, false)
#6 /foo/craft/storage/runtime/compiled_templates/07/07a248374f7f0a1b509929d24f93fe923f5b5b4f5a725e04e09832a913adf308.php(307): Craft\BaseTemplate->getAttribute(Object(Craft\ImagerVariable), 'transformImage', Array, 'method')
```

Here's the error I'm seeing on the front-end of the site.
![front-end-error](https://cloud.githubusercontent.com/assets/1228671/22001578/bfb7a306-dc0b-11e6-9ae2-1af7b8cc73e3.jpg)

If there's any more info I can pass along that might be helpful please let me know. Thanks again.

**Comment by brettburwell** [comment]
I'm a bugger for not following up on this @aelvan. My apologies. 

I never did get to the bottom of the issue entirely, but for reasons unrelated to Imager, we ended up moving away from Cloudfront on the site that was generating the errors, so it ultimately became a moot point. 

Thanks again for the followups on this. I realize this is obviously a free add-on and very much appreciate your time trying to help me debug the issue.
