### ISSUE TITLE
Created site on test server. Enabled Imagick 75% through populating content and now unable to view images

### ISSUE THREAD

**Issue by Midknight** [aelvan/Imager-Craft#62]
Installed Craft on a XAMPP Windows environment. Wasn't at all interested in setting up Imagick. Finally thought after initial setup of CMS with templates to bring in Imager to work with. Then decided to enable Imagick. Now I am unable to view any images manipulated with Imager. Set my general.php config file to 'imageDriver' => 'gd'. I go to each page that I have used Imager. No problem. Switch off the config and I assume the cache is working with the page. Clear cache and update Asset index. With gd default turned off back to Unable to open image (E:\xampp\htdocs\craft\app\vendor\pixelandtonic\imagine\lib\Imagine\Imagick\Imagine.php(57))
Feels like I should have started with Imagick enabled.

**Comment by aelvan** [comment]
Is Imagick working for normal Craft transforms (not using Imager)? What PHP version are you running?

**Comment by Midknight** [comment]
I am not using any normal Craft transforms at the moment. I am running 5.5.30

**Comment by aelvan** [comment]
Ok, but could you try to set up a minimal test that tries to do a normal Craft-transform with Imagick, somthing like:

`{{ myAsset.getUrl({ width: 600 }) }}`

This is almost certainly something wrong with your environment, so finding out if Imagick works at all with Craft is the first step on the way to figuring out where the problem is.

**Comment by Midknight** [comment]
Looks to be my environment. Windows and XAMPP are a cursed world for development that I have no way to get out of as it is our companies environment. Need to find a compatible version with its accompanying DLL. Thanks for the help.
