### ISSUE TITLE
Debugging with jpegoptim: how do I know it's working?

### ISSUE THREAD

**Issue by howells** [aelvan/Imager-Craft#67]
I have configured Imager to use Jpegoptim which I installed via homebrew, so in my imager.php in /config I have this:

```
'jpegoptimEnabled' => true,
'jpegoptimPath' => '/usr/local/Cellar/jpegoptim/1.4.4/bin/jpegoptim',
'jpegoptimOptionString' => '-s',
```

however when the transformations happen I have no idea if jpegoptim is being used: and in fact the file sizes are as large as with jpegoptim disabled, so I assume something's not right. How can I go about debugging this?

**Comment by aelvan** [comment]
You could disable the imager cache and toggle if jpegoptim is enabled or not, refresh your template, and see if the image changes size at all. 

Also, by default jpegoptim performs lossless optimizations, `-s` just strips some metadata. If your jpegs are already optimized, there may be nothing to gain. You could test by adding `-m20` to the option string, that'll apply compression (quality 20) to all images. You should notice a seriously smaller filesize, and really crappy quality. :) So, of course, only do this as a test, don't do it in production.

**Comment by howells** [comment]
Yeah I've already tried both with no difference unfortunately. Ideally I'd like it just to error out if jpegoptim is enabled but the executable can't be found, for example. 

So let's assume it isn't working, how else can I debug?

**Comment by aelvan** [comment]
Yes, seems like Imager will move on silently if the executables for optimizations can't be found. I've added a check which will log an error, it'll be in the next version. 

Are you running the optimizations as a task, or runtime. If task, try changing to `'optimizeType' => 'runtime'`. Also, make sure you turn off the Imager cache when testing, the optimization will only run when the transform is first created.

I assume you're on osx since you reference Homebrew? What webserver/php setup are you running? I guess that in some cases php won't have access to do a `shell_exec`, but it's kind of unlikely if you're running this in a typical dev environment.

**Comment by howells** [comment]
Oh great I'll keep an eye out for the next version - when you reckon it might be available?

I'm running them at runtime, and yeah have the cache disabled.

I'm using MAMP Pro as my environment, so I guess that should be fairly typical?!

**Comment by sapila** [comment]
What i did to see if the optimizations worked is that i set the `logOptimizations` to true. This logs the optimization and also a percentage of optimization like 
```
imagePath/image.jpg 380x380 24bit N JFIF  [OK] 40140 --> 3369 bytes (91.61%), optimized.
```
Hope this helps

**Comment by howells** [comment]
@sapila my logs don't show anything like that: 

`2017/01/12 14:22:53 [info] [plugin] [Forced] Optimized image /Users/danielhowells/Sites/goldteeth/dist/public/imager/s3_amazonaws_com/goldteeth-prod/Benjamin-Bouchet/CAFE_b1578e515a03e7dbce410a2349dc9753.jpg `

so clearly jpegoptim isn't working

**Comment by howells** [comment]
Okay just so you know I have finally gotten it to work, but naturally I have no idea how or why! So this can be closed, but the error being logged if the executable can't be found would be useful.

**Comment by iamtompickering** [comment]
I know this has been closed but I am getting the exact same error and not seeing any additional compression take place on my images. Did you ever figure out why it was happening for you? I have tried all sorts of things but cannot seem to get it working!
