### ISSUE TITLE
How to create an image

### ISSUE THREAD

**Issue by 0xsven** [aelvan/Imager-Craft#69]
This might be outside of the scope of imager:

I want to create a base 64 image with just one color. 

This image is going to be populating the image elements before my lazy loading is replacing it with the actual image.

Why not using a css background-color? Because on page load I am not aware of the height of the image.

Does this make sense?

**Comment by aelvan** [comment]
Background color for base64Pixel was added in 1.5.2. You can now do: `{{ craft.imager.base64Pixel(200, 200, '#f00') }}`
