### ISSUE TITLE
Imageoptim appears to have frozen

### ISSUE THREAD

**Issue by 0xsven** [aelvan/Imager-Craft#71]
I am building a website with a lot of images. For each image I am using imager to create several transforms. I am storing all imager generated files on S3, which works fine.

Recently I have decided to also upload the original images to S3. After changing all asset sources to S3 and manually uploading the files to the bucket my craftCms seems to go crazy.

Frontend is not responsive anymore and the control panel shows the process 'Optimizing images with optipng' running forever. 

Screenshot: https://www.evernote.com/l/ACWeRHp1luFDu4oNGrpVZsk0gtLaIGral-EB/image.png

Any idea what is happening here?

Addition:
I have put the asset sources back to local storage and the site is accessible again. But the processes are still frozen. I am a little worried -.-

Addition 2:
I have deployed the database and code to a staging server and it immediately started to do those background tasks. What is causing this?

**Comment by aelvan** [comment]
If you moved files from a local source to an external one, all asset transforms will be recreated the next time the transforms are requested. To Imager, these are now new files. 

If you have post-optimizations enabled, what happends now is:
– The original asset is downloaded from S3. 
– It's transformed and saved in the local imager path.
– It's uploaded to S3 (to make it instantly accessible) 
– A task is created and triggered, which 1) optimizes the image, and 2) uploads the new, optimized file again to S3.

This will take alot of resources and time. As with all tasks in Craft, if a task runs too long and reaches the execution timeout in PHP, or any of the timeouts in the webserver (nginx has one, PHP-FPM has one or two), the task will get stuck (see https://craftcms.com/support/stuck-tasks).

So, everything you describe is completely natural. That's no help of course, but there's not really a simple solution to this, the underlying problem is that web servers isn't suitable for transforming huge amounts of images. I suggest incerasing the max_execution_timeout in PHP as much as possible, increase or disable the timeout settings in the webserver, and just work your way through all the pages on the site, until all the transforms are created.

**Comment by 0xsven** [comment]
@aelvan  Thank you very much for explaining all this. It certainly helped me understand what happens and how to get rid of those stuck tasks. 

I have found another potential reason for all this:
The way I configured Imager it creates some sort of folder inside of a folder inside of a folder loop ([screenshot](https://www.evernote.com/l/ACV_uWtJJvZE-4buNZBCXSDMMKGbyFaDAqgB/image.png)). It seems plausible that this is what happened when my local server wasn't accessible. 

Could you maybe have a look at my config and tell me what I am doing wrong here:

```
  'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/imager/',
  'imagerUrl' => 'https://s3-us-west-1.amazonaws.com/bucket-name/imager/',
  [...]
  'awsEnabled' => true,
  'awsAccessKey' => '*******',
  'awsSecretAccessKey' => '***********',
  'awsBucket' => 'bucket-name',
  'awsFolder' => 'imager/',
```

**Comment by aelvan** [comment]
Huh, interesting. I'll have a look. Does it happen if you call the aws folder something other than imager?

**Comment by 0xsven** [comment]
I have tried to change the aws folder and it did what it was supposed to. Then I have removed the looping folders on S3 and they are gone now. Imager seems to work fine! 

I am not sure what happened. I am sure it was my fault since I did not fully understand imager

**Comment by aelvan** [comment]
It might actually be a bug in Imager that happends if a folder inside the bucket is used, and has the same name as the imager system path folder. I'll have a look at that. But as I understand it, you've got everything working now?

**Comment by 0xsven** [comment]
There is something weird happening now. 

[Screenshot](https://www.evernote.com/l/ACW1be1ZT8pADITcZuTQCq6ntBcJHpcLzU8B/image.png).

Imager seems to create the folder in my bucket from the system root ?

**Comment by aelvan** [comment]
That is so weird. What's your template code like, what are you passing in to Imager?

**Comment by 0xsven** [comment]
```

{% if image %}

	{% if not image.altText %}
		{% set altText = image.title %}
	{% else %}
		{% set altText = image.altText %}
	{% endif %}

	{# Settings #}
	{% set settings = {
		format: 'jpg',
		allowUpscale: false,
		mode: 'crop',
		jpegQuality: 80,
		position: image.focusPctX ~ '% ' ~ image.focusPctY ~ '%',
		interlace: true
	} %}

	{# Mobile: #}
	{% set mobileImages = craft.imager.transformImage(image,
		[
			{ width: 562, ratio: 1/2 },
			{ width: 1152, ratio: 8/5 },
			{ width: 1536, ratio: 64/75 },
			{ width: 1536, ratio: 1024/700 }
		], settings
	) %}

	{# Desktop: #}
	{% set desktopImages = craft.imager.transformImage(image,
		[
			{ width: 2160, ratio: 1440/900 },
			{ width: 3840, ratio: 2560/1250 }
		], settings
	) %}
	
	<picture>
		<source srcset="{{ desktopImages[1].url }}" media="(min-width: 1920px)">
		<source srcset="{{ desktopImages[0].url }}" media="(min-width: 1200px)">
		<source srcset="{{ mobileImages[3].url }}" media="(min-width: 1024px)">
		<source srcset="{{ mobileImages[2].url }}" media="(min-width: 768px)">
		<source srcset="{{ mobileImages[1].url }}" media="(min-width: 576px)">
		<img src="{{ mobileImages[0].url }}" 
			alt="{{ altText }}"
			class="{{ class }} object-fit">
	</picture>
	
{% endif %}
```

**Comment by 0xsven** [comment]
@aelvan 
I did a simple test: 
First I changed the awsFolder to 
`'awsFolder' => 'tranforms',`

Then I forced one image to reupload. After that I checked my S3 bucket:

> 2017-02-01 20:50:16     306482 tranforms/content/full-width/498/Hero_Cirro_Desktop_4b9e9c361ac6156ff035daf9442bd809.jpg
> 2017-02-01 20:50:16     197367 tranforms/content/full-width/498/Hero_Cirro_Desktop_79fc4f3a7ca1e3f31531ace0dd04ee10.jpg
> 2017-02-01 20:50:15      84187 tranforms/content/full-width/499/Hero_Cirro_Mobile_bade8f928c85b412a0bb9eb5855db509.jpg
> 2017-02-01 20:50:16      90012 tranforms/content/full-width/500/Hero_Cirro_Mobile_Landscape_4f804f9a5eaafffb5c6822e3c4e855d8.jpg
> 2017-02-01 20:50:16     194669 tranforms/content/full-width/501/Hero_Cirro_Tablet_c0731ad006930df48e5ba572950150e6.jpg
> 2017-02-01 20:50:16     209820 tranforms/content/full-width/502/Hero_Cirro_Tablet_Landscape_9dce6e2ff7f941f7e38f8ec8b743736e.jpg
> 2017-02-01 20:47:39     306482 tranforms/var/www/shared/public/imager/content/full-width/498/Hero_Cirro_Desktop_4b9e9c361ac6156ff035daf9442bd809.jpg
> 2017-02-01 20:47:39     197367 tranforms/var/www/shared/public/imager/content/full-width/498/Hero_Cirro_Desktop_79fc4f3a7ca1e3f31531ace0dd04ee10.jpg
> 2017-02-01 20:47:32      84187 tranforms/var/www/shared/public/imager/content/full-width/499/Hero_Cirro_Mobile_bade8f928c85b412a0bb9eb5855db509.jpg
> 2017-02-01 20:47:32      90012 tranforms/var/www/shared/public/imager/content/full-width/500/Hero_Cirro_Mobile_Landscape_4f804f9a5eaafffb5c6822e3c4e855d8.jpg
> 2017-02-01 20:47:33     194669 tranforms/var/www/shared/public/imager/content/full-width/501/Hero_Cirro_Tablet_c0731ad006930df48e5ba572950150e6.jpg
> 2017-02-01 20:47:35     209820 tranforms/var/www/shared/public/imager/content/full-width/502/Hero_Cirro_Tablet_Landscape_9dce6e2ff7f941f7e38f8ec8b743736e.jpg

As you can see it uploads every asset twice. Do you have any idea what causes this? 

(I am now using aws CLI since the web interface and transmit seem to be very unreiable.)

**Comment by 0xsven** [comment]
SOLVED IT!

This is bad:
`'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/imager/',`

This is good:
`'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/imager',`

You might want to check the way you build the paths, so there are no whites paces and no trailing slashes.

**Comment by aelvan** [comment]
That trailing slash should not be needed. I've tested loads of different setups now, and it works with or without trailing slash. I've also tested with original assets on S3 and local, with upload to S3 and not, and with and without various post-optimizing tools. All combinations work as they should.

This is either a matter of something being configured wrong, something weird in your server setup, or just a misunderstanding as to how Imager works.

I notice that between those to sets of images (the one with the local path added to it and the ones that appear to be correct), there's a 3 minute gap in the files timestamp. Are you running any post-optimizations on jpeg files? You mentioned optipng but that isn't being run in this case where the files are jpegs. If you turn off any such tools what happends then? Or could it be that you changed your configuration and ran the transforms twice? Did you ensure that the bucket was empty before running your last test?

Can you also try to output `$_SERVER['DOCUMENT_ROOT']` and confirm that it actually points to the correct public root folder? Do you use some kind of symlinks somewhere in your paths?

**Comment by 0xsven** [comment]
One thing that might help here is that it only happens on the server. I tested it on an amazon-linux + apache and on an ubuntu + nginx server. Both create those weird folders. It worked fine on my local machine.

I am realising now that I haven't intalled jpegoptim on the server. I can't reproduce it anymore. 

There for sure is some misconfiguration from my side. I will test more tomorrow. Getting late here.
