### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by thijskaspers** [aelvan/Imager-Craft#72]
We use Google Cloud buckets instead of AWS (S3).

I can only find references to AWS in Imager, am I correct that Google Cloud is not supported?

**Comment by aelvan** [comment]
That is correct, Imager only supports uploading transformed images to AWS. It can pull down assets from whatever url you supply, though, but I'm guessing you want to serve the transforms from GC too?

**Comment by thijskaspers** [comment]
Thanks for the quick reply!

Yeah, our websites run in Docker containers (on GC as well), so we want to store the images externally. That way, we  can move our websites across servers, without losing assets.

**Comment by thijskaspers** [comment]
@aelvan We are working on implementing GC. Once finished, we'll submit a pull request.

**Comment by thijskaspers** [comment]
@aelvan We have submitted the pull-request, see: https://github.com/aelvan/Imager-Craft/pull/78
