### ISSUE TITLE
Server problems

### ISSUE THREAD

**Issue by 0xsven** [aelvan/Imager-Craft#75]
My clients keep uploading huge images (6-10 MB PNGs) and the site seems to crash after that. The only way to get the website up again is to restart php-fpm.

Have you experienced something like this before? Can you give me a hint on how to get a more stable environment?

One idea would be to limit upload size in php.ini. But unfortunately there is this rather big video that would exceed the limit.

**Comment by 0xsven** [comment]
In my php-fpm error logs there is this:

[30-Jan-2017 01:30:55] WARNING: [pool www] child 3824 exited on signal 9 (SIGKILL) after 24.582025 seconds from start
[30-Jan-2017 01:30:56] WARNING: [pool www] child 3830 exited on signal 9 (SIGKILL) after 12.815219 seconds from start
[30-Jan-2017 01:31:18] WARNING: [pool www] child 3831 exited on signal 9 (SIGKILL) after 32.224688 seconds from start
[30-Jan-2017 01:31:29] WARNING: [pool www] child 3832 exited on signal 9 (SIGKILL) after 42.039661 seconds from start
[30-Jan-2017 01:31:34] WARNING: [pool www] child 3836 exited on signal 9 (SIGKILL) after 15.964953 seconds from start
[30-Jan-2017 01:31:37] WARNING: [pool www] child 3835 exited on signal 9 (SIGKILL) after 40.696857 seconds from start
[30-Jan-2017 01:31:37] WARNING: [pool www] server reached max_children setting (5), consider raising it

I asked a fellow php developer for help and he suggested to increase the memory limit just before doing image transforms. Will look into it more. Might also switch from apache to nginx.

In case this is not related to craft-imager, I am sorry for spamming your issues section. In that case close this issue.

**Comment by aelvan** [comment]
This is completely normal, letting a webserver try to transform an image that's 10MB won't work, least of all if you're trying to do multiple transforms on it. Memory is usually the problem, an image that is 4000x3000px will require 66MB of memory, and you usually have to double that to account for in-memory transforms. And it will take alot of time, so after a couple of transforms you'll probably time out. 

If you can't limit the upload size, have a look at [Image Resizer](https://github.com/engram-design/ImageResizer) which lets you resize the uploaded file when uploaded, which will help, assuming that the server has enough memory to do one transform.

**Comment by 0xsven** [comment]
@aelvan 
Thank you for that info. Will look into Image Reziser.

The problem is that the server doesn't respond any more at all after the crash. I am trying to wrap my head around how to configure php so it fails gracefully.

My thoughts are:
128M per process with max_children set to 5 = 640M 
Seems to be good, since I have 1 gig on my server.

I am not sure how the image transformation fits into processes? Is it one process for all the transformations? Or is it one process per transformation? 

Are all the transforms happen in parallel?

(I understand that this is outside of the scope of this plugin, but maybe it helps people that crash their server with how easy imager makes it to transform loooots of images :) )

**Comment by aelvan** [comment]
The max_children setting doesn't matter in this case. Every request runs as a separate process, so there's only 128MB available to the whole life-span of a request to Craft. 128MB is pretty low, we usually have it at 512MB.
