### ISSUE TITLE
Error When Using colorBlend + Imagick

### ISSUE THREAD

**Issue by poopsplat** [aelvan/Imager-Craft#77]
When trying to use the `colorBlend` adjustment I get the following error when loading the page:

```
Error

Call to undefined method Imagine\Imagick\Imagick::setImageClipMask()

[...]/craft/plugins/imager/services/ImagerService.php(1290)

```

[This](https://github.com/aelvan/Imager-Craft/blob/master/imager/services/ImagerService.php#L1290) is the line it's referring to.

I am testing locally with PHP V7.1.1 + Imagick V3.4.3RC4 (compiled with ImageMagick V7.0.4-6),
and was using the sample code for the color blend:

```
{% set transformedImage = craft.imager.transformImage(image, { width: 500, effects: { colorBlend: ['rgb(255, 153, 51)', 0.5] } }) %}
```

It seems that the `colorBlend` adjustment is the only one that causes and error, I've tested the rest without issue.

Anyone else experience this? Any thoughts as to what could be causing the error?

**Comment by aelvan** [comment]
I think ImageMagick v7 deprecated quite a few things, and I haven't really tested it yet since none of the distros I use come with it installed. If you don't need ImageMagic v7, I suggest compiling against the latest version of v6.

**Comment by poopsplat** [comment]
Ahh, yeah, I believe you're right. Thanks for the quick response!
