### ISSUE TITLE
Is a circle crop possible?

### ISSUE THREAD

**Issue by jamiepittock** [aelvan/Imager-Craft#8]
Would any of the current effects help me to crop an image as a circle, or maybe apply a mask to give the same effect? 

We have a template that is eventually being used as an HTML email and it includes round author avatars. Email clients don't have great support for rounding the images via CSS.

**Comment by aelvan** [comment]
No, sorry, that's not possible at the moment. I've toyed with the idea of implementing rounded corners like in CE Image for EE, which could be used to make a rounded image, but haven't had the time to have a look at it yet.

**Comment by jamiepittock** [comment]
No problem, thanks for the reply.

**Comment by lboaretto** [comment]
I needed rounded corners... 👍

**Comment by john-henry** [comment]
+1 for this feature. Same reason as Jamie. HTML email

**Comment by john-henry** [comment]
For anybody interested you can circumvent this by using a watermark as a mask. Slight hack but handy workaround. Some example code below.

```
{% set watermark = '/assets/img/circular-mask.png' %}
{% set authorImage = block.authorHeadshot.first() %}
{% set transformedImage = craft.imager.transformImage(authorImage, {
       width: 120,
       height: 120,
       mode: 'crop',
       quality:90,
       watermark: { image: watermark, width: 120, height: 120, position: { left: 0, top: 0 }, opacity: 1 },
       position: authorImage.focusPctX ~ '% ' ~ authorImage.focusPctY ~ '%'
 }) %}
```
