### ISSUE TITLE
Length of either side cannot be 0 or negative, current size is x

### ISSUE THREAD

**Issue by cmalven** [aelvan/Imager-Craft#81]
I'm getting the following error using using Imager `1.4.0` with Craft `2.6.2956`

```
Imagine\Exception\InvalidArgumentException
Length of either side cannot be 0 or negative, current size is x
```

I'm definitely passing valid assets, width, height, and other parameters to `craft.imager.transformImage` as you can see in the attached stack trace.

Can you see any details that I'm missing that would cause this error?

![imager-error-stack-trace](https://cloud.githubusercontent.com/assets/610118/22988847/26d9ae92-f379-11e6-98f1-4cd98b4952ad.png)

**Comment by aelvan** [comment]
What filetype is the file you're trying to transform? Does it happen for all images, or just one of them?

**Comment by cmalven** [comment]
@aelvan _hangs head in shame_ One of them was an `svg`…

**Comment by bymayo** [comment]
I'm also having this issue when pulling images from an API where the URL does not contain the file format on the file... But, when they are downloaded they are JPEG.

This works perfectly fine locally, but just not on a production server. 

Any ideas what this could be?

**Comment by bymayo** [comment]
Coming back to this... We need to allow the field to add SVG's to the field Imager is transforming.

So it would be good if Imager could determine and skip SVG's because this breaks the site if they are uploaded.

Currently we're resorting in changing back to PNG's, but this isn't ideal.
