### ISSUE TITLE
ImageMagick v7 compatibility

### ISSUE THREAD

**Issue by dennisfrank** [aelvan/Imager-Craft#83]
Hi,

on my client’s (shared hosting) server is ImageMagick in version 7.0.2 installed. I’m afraid I can not change it to v6 (as suggested in https://github.com/aelvan/Imager-Craft/issues/77#issuecomment-277013066).

I tried a few manipulations (resizing, modulate, colorBlend, contrast) with Imager. No problems on my local dev machine with ImageMagick 6.9.6. But on my client's server I get the following error when I try load a page with image manipulations:

> Undefined class constant 'IMGTYPE_TRUECOLORALPHA

From the craft.log:

> **Level:** error
> **Category:** exception.error
> **Message:** Error: Undefined class constant 'IMGTYPE_TRUECOLORALPHA' in /PATH-TO-SITE/craft/app/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Image.php:880

I hope you could check out the issues with ImageMagick 7. I don’t no much about ImageMagick and the Imagick PHP extension but if you need me to run some tests I would be happy to help!

https://www.imagemagick.org/script/porting.php

**Comment by aelvan** [comment]
I've tested Imager with ImageMagick 7 now, and apart from a small fix for the colorBlend effect, it all seems to work as it should. The error you were seeing was due to missing ImageMagick 7 support in the underlying Imagine library that ships with Craft. Seems like they have updated it now.
