### ISSUE TITLE
Imager extremely slow and task mode not running

### ISSUE THREAD

**Issue by andrew-anguiano** [aelvan/Imager-Craft#84]
I've been struggling with Imager for most of the evening. I originally wanted to use Preparse to generate image transforms on entry save, but that caused saving entries to take about 30 seconds. Also, I couldn't access the twig variable in the template that was supposedly parsed to return the Imager model. Having Imager run at runtime also causes about a 30 second delay when loading a page.

I tried to switch to task so that at least the page would load quicker, but I'm not seeing any task being run in the CP when I save the entry and the front end still runs super slow (20-30s for two images to transform to three sizes). 

Any ideas would be great as I'm struggling to figure out what else to try to implement Imager without a ton of TTFB.

**Comment by aelvan** [comment]
How many images are you creating and what are the size (in pixels and bytes) of the original? 

Regarding runtime/tasks, there is an option for running post-optimizations (like optipng and jpegoptim) as tasks, but the actual transforms are always running at "runtime".

**Comment by andrew-anguiano** [comment]
I'm generating 3 sizes. The original image is roughly 6000x4000px and 12.5MB. I was mostly testing the worst case scenario if a client should try to upload an image that's much too large. I can just set a max size on the asset field though.

**Comment by aelvan** [comment]
That's unfortunately how slow it is to manipulate big images on standard webhosting. :-/ I'd suggest using something like [Image Resizer](https://github.com/engram-design/ImageResizer) to ensure that the images are resized reasonable size on upload. Or, you could transform in two steps, first to a size that's a little bigger than your biggest transform with max quality, and then do the actual transforms using that image.
