### ISSUE TITLE
jpegoptim: Error when open_basedir is restricted.

### ISSUE THREAD

**Issue by thomasvankerckvoorde** [aelvan/Imager-Craft#85]
In the ImagerService.php file around rule 1401 there is a conditional to check if the jpegoptim plugin exists.

I get this error:
`[error] [php] file_exists(): open_basedir restriction in effect. File(/usr/bin/jpegoptim) is not within the allowed path(s)`

But I was able to get it working temporary by removing this conditional (It seems the file_exists() method is throwing the error).

![screen shot 2017-03-08 at 15 01 50](https://cloud.githubusercontent.com/assets/2323270/23706871/4c3129d4-0410-11e7-8f69-f230ed654dea.png)

I'm not sure this is an issue of my hosting provider, because the compression seems to work without the conditional. (But I rather do not change the plugin core)

I hope I made this problem clear because my knowledge of PHP is rather limited.

**Comment by aelvan** [comment]
Not sure why this works when you remove the conditional, it shouldn't. Are you sure that the files are actually optimized? The whole point of open_basedir PHP setting are that the website shouldn't get access to files outside of the paths that are allowed in the setting. So you shouldn't be able to use jpegoptim if it's in /usr/bin, and that's not allowed (which would be very likely in such a setup).

You'll either need to get your hosting provider to turn off open_basedir (unlikely), move the site to a hosting setup that doesn't use open_basedir (most modern platforms don't), or copy/move the jpegoptim file somewhere inside the allowed paths.
