### ISSUE TITLE
`_getCropPoint` incorrect offset order

### ISSUE THREAD

**Issue by fyrebase** [aelvan/Imager-Craft#86]
It looks like when calling `list` in the `_getCropPoint` method within the `ImagerService` that the order is the wrong way round.

It should be `list($topOffset, $leftOffset)` rather than `list($leftOffset, $topOffset)`

**Comment by aelvan** [comment]
Noo, I don't think so. :) What's the error that you're seeing which makes you think it's wrong? It really all depends on the value you pass to the position parameter, and that should be "<left>% <top>%". So `position: "0% 50%"` means crop from left side, center vertically. If you switch these around, you'd get the wrong crop.

**Comment by fyrebase** [comment]
You're right, the problem is self inflicted. I have created a focus point field on a front end form and I am feeding the crop points in the wrong order. Sorry about that, delete issue at will :D
