### ISSUE TITLE
Strange getimagesize(): Read error! on image called placeholder.jpg

### ISSUE THREAD

**Issue by vegardsando** [aelvan/Imager-Craft#91]
This is kinda funny, but weird. Not sure if it only happens on my local mamp. But I created an image meant to be a placeholder. So I named the image "placeholder.jpg" and uploaded it as normal to Assets. 

What's weird is that when I add that image to some field in an article, I get the **getimagesize(): Read error!** on the front end. 

The image is only 35.53KB, but this is the real kicker,  I renamed the same image to "soontobe.jpg" and now it works. So I tried to re-rename it back to "placeholder.jpg", error. Whaat? Ok? Tried renaming it to "placeholder1.jpg" and it works. 

Soooo, conclusion, if you upload an image called placeholder.jpg it craps out. I have no explanation for this, maybe you've got some leftovers in your code or something? Cause I see no logical reasoning why this should happen.

**Comment by aelvan** [comment]
That is indeed very weird! I've tested it now, and in my test environment there's no problem transforming a file named placeholder.jpg, see: 

![image](https://cloud.githubusercontent.com/assets/2675644/24325488/54219498-119a-11e7-9146-15575f4e1b9f.png)

I've search the imager source (and Craft) for references to placeholder.jpg (or just placeholder), and I can't find any. Either, something wrong happend when you first tried to create the file, which resulted in the file written to disk being corrupted. Have you tried deleting the transformed file in the Imager cache? If the image asset is on a cloud storage, try to clear the remote images cache too.

Or, you have something weird in your apache/nginx config which would result in the request for the file being rewritten or something, but that's maybe more unlikely. 

Try clearing the cache and let me know if that worked.
