### ISSUE TITLE
Check for executables is not working for "global binaries" (Image Optimizations)

### ISSUE THREAD

**Issue by christianruhstaller** [aelvan/Imager-Craft#92]
This change introduced a file check for the binary: https://github.com/aelvan/Imager-Craft/commit/7aabb13136850f521c58628f86eb0d446eadbc4f

If the binary is available via the default os paths (/bin,…) this check will fail and return that the file does not exist.

Using the custom Path for the binary is not an option if the `open_basedir` restricts access to /bin,…

**Comment by thomasvankerckvoorde** [comment]
See issue #85 
I did not found a solution besides removing the conditional.

**Comment by christianruhstaller** [comment]
How about adding an option, so the file check can be disabled? This would at least enable the optimization on such systems.

**Comment by aelvan** [comment]
I've added a `skipExecutableExistCheck` config setting to version 1.5.1 that let's you disable the check.
