### ISSUE TITLE
Same image for all in loop using external URLs

### ISSUE THREAD

**Issue by john-henry** [aelvan/Imager-Craft#94]
Craft 2.6.2967 and Imager 1.5.0

I have a plain text field in an entry that holds an external URL to an image

The pattern for the external image URL looks like this

_example.com/news/GetImg.aspx?ArticleID=12345&ImageTypeID=2_

When I loop through the images I get the first returned for every one and only one is added to S3 and renamed like so

_/made/example_com/news/GetImg_c1e9e2f1c244d11eed18e13b29d61849.aspx_

```
{% for entry in craft.entries.section('news').limit(25).find() %}

{% set marketImage = entry.newsImage %}
{% set transformedImage = craft.imager.transformImage(marketImage, {
             width: 80,
             ratio: 4/3,
            mode: 'crop',
             quality:90
}) %}
<li><img src="{{ transformedImage.url }}"></li>

{% endfor %}
```
Any ideas or am I missing some basic Twig trick here?

**Comment by john-henry** [comment]
OK so I solved my problem. Likely an edge case.

https://github.com/aelvan/Imager-Craft/blob/master/imager/models/Imager_ImagePathsModel.php#L153

__getPathsForUrl_ was not accounting for the query after parsing external URL. So I just built that in.

General gist and inclusion of $pathQuery


       $pathQuery = null;
        if (parse_url($convertedImageStr, PHP_URL_QUERY)){
            $pathQuery = $urlParts['query'];
        }
        
        $hashRemoteUrl = craft()->imager->getSetting('hashRemoteUrl');
        $hashPath = craft()->imager->getSetting('hashPath');
        
        if ($hashPath) {
            $targetFolder = '/' . md5($pathParts['dirname'] . $pathQuery);
        } else {
            $targetFolder = $pathParts['dirname'] . $pathQuery;
        }


        if ($hashRemoteUrl) {
            if (is_string($hashRemoteUrl) && $hashRemoteUrl == 'host') {
                $parsedDirname = substr(md5($urlParts['host']), 0, 10) . $targetFolder;
            } else {
                $parsedDirname = md5($urlParts['host'] . $pathParts['dirname'] . $pathQuery);
            }
        } else {
            $parsedDirname = str_replace('.', '_', $urlParts['host']) . $targetFolder;
        }

**Comment by bymayo** [comment]
I feel like this should be part of the main build. I've had the same issue when loading images up via an API where the URL contains a query string.

I've fixed this a few times using @john-henry fix - But it keeps getting overwritten when I update the plugin :(

**Comment by aelvan** [comment]
I agree, this should probably be taken into account when processing external urls. Does anyone have a couple of public urls that uses this format? It's probably more work setting up a test case with an image server that returns images dynamically, than actually implementing the fix. ;)

**Comment by bymayo** [comment]
I can certainly send you some, but possibly not on here as they are API requests (That we then hash etc)

**Comment by aelvan** [comment]
Ok, can you PM them to me on Slack?

**Comment by aelvan** [comment]
This was fixed in 1.5.3.

**Comment by JonnyTurnerUK** [comment]
Just installed Imager v2.1.2 on Craft 3.0.33 and getting this exact issue. Anyone experienced this with the same versions?

**Comment by john-henry** [comment]
@JonnyTurnerUK Try using the `useRemoteUrlQueryString` config setting.
When enabled, any query strings in external urls will be included in the transformed filename.

**Comment by JonnyTurnerUK** [comment]
Thanks for the super quick reply @john-henry. I've tried that as I thought that would be the option to use but no joy. Here's my latest config / attempt:

    {% set images = value|split(',') %}
    {%- for image in images -%}
        {% set newBaseImage = craft.imager.transformImage(image, {
            width: 740,
            height: 494,
            format: 'jpg',
            jpegQuality: 70,
            useRemoteUrlQueryString: true,
            cacheEnabled: false,
            cacheRemoteFiles: false
        }) %}
        {{ newBaseImage.url }}{%- if loop.last == false -%},{%- endif -%}
    {%- endfor -%}

**Comment by john-henry** [comment]
@JonnyTurnerUK I would have thought 

```
useRemoteUrlQueryString: true,
cacheEnabled: false,
cacheRemoteFiles: false
```
needs to go into your `craft/config/imager.php` (renamed config file from plugin folder). They are config variables and not transform parameters

**Comment by JonnyTurnerUK** [comment]
Yep! That'd be it. I just completely over looked it, thanks again - really appreciate it.
