### ISSUE TITLE
Clarity on using mozjpeg

### ISSUE THREAD

**Issue by lexbi** [aelvan/Imager-Craft#95]
Mozjpeg doesn't actually appear to have an executable, so the path example `/usr/bin/mozjpeg` for the option `mozjpegPath ` doesn't make sense.

mozjpeg ships with 2 tools `cjpeg` and `jpegtran`: https://github.com/mozilla/mozjpeg/issues/229

cjpeg for lossy
jpegtran for lossless

Does imager use these tools & should the path just be be to the mozjpeg folder as you refer to is as an `executable` in the readme?

**Comment by aelvan** [comment]
The relevant tool is the jpegtran version compiled with mozjpeg optimizations. You set the option to:

```
'mozjpegPath' => '/whatever/path/you/compiled/to/bin/jpegtran'
```

Or you could rename the compiled version of jpegtran to mozjpeg, and put it in /usr/bin. The path and name of the executable is just an example.

Also, see this blog post: https://nystudio107.com/blog/installing-mozjpeg-on-ubuntu-16-04-forge

**Comment by lexbi** [comment]
Ok, thanks for clarifying, it really wasn't clear that you create a simlink from your readme, and, which tool you had used.

Seems like a bit of a waste that imager only uses the lossless optimisation of mozjpeg. jpegtran wont alter the filesizes that much?

What happens when you set `'jpegQuality' => 80,` when you use mozjpeg? Does it ignore this option? Or does it do another type of lossy compression on top?

**Comment by aelvan** [comment]
All the external tools that Imager integrates with are post-optimization tools. So the image will be transformed with either GD or Imagick (depending on which driver you've chosen), and then the transformed image is passed on to the enabled tools for further optimization. So `jpegQuality` is the quality that GD/Imagick will use.

Imager wasn't really made to use **only** an external tool to do the complete transform, without using GD or Imagick. But there's nothing stopping you from adding the path of cjpeg to `mozjpegPath`, and adding the necessary options to the option string if you want to do the compression with cjpeg. But the image would be compressed twice, so I'm not sure if there would be any point.

**Comment by lexbi** [comment]
Great ok thanks for the info 👍
