### ISSUE TITLE
Trim superfluous folders from S3 URL

### ISSUE THREAD

**Issue by ijy** [aelvan/Imager-Craft#99]
It seems that when using Imager to store transforms on S3 folders are created inside the S3 bucket which duplication the S3 URL and bucket name. For example, with the following configuration settings:

```
'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/uploads/imager/',
'imagerUrl' =>  'https://s3-eu-west-1.amazonaws.com/bucket-name/transforms',
'awsFolder' => 'transforms',
```

Imager creates folders and sub-folders in the bucket which duplicate the full path:

```
https://s3-eu-west-1.amazonaws.com/bucket-name/transforms/s3-eu-west-1_amazonaws_com/bucket-name/folder/image.jpg
```

Is it necessary to duplicate the region URL and bucket name in the AWS folder (and image path)? I'd much prefer the simpler:

```
https://s3-eu-west-1.amazonaws.com/bucket-name/transforms/folder/image.jpg
```

Is this possible?

**Comment by aelvan** [comment]
Yes, it's necessary. The fact that the bucket you have the original file on, and where you put the transformed images, is not something Imager knows about. The files are treated as an external URL, and to ensure that file paths are unique, the hostname and path to the original file needs to be part of the transformed files path. See https://github.com/aelvan/Imager-Craft/issues/76.

As noted in that thread, if you want to shorten the url you could use `hashPath` and/or `hashRemoteUrl`.
